# Generated by Devo (Lead Developer)
import re
from typing import List, Tuple, Dict

class SpecParser:
    """Analyzes technical text to extract entities and relationships."""
    
    def __init__(self):
        self.pattern_keywords = {
            "sequence": ["sequence", "interaction", "call flow", "request"],
            "flowchart": ["workflow", "step", "process", "decision", "if/then"],
            "erd": ["schema", "database", "entity", "table", "relationship"],
            "state": ["state", "status", "transition", "lifecycle"],
            "class": ["hierarchy", "composition", "class", "inherits"]
        }

    def determine_diagram_type(self, text: str) -> str:
        text_lower = text.lower()
        scores = {k: sum(1 for word in v if word in text_lower) for k, v in self.pattern_keywords.items()}
        return max(scores, key=scores.get) if any(scores.values()) else "flowchart"

    def extract_triplets(self, text: str) -> List[Tuple[str, str, str]]:
        """
        Extracts (Subject, Action, Object) triplets.
        Example: 'User calls API' -> ('User', 'calls', 'API')
        """
        triplets = []
        # Simplified regex for demonstration; in production, this would use an NLP NER model
        pattern = r"([A-Z][\w\s]+)\s(calls|updates|triggers|sends|returns|inherits|contains)\s([A-Z][\w\s]+)"
        matches = re.findall(pattern, text)
        for match in matches:
            triplets.append((match[0].strip(), match[1].strip(), match[2].strip()))
        return triplets