# Generated by Verify (QA Engineer)
import pytest
from typing import Dict, List
from dataclasses import is_dataclass
from runtime.interface import ContainerRuntime, ContainerResult

class MockRuntime(ContainerRuntime):
    """
    Concrete implementation of ContainerRuntime for interface validation.
    Used to verify that the ABC contract is enforceable and functional.
    """
    def run_command(
        self, 
        image: str, 
        command: List[str], 
        env: Dict[str, str] = None, 
        volumes: Dict[str, str] = None, 
        cpu_limit: float = 1.0, 
        mem_limit: str = "512m", 
        timeout: int = 300
    ) -> ContainerResult:
        # Simulate a successful execution
        return ContainerResult(
            exit_code=0,
            stdout="Success",
            stderr="",
            duration_ms=120.5,
            runtime_used="MockRuntime"
        )

    def check_health(self) -> bool:
        return True

class FailingRuntime(ContainerRuntime):
    """Concrete implementation that simulates runtime failures."""
    def run_command(self, *args, **kwargs) -> ContainerResult:
        return ContainerResult(
            exit_code=1,
            stdout="",
            stderr="Execution Failed",
            duration_ms=10.0,
            runtime_used="FailingRuntime"
        )

    def check_health(self) -> bool:
        return False

@pytest.fixture
def success_runtime():
    return MockRuntime()

@pytest.fixture
def failure_runtime():
    return FailingRuntime()

class TestContainerResult:
    """Validates the ContainerResult Data Transfer Object."""
    
    def test_dataclass_properties(self):
        """Ensure ContainerResult is a dataclass with correct fields."""
        assert is_dataclass(ContainerResult)
        res = ContainerResult(0, "out", "err", 100.0, "docker")
        assert res.exit_code == 0
        assert res.stdout == "out"
        assert res.stderr == "err"
        assert res.duration_ms == 100.0
        assert res.runtime_used == "docker"

    def test_type_consistency(self):
        """Verify that the DTO handles expected types without coercion errors."""
        res = ContainerResult(
            exit_code=127, 
            stdout="command not found", 
            stderr="sh: 1: not found", 
            duration_ms=5.2, 
            runtime_used="podman"
        )
        assert isinstance(res.exit_code, int)
        assert isinstance(res.duration_ms, float)

class TestContainerRuntimeInterface:
    """Validates the ContainerRuntime ABC contract."""

    def test_cannot_instantiate_abc(self):
        """Verify that ContainerRuntime cannot be instantiated directly."""
        with pytest.raises(TypeError) as excinfo:
            ContainerRuntime()
        assert "Can't instantiate abstract class ContainerRuntime" in str(excinfo.value)

    def test_run_command_success(self, success_runtime):
        """Test the interface via a successful mock implementation."""
        result = success_runtime.run_command(
            image="alpine:latest",
            command=["ls", "-la"],
            env={"DEBUG": "1"},
            volumes={"/tmp": "/tmp"},
            cpu_limit=0.5,
            mem_limit="256m",
            timeout=60
        )
        assert result.exit_code == 0
        assert result.runtime_used == "MockRuntime"
        assert result.stdout == "Success"

    def test_run_command_failure(self, failure_runtime):
        """Test the interface via a failing mock implementation."""
        result = failure_runtime.run_command(
            image="alpine:latest",
            command=["false"]
        )
        assert result.exit_code == 1
        assert "Execution Failed" in result.stderr

    def test_health_check_positive(self, success_runtime):
        """Verify health check returns True for healthy runtimes."""
        assert success_runtime.check_health() is True

    def test_health_check_negative(self, failure_runtime):
        """Verify health check returns False for unhealthy runtimes."""
        assert failure_runtime.check_health() is False

    @pytest.mark.parametrize("cpu, mem, timeout", [
        (0.1, "128m", 1),
        (16.0, "64g", 3600),
        (1.0, "512m", 300),
    ])
    def test_parameter_boundaries(self, success_runtime, cpu, mem, timeout):
        """Ensure the interface accepts a wide range of resource constraints."""
        result = success_runtime.run_command(
            image="test", 
            command=["echo"], 
            cpu_limit=cpu, 
            mem_limit=mem, 
            timeout=timeout
        )
        assert result is not None

    def test_optional_parameters_defaults(self, success_runtime):
        """Verify that the interface handles omitted optional parameters."""
        # Only providing required arguments
        result = success_runtime.run_command(
            image="alpine", 
            command=["whoami"]
        )
        assert result.exit_code == 0