# Generated by Verify (QA Engineer)
import pytest
from unittest.mock import MagicMock, patch
from src.diagram_skill.engine import DiagramEngine

class TestDiagramEngine:
    """
    Precision Reliability Suite for DiagramEngine.
    Focuses on orchestration logic, error handling, and DSL synthesis.
    """

    @pytest.fixture
    def engine(self):
        """Provides a clean instance of DiagramEngine for each test."""
        return DiagramEngine()

    @pytest.fixture
    def mock_dependencies(self, engine):
        """Mocks the parser and templates to isolate the engine logic."""
        engine.parser = MagicMock()
        engine.templates = MagicMock()
        return engine.parser, engine.templates

    def test_generate_success_sequence(self, engine, mock_dependencies):
        """
        Scenario: Valid sequence diagram specification.
        Expected: Correct Mermaid wrapping and sequence-specific DSL.
        """
        mock_parser, mock_templates = mock_dependencies
        
        # Setup Mocks
        spec = "User sends request to Server"
        mock_parser.determine_diagram_type.return_value = "sequence"
        mock_parser.extract_triplets.return_value = [("User", "sends request", "Server")]
        mock_templates.SEQUENCE = "sequenceDiagram"
        
        result = engine.generate(spec)
        
        # Assertions
        assert "```mermaid" in result
        assert "sequenceDiagram" in result
        assert "User->>Server: sends request" in result
        assert "```" in result
        mock_parser.determine_diagram_type.assert_called_once_with(spec)

    def test_generate_success_flowchart(self, engine, mock_dependencies):
        """
        Scenario: Valid flowchart diagram specification.
        Expected: Correct Mermaid wrapping and flowchart-specific DSL.
        """
        mock_parser, mock_templates = mock_dependencies
        
        # Setup Mocks
        spec = "A leads to B"
        mock_parser.determine_diagram_type.return_value = "flowchart"
        mock_parser.extract_triplets.return_value = [("A", "leads to", "B")]
        mock_templates.FLOWCHART = "graph TD"
        
        result = engine.generate(spec)
        
        # Assertions
        assert "```mermaid" in result
        assert "graph TD" in result
        assert "A --> B" in result
        assert "```" in result

    def test_generate_no_triplets_fallback(self, engine, mock_dependencies):
        """
        Scenario: Specification provided but no triplets extracted.
        Expected: System should log warning and still attempt to build DSL (fallback).
        """
        mock_parser, mock_templates = mock_dependencies
        
        mock_parser.determine_diagram_type.return_value = "flowchart"
        mock_parser.extract_triplets.return_value = [] # Empty triplets
        mock_templates.FLOWCHART = "graph TD"
        
        result = engine.generate("Something vague")
        
        # Should still return a valid mermaid block even if empty/basic
        assert "```mermaid" in result
        assert "graph TD" in result

    def test_generate_exception_handling(self, engine, mock_dependencies):
        """
        Scenario: Parser raises an unexpected exception.
        Expected: Graceful failure returning the specific error string.
        """
        mock_parser, _ = mock_dependencies
        
        # Simulate a crash in the parser
        mock_parser.determine_diagram_type.side_effect = Exception("Parser Crash")
        
        result = engine.generate("Invalid Spec")
        
        assert result == "Error generating diagram: Specification too ambiguous."

    @pytest.mark.parametrize("diag_type, expected_header", [
        ("sequence", "sequenceDiagram"),
        ("flowchart", "graph TD"),
        ("unknown", "graph TD"), # Testing default behavior in _build_dsl if applicable
    ])
    def test_build_dsl_logic(self, engine, mock_dependencies, diag_type, expected_header):
        """
        Scenario: Testing the internal _build_dsl method with various types.
        Expected: Correct template header selection.
        """
        _, mock_templates = mock_dependencies
        mock_templates.SEQUENCE = "sequenceDiagram"
        mock_templates.FLOWCHART = "graph TD"
        
        triplets = [("X", "relates", "Y")]
        output = engine._build_dsl(diag_type, triplets)
        
        assert output.startswith(expected_header)

    def test_integration_flow_telemetry(self, engine, caplog):
        """
        Scenario: Verify that the engine logs the synthesis process.
        Expected: Log entries for initiation and type detection.
        """
        import logging
        with caplog.at_level(logging.INFO):
            # We use a real SpecParser/Templates here for a mini-integration check
            # assuming they are available in the environment
            engine.generate("User -> Server: Hello")
            
            assert "Initiating diagram synthesis..." in caplog.text
            assert "Detected diagram type" in caplog.text