# Generated by Verify (QA Engineer)
import pytest
from src.diagram_skill.parsers import SpecParser

class TestSpecParser:
    """
    Comprehensive test suite for SpecParser ensuring high-fidelity 
    extraction of diagram types and entity triplets.
    """

    @pytest.fixture
    def parser(self):
        return SpecParser()

    # --- Tests for determine_diagram_type ---

    @pytest.mark.parametrize("text, expected_type", [
        ("The system interaction involves a request from the client.", "sequence"),
        ("This workflow describes the decision process for approval.", "flowchart"),
        ("The database schema defines the entity relationship.", "erd"),
        ("The lifecycle includes a transition from Pending to Active.", "state"),
        ("The class hierarchy shows how the Child inherits from Parent.", "class"),
    ])
    def test_determine_diagram_type_success(self, parser, text, expected_type):
        """Verify that the parser correctly identifies diagram types based on keywords."""
        assert parser.determine_diagram_type(text) == expected_type

    def test_determine_diagram_type_fallback(self, parser):
        """Verify that the parser defaults to 'flowchart' when no keywords are found."""
        assert parser.determine_diagram_type("The weather is sunny today.") == "flowchart"
        assert parser.determine_diagram_type("") == "flowchart"

    def test_determine_diagram_type_case_insensitivity(self, parser):
        """Verify that keyword detection is case-insensitive."""
        assert parser.determine_diagram_type("SCHEMA and DATABASE") == "erd"
        assert parser.determine_diagram_type("sEqUeNcE") == "sequence"

    def test_determine_diagram_type_weighting(self, parser):
        """Verify that the type with the most keyword matches wins."""
        text = "The database schema defines the entity and the workflow process."
        # ERD has 'database', 'schema', 'entity' (3)
        # Flowchart has 'workflow', 'process' (2)
        assert parser.determine_diagram_type(text) == "erd"

    # --- Tests for extract_triplets ---

    @pytest.mark.parametrize("text, expected_triplets", [
        (
            "User calls API", 
            [("User", "calls", "API")]
        ),
        (
            "Admin updates Database and System triggers Alert", 
            [("Admin", "updates", "Database"), ("System", "triggers", "Alert")]
        ),
        (
            "The Manager sends Notification to the Employee", 
            [("Manager", "sends", "Notification")] # Note: regex captures [A-Z][\w\s]+
        ),
        (
            "BaseClass inherits DerivedClass", 
            [("BaseClass", "inherits", "DerivedClass")]
        ),
    ])
    def test_extract_triplets_success(self, parser, text, expected_triplets):
        """Verify that valid (Subject, Action, Object) triplets are extracted correctly."""
        assert parser.extract_triplets(text) == expected_triplets

    def test_extract_triplets_no_matches(self, parser):
        """Verify that no triplets are returned for non-matching text."""
        text = "This is a random sentence with no specific actions."
        assert parser.extract_triplets(text) == []

    def test_extract_triplets_case_sensitivity(self, parser):
        """
        Verify that entities must start with uppercase letters as per regex 
        ([A-Z][\w\s]+).
        """
        text = "user calls api" # Lowercase entities
        assert parser.extract_triplets(text) == []

    def test_extract_triplets_complex_spacing(self, parser):
        """Verify that the parser handles trailing/leading whitespace within matches."""
        text = "PaymentGateway   returns   TransactionResponse"
        # The regex captures the spaces, but the .strip() in the loop should clean them
        result = parser.extract_triplets(text)
        assert result == [("PaymentGateway", "returns", "TransactionResponse")]

    def test_extract_triplets_empty_input(self, parser):
        """Verify behavior with empty or null-like input."""
        assert parser.extract_triplets("") == []
        with pytest.raises(TypeError):
            parser.extract_triplets(None)