# Generated by Archi (Architect)
import os
import json
from pyspark.sql import SparkSession

# Define the metric collector function
def collect_metrics(system_id, metric_types):
    # Utilize system APIs and libraries to collect metrics
    metrics = {}
    for metric_type in metric_types:
        # Collect metric data
        metric_data = collect_metric_data(system_id, metric_type)
        metrics[metric_type] = metric_data
    return metrics

# Define the data processor function
def process_data(metrics):
    # Utilize Apache Spark for data processing
    spark = SparkSession.builder.appName("SystemMetricsSkill").getOrCreate()
    # Process metric data
    processed_metrics = spark.createDataFrame(metrics)
    return processed_metrics

# Define the output generator function
def generate_output(processed_metrics, output_format):
    # Utilize JSON and CSV libraries to generate output metrics
    if output_format == "json":
        output = json.dumps(processed_metrics.collect())
    elif output_format == "csv":
        output = processed_metrics.toPandas().to_csv(index=False)
    return output

# Define the error handler function
def handle_error(error):
    # Handle errors and exceptions
    print(f"Error: {error}")

# Define the main function
def main():
    system_id = "system-123"
    metric_types = ["cpu_usage", "memory_usage"]
    collection_interval = 60
    output_format = "json"
    
    try:
        metrics = collect_metrics(system_id, metric_types)
        processed_metrics = process_data(metrics)
        output = generate_output(processed_metrics, output_format)
        print(output)
    except Exception as e:
        handle_error(e)

if __name__ == "__main__":
    main()