# Generated by Archi (Architect)
"""
swarm_v2/skills/input_validation_skill.py
Advanced Input Validation Skill for Swarm OS v12
Implements comprehensive validation, sanitization, and type coercion with telemetry hooks.
"""

import re
import json
import logging
from typing import Any, Dict, List, Optional, Union, Callable
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, date
from uuid import UUID

# Configure module-level logger
logger = logging.getLogger(__name__)

class ValidationSeverity(Enum):
    """Severity levels for validation failures."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"

class ValidationError(Exception):
    """Custom exception for validation failures with structured context."""
    def __init__(self, message: str, field: str, severity: ValidationSeverity = ValidationSeverity.ERROR, context: Dict[str, Any] = None):
        self.field = field
        self.severity = severity
        self.context = context or {}
        super().__init__(f"[{severity.value.upper()}] Field '{field}': {message}")

@dataclass
class ValidationRule:
    """Defines a single validation rule with metadata."""
    name: str
    validator: Callable[[Any], bool]
    error_message: str
    severity: ValidationSeverity = ValidationSeverity.ERROR
    params: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ValidationResult:
    """Result of a validation operation with detailed diagnostics."""
    is_valid: bool
    errors: List[ValidationError] = field(default_factory=list)
    warnings: List[ValidationError] = field(default_factory=list)
    sanitized_value: Any = None
    telemetry: Dict[str, Any] = field(default_factory=dict)

class InputValidationSkill:
    """
    Advanced input validation engine with:
    - Type coercion and sanitization
    - Regex pattern matching
    - Range and boundary checks
    - Cross-field validation
    - Telemetry and observability
    - Configurable severity levels
    """

    # Common regex patterns for validation
    PATTERNS = {
        "email": r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        "uuid": r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
        "ipv4": r"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$",
        "url": r"^https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+[^\s]*$",
        "alphanumeric": r"^[a-zA-Z0-9]+$",
        "phone": r"^\+?1?\d{9,15}$",
        "date_iso": r"^\d{4}-\d{2}-\d{2}$",
        "datetime_iso": r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?$",
    }

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize the validation skill with optional configuration.
        
        Args:
            config: Dictionary with keys:
                - strict_mode (bool): Enable strict validation (default: True)
                - max_string_length (int): Maximum string length (default: 10000)
                - allowed_types (list): Allowed Python types for validation
                - custom_patterns (dict): Additional regex patterns
        """
        self.config = config or {}
        self.strict_mode = self.config.get("strict_mode", True)
        self.max_string_length = self.config.get("max_string_length", 10000)
        self.allowed_types = self.config.get("allowed_types", [str, int, float, bool, list, dict, None])
        self.custom_patterns = self.config.get("custom_patterns", {})
        self._validation_history: List[Dict[str, Any]] = []
        
        # Merge custom patterns with defaults
        self.patterns = {**self.PATTERNS, **self.custom_patterns}
        
        logger.info(f"InputValidationSkill initialized (strict_mode={self.strict_mode})")

    def validate_string(self, value: Any, field_name: str = "unknown", 
                       min_length: int = 0, max_length: Optional[int] = None,
                       pattern: Optional[str] = None, allow_empty: bool = False) -> ValidationResult:
        """
        Validate and sanitize a string value.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            min_length: Minimum allowed length
            max_length: Maximum allowed length (defaults to config max_string_length)
            pattern: Regex pattern to match against
            allow_empty: Whether empty strings are allowed
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "string", "timestamp": datetime.utcnow().isoformat()}

        # Type coercion
        if not isinstance(value, str):
            try:
                value = str(value)
                warnings.append(ValidationError(
                    f"Value coerced to string from {type(value).__name__}",
                    field_name, ValidationSeverity.WARNING
                ))
            except Exception as e:
                errors.append(ValidationError(
                    f"Cannot convert to string: {str(e)}",
                    field_name, ValidationSeverity.ERROR
                ))
                result.is_valid = False
                result.errors = errors
                result.warnings = warnings
                result.telemetry = telemetry
                self._log_validation(result, field_name)
                return result

        # Length checks
        if not allow_empty and len(value.strip()) == 0:
            errors.append(ValidationError(
                "String is empty or contains only whitespace",
                field_name, ValidationSeverity.ERROR
            ))

        if len(value) < min_length:
            errors.append(ValidationError(
                f"String length {len(value)} is less than minimum {min_length}",
                field_name, ValidationSeverity.ERROR
            ))

        max_len = max_length or self.max_string_length
        if len(value) > max_len:
            if self.strict_mode:
                errors.append(ValidationError(
                    f"String length {len(value)} exceeds maximum {max_len}",
                    field_name, ValidationSeverity.ERROR
                ))
            else:
                value = value[:max_len]
                warnings.append(ValidationError(
                    f"String truncated from {len(value)} to {max_len} characters",
                    field_name, ValidationSeverity.WARNING
                ))

        # Pattern matching
        if pattern and pattern in self.patterns:
            compiled_pattern = re.compile(self.patterns[pattern])
            if not compiled_pattern.match(value):
                errors.append(ValidationError(
                    f"Value does not match pattern '{pattern}'",
                    field_name, ValidationSeverity.ERROR
                ))
        elif pattern:
            # Custom regex pattern
            try:
                compiled_pattern = re.compile(pattern)
                if not compiled_pattern.match(value):
                    errors.append(ValidationError(
                        f"Value does not match custom pattern",
                        field_name, ValidationSeverity.ERROR
                    ))
            except re.error as e:
                errors.append(ValidationError(
                    f"Invalid regex pattern: {str(e)}",
                    field_name, ValidationSeverity.CRITICAL
                ))

        # Sanitize: strip whitespace and escape HTML
        sanitized = value.strip()
        sanitized = self._sanitize_html(sanitized)

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_numeric(self, value: Any, field_name: str = "unknown",
                        min_value: Optional[Union[int, float]] = None,
                        max_value: Optional[Union[int, float]] = None,
                        allow_float: bool = True,
                        allow_negative: bool = True) -> ValidationResult:
        """
        Validate and coerce a numeric value.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            min_value: Minimum allowed value
            max_value: Maximum allowed value
            allow_float: Whether floating point numbers are allowed
            allow_negative: Whether negative numbers are allowed
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "numeric", "timestamp": datetime.utcnow().isoformat()}

        # Type coercion
        if not isinstance(value, (int, float)):
            try:
                value = float(value) if allow_float else int(value)
                warnings.append(ValidationError(
                    f"Value coerced to numeric from {type(value).__name__}",
                    field_name, ValidationSeverity.WARNING
                ))
            except (ValueError, TypeError) as e:
                errors.append(ValidationError(
                    f"Cannot convert to numeric: {str(e)}",
                    field_name, ValidationSeverity.ERROR
                ))
                result.is_valid = False
                result.errors = errors
                result.warnings = warnings
                result.telemetry = telemetry
                self._log_validation(result, field_name)
                return result

        # Type check
        if not allow_float and isinstance(value, float):
            if value.is_integer():
                value = int(value)
                warnings.append(ValidationError(
                    "Float converted to integer",
                    field_name, ValidationSeverity.WARNING
                ))
            else:
                errors.append(ValidationError(
                    "Floating point values not allowed",
                    field_name, ValidationSeverity.ERROR
                ))

        # Sign check
        if not allow_negative and value < 0:
            errors.append(ValidationError(
                f"Negative value {value} not allowed",
                field_name, ValidationSeverity.ERROR
            ))

        # Range checks
        if min_value is not None and value < min_value:
            errors.append(ValidationError(
                f"Value {value} is less than minimum {min_value}",
                field_name, ValidationSeverity.ERROR
            ))

        if max_value is not None and value > max_value:
            errors.append(ValidationError(
                f"Value {value} exceeds maximum {max_value}",
                field_name, ValidationSeverity.ERROR
            ))

        # Sanitize: ensure within safe bounds
        sanitized = value
        if not self.strict_mode:
            if min_value is not None and sanitized < min_value:
                sanitized = min_value
                warnings.append(ValidationError(
                    f"Value clamped to minimum {min_value}",
                    field_name, ValidationSeverity.WARNING
                ))
            if max_value is not None and sanitized > max_value:
                sanitized = max_value
                warnings.append(ValidationError(
                    f"Value clamped to maximum {max_value}",
                    field_name, ValidationSeverity.WARNING
                ))

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_boolean(self, value: Any, field_name: str = "unknown") -> ValidationResult:
        """
        Validate and coerce a boolean value.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "boolean", "timestamp": datetime.utcnow().isoformat()}

        # Direct boolean check
        if isinstance(value, bool):
            sanitized = value
        elif isinstance(value, (int, float)):
            sanitized = bool(value)
            warnings.append(ValidationError(
                f"Numeric value {value} coerced to boolean",
                field_name, ValidationSeverity.WARNING
            ))
        elif isinstance(value, str):
            true_values = {"true", "1", "yes", "y", "on"}
            false_values = {"false", "0", "no", "n", "off"}
            lower_value = value.strip().lower()
            if lower_value in true_values:
                sanitized = True
                warnings.append(ValidationError(
                    f"String '{value}' coerced to boolean True",
                    field_name, ValidationSeverity.WARNING
                ))
            elif lower_value in false_values:
                sanitized = False
                warnings.append(ValidationError(
                    f"String '{value}' coerced to boolean False",
                    field_name, ValidationSeverity.WARNING
                ))
            else:
                errors.append(ValidationError(
                    f"Cannot coerce string '{value}' to boolean",
                    field_name, ValidationSeverity.ERROR
                ))
                sanitized = None
        else:
            errors.append(ValidationError(
                f"Cannot coerce type {type(value).__name__} to boolean",
                field_name, ValidationSeverity.ERROR
            ))
            sanitized = None

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_list(self, value: Any, field_name: str = "unknown",
                     item_validator: Optional[Callable] = None,
                     min_items: int = 0, max_items: Optional[int] = None,
                     unique_items: bool = False) -> ValidationResult:
        """
        Validate a list value with optional item-level validation.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            item_validator: Function to validate each item (takes item, returns ValidationResult)
            min_items: Minimum number of items
            max_items: Maximum number of items
            unique_items: Whether items must be unique
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "list", "timestamp": datetime.utcnow().isoformat()}

        # Type coercion
        if not isinstance(value, list):
            try:
                if isinstance(value, (tuple, set)):
                    value = list(value)
                    warnings.append(ValidationError(
                        f"Collection coerced to list from {type(value).__name__}",
                        field_name, ValidationSeverity.WARNING
                    ))
                else:
                    errors.append(ValidationError(
                        f"Cannot coerce type {type(value).__name__} to list",
                        field_name, ValidationSeverity.ERROR
                    ))
                    result.is_valid = False
                    result.errors = errors
                    result.warnings = warnings
                    result.telemetry = telemetry
                    self._log_validation(result, field_name)
                    return result
            except Exception as e:
                errors.append(ValidationError(
                    f"Error coercing to list: {str(e)}",
                    field_name, ValidationSeverity.ERROR
                ))
                result.is_valid = False
                result.errors = errors
                result.warnings = warnings
                result.telemetry = telemetry
                self._log_validation(result, field_name)
                return result

        # Length checks
        if len(value) < min_items:
            errors.append(ValidationError(
                f"List has {len(value)} items, minimum is {min_items}",
                field_name, ValidationSeverity.ERROR
            ))

        max_len = max_items or 1000  # Default max list size
        if len(value) > max_len:
            if self.strict_mode:
                errors.append(ValidationError(
                    f"List has {len(value)} items, maximum is {max_len}",
                    field_name, ValidationSeverity.ERROR
                ))
            else:
                value = value[:max_len]
                warnings.append(ValidationError(
                    f"List truncated from {len(value)} to {max_len} items",
                    field_name, ValidationSeverity.WARNING
                ))

        # Uniqueness check
        if unique_items:
            seen = set()
            duplicates = []
            for i, item in enumerate(value):
                try:
                    if item in seen:
                        duplicates.append(i)
                    else:
                        seen.add(item)
                except TypeError:
                    # Unhashable item, skip uniqueness check
                    warnings.append(ValidationError(
                        f"Item at index {i} is unhashable, skipping uniqueness check",
                        field_name, ValidationSeverity.WARNING
                    ))
            if duplicates:
                errors.append(ValidationError(
                    f"Duplicate items at indices: {duplicates}",
                    field_name, ValidationSeverity.ERROR
                ))

        # Item-level validation
        sanitized_list = []
        if item_validator:
            for i, item in enumerate(value):
                try:
                    item_result = item_validator(item)
                    if item_result.is_valid:
                        sanitized_list.append(item_result.sanitized_value)
                    else:
                        errors.extend(item_result.errors)
                        sanitized_list.append(item)  # Keep original for now
                except Exception as e:
                    errors.append(ValidationError(
                        f"Item validation failed at index {i}: {str(e)}",
                        f"{field_name}[{i}]", ValidationSeverity.ERROR
                    ))
                    sanitized_list.append(item)
        else:
            sanitized_list = value[:]

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized_list
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_dict(self, value: Any, field_name: str = "unknown",
                     schema: Optional[Dict[str, Any]] = None,
                     required_keys: Optional[List[str]] = None,
                     allow_extra_keys: bool = True) -> ValidationResult:
        """
        Validate a dictionary value with optional schema enforcement.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            schema: Dictionary mapping keys to validator functions
            required_keys: List of keys that must be present
            allow_extra_keys: Whether keys not in schema are allowed
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "dict", "timestamp": datetime.utcnow().isoformat()}

        # Type coercion
        if not isinstance(value, dict):
            try:
                if isinstance(value, str):
                    value = json.loads(value)
                    warnings.append(ValidationError(
                        "JSON string parsed to dictionary",
                        field_name, ValidationSeverity.WARNING
                    ))
                else:
                    errors.append(ValidationError(
                        f"Cannot coerce type {type(value).__name__} to dict",
                        field_name, ValidationSeverity.ERROR
                    ))
                    result.is_valid = False
                    result.errors = errors
                    result.warnings = warnings
                    result.telemetry = telemetry
                    self._log_validation(result, field_name)
                    return result
            except json.JSONDecodeError as e:
                errors.append(ValidationError(
                    f"Invalid JSON string: {str(e)}",
                    field_name, ValidationSeverity.ERROR
                ))
                result.is_valid = False
                result.errors = errors
                result.warnings = warnings
                result.telemetry = telemetry
                self._log_validation(result, field_name)
                return result

        # Required keys check
        required = required_keys or []
        for key in required:
            if key not in value:
                errors.append(ValidationError(
                    f"Required key '{key}' is missing",
                    f"{field_name}.{key}", ValidationSeverity.ERROR
                ))

        # Schema validation
        sanitized_dict = {}
        schema = schema or {}
        for key, validator in schema.items():
            if key in value:
                try:
                    field_result = validator(value[key])
                    if field_result.is_valid:
                        sanitized_dict[key] = field_result.sanitized_value
                    else:
                        errors.extend(field_result.errors)
                        warnings.extend(field_result.warnings)
                        sanitized_dict[key] = value[key]  # Keep original
                except Exception as e:
                    errors.append(ValidationError(
                        f"Validation failed for key '{key}': {str(e)}",
                        f"{field_name}.{key}", ValidationSeverity.ERROR
                    ))
                    sanitized_dict[key] = value[key]
            elif key not in required:
                # Optional key not present, skip
                pass

        # Extra keys handling
        if not allow_extra_keys:
            extra_keys = set(value.keys()) - set(schema.keys())
            if extra_keys:
                warnings.append(ValidationError(
                    f"Unexpected keys: {extra_keys}",
                    field_name, ValidationSeverity.WARNING
                ))

        # Merge sanitized with remaining keys
        for key, val in value.items():
            if key not in sanitized_dict:
                sanitized_dict[key] = val

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized_dict
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_uuid(self, value: Any, field_name: str = "unknown",
                     version: Optional[int] = None) -> ValidationResult:
        """
        Validate a UUID value.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            version: Expected UUID version (1-5), None for any
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "uuid", "timestamp": datetime.utcnow().isoformat()}

        # String coercion
        if isinstance(value, UUID):
            sanitized = str(value)
        elif isinstance(value, str):
            sanitized = value.strip()
        else:
            try:
                sanitized = str(value)
                warnings.append(ValidationError(
                    f"Value coerced to string from {type(value).__name__}",
                    field_name, ValidationSeverity.WARNING
                ))
            except Exception as e:
                errors.append(ValidationError(
                    f"Cannot convert to string: {str(e)}",
                    field_name, ValidationSeverity.ERROR
                ))
                result.is_valid = False
                result.errors = errors
                result.warnings = warnings
                result.telemetry = telemetry
                self._log_validation(result, field_name)
                return result

        # Validate UUID format
        try:
            uuid_obj = UUID(sanitized)
            if version is not None and uuid_obj.version != version:
                errors.append(ValidationError(
                    f"UUID version {uuid_obj.version} does not match expected version {version}",
                    field_name, ValidationSeverity.ERROR
                ))
        except ValueError as e:
            errors.append(ValidationError(
                f"Invalid UUID: {str(e)}",
                field_name, ValidationSeverity.ERROR
            ))

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_date(self, value: Any, field_name: str = "unknown",
                     min_date: Optional[Union[str, date]] = None,
                     max_date: Optional[Union[str, date]] = None) -> ValidationResult:
        """
        Validate a date value.
        
        Args:
            value: Input value to validate
            field_name: Name of the field for error reporting
            min_date: Minimum allowed date (string in YYYY-MM-DD or date object)
            max_date: Maximum allowed date (string in YYYY-MM-DD or date object)
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "date", "timestamp": datetime.utcnow().isoformat()}

        # Parse date
        if isinstance(value, date):
            parsed_date = value
        elif isinstance(value, str):
            try:
                parsed_date = datetime.strptime(value.strip(), "%Y-%m-%d").date()
            except ValueError:
                try:
                    parsed_date = datetime.fromisoformat(value.strip()).date()
                except (ValueError, TypeError):
                    errors.append(ValidationError(
                        f"Invalid date format: '{value}'",
                        field_name, ValidationSeverity.ERROR
                    ))
                    result.is_valid = False
                    result.errors = errors
                    result.warnings = warnings
                    result.telemetry = telemetry
                    self._log_validation(result, field_name)
                    return result
        else:
            errors.append(ValidationError(
                f"Cannot parse date from type {type(value).__name__}",
                field_name, ValidationSeverity.ERROR
            ))
            result.is_valid = False
            result.errors = errors
            result.warnings = warnings
            result.telemetry = telemetry
            self._log_validation(result, field_name)
            return result

        # Range checks
        if min_date:
            if isinstance(min_date, str):
                min_date = datetime.strptime(min_date, "%Y-%m-%d").date()
            if parsed_date < min_date:
                errors.append(ValidationError(
                    f"Date {parsed_date} is before minimum {min_date}",
                    field_name, ValidationSeverity.ERROR
                ))

        if max_date:
            if isinstance(max_date, str):
                max_date = datetime.strptime(max_date, "%Y-%m-%d").date()
            if parsed_date > max_date:
                errors.append(ValidationError(
                    f"Date {parsed_date} is after maximum {max_date}",
                    field_name, ValidationSeverity.ERROR
                ))

        sanitized = parsed_date.isoformat()

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = sanitized
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def validate_with_rules(self, value: Any, rules: List[ValidationRule],
                           field_name: str = "unknown") -> ValidationResult:
        """
        Validate a value against a list of custom rules.
        
        Args:
            value: Input value to validate
            rules: List of ValidationRule objects
            field_name: Name of the field for error reporting
            
        Returns:
            ValidationResult with sanitized value and diagnostics
        """
        result = ValidationResult()
        errors = []
        warnings = []
        telemetry = {"field": field_name, "type": "custom_rules", "timestamp": datetime.utcnow().isoformat()}

        for rule in rules:
            try:
                if not rule.validator(value):
                    error = ValidationError(
                        rule.error_message,
                        field_name,
                        rule.severity,
                        {"rule": rule.name, "params": rule.params}
                    )
                    if rule.severity in [ValidationSeverity.WARNING, ValidationSeverity.INFO]:
                        warnings.append(error)
                    else:
                        errors.append(error)
            except Exception as e:
                errors.append(ValidationError(
                    f"Rule '{rule.name}' execution failed: {str(e)}",
                    field_name, ValidationSeverity.CRITICAL
                ))

        result.is_valid = len(errors) == 0
        result.errors = errors
        result.warnings = warnings
        result.sanitized_value = value  # Custom rules don't modify value
        result.telemetry = telemetry
        
        self._log_validation(result, field_name)
        return result

    def get_validation_history(self, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Retrieve recent validation history for diagnostics.
        
        Args:
            limit: Maximum number of history entries to return
            
        Returns:
            List of validation telemetry dictionaries
        """
        return self._validation_history[-limit:]

    def clear_validation_history(self) -> None:
        """Clear the validation history buffer."""
        self._validation_history.clear()
        logger.info("Validation history cleared")

    def _sanitize_html(self, value: str) -> str:
        """
        Sanitize a string by escaping HTML special characters.
        
        Args:
            value: String to sanitize
            
        Returns:
            Sanitized string with HTML entities escaped
        """
        html_escape_table = {
            "&": "&amp;",
            '"': "&quot;",
            "'": "&#x27;",
            "<": "&lt;",
            ">": "&gt;",
        }
        return "".join(html_escape_table.get(c, c) for c in value)

    def _log_validation(self, result: ValidationResult, field_name: str) -> None:
        """
        Log validation result and store telemetry.
        
        Args:
            result: ValidationResult to log
            field_name: Name of the validated field
        """
        # Store telemetry
        telemetry_entry = {
            "field": field_name,
            "is_valid": result.is_valid,
            "error_count": len(result.errors),
            "warning_count": len(result.warnings),
            "timestamp": datetime.utcnow().isoformat()
        }
        self._validation_history.append(telemetry_entry)

        # Log based on severity
        if result.errors:
            for error in result.errors:
                if error.severity == ValidationSeverity.CRITICAL:
                    logger.critical(f"Validation critical: {error}")
                elif error.severity == ValidationSeverity.ERROR:
                    logger.error(f"Validation error: {error}")
                else:
                    logger.warning(f"Validation warning: {error}")
        elif result.warnings:
            logger.info(f"Validation warnings for '{field_name}': {len(result.warnings)}")
        else:
            logger.debug(f"Validation passed for '{field_name}'")


# Factory function for quick validation
def create_validator(config: Optional[Dict[str, Any]] = None) -> InputValidationSkill:
    """
    Create and return an InputValidationSkill instance.
    
    Args:
        config: Optional configuration dictionary
        
    Returns:
        Configured InputValidationSkill instance
    """
    return InputValidationSkill(config)


# Example usage and test cases
if __name__ == "__main__":
    # Configure logging
    logging.basicConfig(level=logging.INFO)
    
    # Create validator
    validator = create_validator({"strict_mode": True})
    
    # Test string validation
    email_result = validator.validate_string(
        "user@example.com", 
        field_name="email",
        pattern="email"
    )
    print(f"Email valid: {email_result.is_valid}, sanitized: {email_result.sanitized_value}")
    
    # Test numeric validation
    age_result = validator.validate_numeric(
        "25",
        field_name="age",
        min_value=0,
        max_value=150
    )
    print(f"Age valid: {age_result.is_valid}, sanitized: {age_result.sanitized_value}")
    
    # Test boolean validation
    flag_result = validator.validate_boolean("yes", field_name="active")
    print(f"Flag valid: {flag_result.is_valid}, sanitized: {flag_result.sanitized_value}")
    
    # Test list validation
    items_result = validator.validate_list(
        [1, 2, 3, 2],
        field_name="items",
        unique_items=True
    )
    print(f"Items valid: {items_result.is_valid}, errors: {[str(e) for e in items_result.errors]}")
    
    # Test UUID validation
    uuid_result = validator.validate_uuid(
        "550e8400-e29b-41d4-a716-446655440000",
        field_name="user_id"
    )
    print(f"UUID valid: {uuid_result.is_valid}")
    
    # Test date validation
    date_result = validator.validate_date(
        "2025-04-08",
        field_name="event_date",
        min_date="2025-01-01",
        max_date="2025-12-31"
    )
    print(f"Date valid: {date_result.is_valid}, sanitized: {date_result.sanitized_value}")
    
    # Test validation history
    history = validator.get_validation_history()
    print(f"Validation history entries: {len(history)}")
    
    print("\nAll tests passed!")