# Generated by Flow (DevOps Engineer)
import docker
import time
from typing import Dict, List
from .interface import ContainerRuntime, ContainerResult
from ..exceptions import ContainerExecutionError, ResourceConstraintError

class DockerRuntime(ContainerRuntime):
    def __init__(self, socket_path: str = "/var/run/docker.sock"):
        try:
            self.client = docker.DockerClient(base_url=f"unix://{socket_path}")
        except Exception as e:
            raise ContainerExecutionError(f"Failed to connect to Docker socket: {e}")

    def check_health(self) -> bool:
        try:
            self.client.ping()
            return True
        except:
            return False

    def run_command(
        self, 
        image: str, 
        command: List[str], 
        env: Dict[str, str] = None, 
        volumes: Dict[str, str] = None, 
        cpu_limit: float = 1.0, 
        mem_limit: str = "512m", 
        timeout: int = 300
    ) -> ContainerResult:
        start_time = time.perf_counter()
        try:
            # Convert mem_limit to bytes for Docker API
            mem_bytes = self._parse_mem_limit(mem_limit)
            
            container = self.client.containers.run(
                image=image,
                command=command,
                environment=env,
                volumes=volumes,
                mem_limit=mem_bytes,
                nano_cpus=int(cpu_limit * 1e9),
                detach=True,
                remove=True
            )

            try:
                result = container.wait(timeout=timeout)
                logs = container.logs().decode('utf-8')
                exit_code = result['StatusCode']
            except Exception as e:
                container.kill()
                raise ContainerExecutionError(f"Container timed out or failed: {e}")

            return ContainerResult(
                exit_code=exit_code,
                stdout=logs, # Docker merges stdout/stderr in logs() unless split
                stderr="", 
                duration_ms=(time.perf_counter() - start_time) * 1000,
                runtime_used="docker"
            )
        except docker.errors.ImageNotFound:
            raise ContainerExecutionError(f"Image {image} not found.")
        except docker.errors.APIError as e:
            raise ResourceConstraintError(f"Docker API Error: {e}")

    def _parse_mem_limit(self, limit: str) -> int:
        units = {"k": 10**3, "m": 10**6, "g": 10**9}
        unit = limit[-1].lower()
        if unit in units:
            return int(limit[:-1]) * units[unit]
        return int(limit)