# Generated by Flow (DevOps Engineer)
import shutil
from typing import Type
from .interface import ContainerRuntime
from .docker_adapter import DockerRuntime
from .podman_adapter import PodmanRuntime
from ..exceptions import RuntimeNotFoundError

class RuntimeFactory:
    """
    Orchestrates the selection of the container runtime based on 
    system availability and priority.
    """
    
    PRIORITY = [DockerRuntime, PodmanRuntime]

    @staticmethod
    def get_runtime() -> ContainerRuntime:
        # 1. Check for Docker (Priority 1)
        if shutil.which("docker"):
            try:
                dr = DockerRuntime()
                if dr.check_health():
                    return dr
            except:
                pass

        # 2. Check for Podman (Priority 2)
        if shutil.which("podman"):
            try:
                pr = PodmanRuntime()
                if pr.check_health():
                    return pr
            except:
                pass

        raise RuntimeNotFoundError(
            "No compatible container runtime (Docker/Podman) found or healthy on this host."
        )