# Generated by Verify (QA Engineer)
```python
import pytest
from pydantic import ValidationError
from swarm_v2.core.global_memory import MemoryEntry, MemoryType

class TestGlobalMemorySchema:
    """
    Test suite for the Global Memory Schema components in swarm_v2.core.global_memory.
    Validates Pydantic model enforcement and Enum integrity.
    """

    @pytest.mark.parametrize("m_type, expected_value", [
        (MemoryType.KNOWLEDGE, "knowledge"),
        (MemoryType.SYSTEM_LOG, "system_log"),
        (MemoryType.USER_PREFERENCE, "user_preference"),
        (MemoryType.INTERACTION_HISTORY, "interaction_history"),
    ])
    def test_memory_type_enum_values(self, m_type, expected_value):
        """Verify that MemoryType enum values match the expected string representations."""
        assert m_type == expected_value

    def test_memory_entry_valid_instantiation(self):
        """Test successful creation of a MemoryEntry with valid data."""
        data = {
            "entry_id": "uuid-12345",
            "content": "Sample knowledge content.",
            "author": "system_agent",
            "author_role": "coordinator",
            "memory_type": MemoryType.KNOWLEDGE
        }
        entry = MemoryEntry(**data)
        assert entry.entry_id == "uuid-12345"
        assert entry.content == "Sample knowledge content."
        assert entry.author == "system_agent"
        assert entry.author_role == "coordinator"
        assert entry.memory_type == MemoryType.KNOWLEDGE

    @pytest.mark.parametrize("missing_field", [
        "entry_id", 
        "content", 
        "author", 
        "author_role", 
        "memory_type"
    ])
    def test_memory_entry_missing_fields(self, missing_field):
        """Ensure that missing required fields trigger a Pydantic ValidationError."""
        data = {
            "entry_id": "uuid-12345",
            "content": "Sample content",
            "author": "agent",
            "author_role": "worker",
            "memory_type": MemoryType.KNOWLEDGE
        }
        del data[missing_field]
        with pytest.raises(ValidationError):
            MemoryEntry(**data)

    def test_memory_entry_extra_fields_forbidden(self):
        """Verify that the 'extra=forbid' configuration prevents injection of unknown fields."""
        data = {
            "entry_id": "uuid-12345",
            "content": "Sample content",
            "author": "agent",
            "author_role": "worker",
            "memory_type": MemoryType.KNOWLEDGE,
            "unexpected_field": "malicious_injection"
        }
        with pytest.raises(ValidationError) as excinfo:
            MemoryEntry(**data)
        assert "extra fields not permitted" in str(excinfo.value)

    @pytest.mark.parametrize("invalid_type", [
        123, 
        ["list_type"], 
        None
    ])
    def test_memory_entry_invalid_types(self, invalid_type):
        """Ensure that incorrect data types for fields trigger a ValidationError."""
        data = {
            "entry_id": "uuid-12345",
            "content": "Sample content",
            "author": "agent",
            "author_role": "worker",
            "memory_type": invalid_type
        }
        with pytest.raises(ValidationError):
            MemoryEntry(**data)

    def test_memory_entry_immutability(self):
        """Verify that the 'frozen=True' configuration prevents modification of the instance."""
        data = {
            "entry_id": "uuid-12345",
            "content": "Sample content",
            "author": "agent",
            "author_role": "worker",
            "memory_type": MemoryType.KNOWLEDGE
        }
        entry = MemoryEntry(**data)
        with pytest.raises(AttributeError):
            # Attempting to modify a field on a frozen Pydantic model
            entry.content = "New content"

```