# Generated by Devo (Lead Developer)
# async_telemetry_gateway/app/config.py
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import Field
import logging

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    APP_NAME: str = "AsyncHighFrequencyTelemetryGateway"
    APP_VERSION: str = "1.0.0"
    DEBUG_MODE: bool = Field(False, description="Enable debug logging and features.")

    # Server Settings
    HOST: str = "0.0.0.0"
    PORT: int = 8000
    WORKERS: int = Field(1, description="Number of Uvicorn workers.")

    # Telemetry Processing Settings
    TELEMETRY_QUEUE_MAX_SIZE: int = Field(100000, description="Maximum size of the in-memory telemetry queue.")
    TELEMETRY_PROCESS_BATCH_SIZE: int = Field(1000, description="Number of telemetry items to process in a single batch.")
    TELEMETRY_PROCESS_INTERVAL_SEC: float = Field(0.01, description="Interval (seconds) between telemetry processing cycles.")

    # Rate Limiting Settings (per IP)
    RATE_LIMIT_ENABLED: bool = Field(True, description="Enable API rate limiting.")
    RATE_LIMIT_REQUESTS_PER_MINUTE: int = Field(500000, description="Max requests per minute per IP.")

    # Circuit Breaker Settings
    CIRCUIT_BREAKER_ENABLED: bool = Field(True, description="Enable circuit breaker for downstream calls.")
    CIRCUIT_BREAKER_FAIL_THRESHOLD: int = Field(5, description="Number of failures before opening the circuit.")
    CIRCUIT_BREAKER_RESET_TIMEOUT_SEC: int = Field(30, description="Time (seconds) before attempting to close the circuit.")
    CIRCUIT_BREAKER_EXCLUDE_EXCEPTIONS: list[type[Exception]] = Field([], description="Exceptions that do not count as failures.")

    # Redis for Rate Limiter
    REDIS_HOST: str = "localhost"
    REDIS_PORT: int = 6379
    REDIS_DB: int = 0

    # Logging Settings
    LOG_LEVEL: str = Field("INFO", description="Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL).")

    # Anomaly Detection Hook (Placeholder for integration with Nexus/Logic)
    ANOMALY_DETECTION_ENDPOINT: str | None = Field(None, description="URL for the external anomaly detection service.")
    ANOMALY_DETECTION_TIMEOUT_SEC: float = Field(0.5, description="Timeout for anomaly detection requests.")

    def configure_logging(self):
        logging.basicConfig(level=self.LOG_LEVEL.upper(),
                            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        if self.DEBUG_MODE:
            logging.getLogger().setLevel(logging.DEBUG)
        else:
            logging.getLogger().setLevel(logging.INFO)

settings = Settings()
settings.configure_logging()