# Generated by Devo (Lead Developer)
# async_telemetry_gateway/app/models.py
from pydantic import BaseModel, Field, conlist
from typing import Literal, Union, List, Dict, Any
from datetime import datetime

class BaseTelemetry(BaseModel):
    """Base model for all telemetry data."""
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC timestamp of the telemetry event.")
    source_id: str = Field(..., min_length=1, max_length=64, description="Unique identifier of the telemetry source (e.g., robot ID, financial instrument ID).")
    sequence_num: int = Field(..., ge=0, description="Monotonically increasing sequence number for the source.")
    data_type: str = Field(..., min_length=1, max_length=32, description="Type of telemetry data (e.g., 'robot_vibration', 'financial_quote').")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Optional metadata associated with the telemetry.")

class RobotVibrationTelemetry(BaseTelemetry):
    """Telemetry for robot vibration sensors."""
    data_type: Literal["robot_vibration"] = "robot_vibration"
    vibration_x: float = Field(..., description="Vibration amplitude on X-axis.")
    vibration_y: float = Field(..., description="Vibration amplitude on Y-axis.")
    vibration_z: float = Field(..., description="Vibration amplitude on Z-axis.")
    frequency_hz: float = Field(..., gt=0, description="Dominant vibration frequency in Hz.")
    temperature_c: float = Field(..., description="Sensor temperature in Celsius.")

class RobotMotorTelemetry(BaseTelemetry):
    """Telemetry for robot motor status."""
    data_type: Literal["robot_motor"] = "robot_motor"
    motor_id: str = Field(..., description="Identifier for the specific motor.")
    rpm: int = Field(..., ge=0, description="Revolutions per minute.")
    current_a: float = Field(..., ge=0, description="Motor current in Amperes.")
    voltage_v: float = Field(..., ge=0, description="Motor voltage in Volts.")
    power_w: float = Field(..., ge=0, description="Motor power in Watts.")
    temperature_c: float = Field(..., description="Motor temperature in Celsius.")
    status: Literal["running", "idle", "error", "warning"] = Field(..., description="Motor operational status.")

class FinancialQuoteTelemetry(BaseTelemetry):
    """Telemetry for financial instrument quotes."""
    data_type: Literal["financial_quote"] = "financial_quote"
    symbol: str = Field(..., min_length=1, max_length=16, description="Trading symbol (e.g., 'AAPL', 'EUR/USD').")
    bid_price: float = Field(..., gt=0, description="Best bid price.")
    ask_price: float = Field(..., gt=0, description="Best ask price.")
    last_price: float = Field(..., gt=0, description="Last traded price.")
    volume: int = Field(..., ge=0, description="Cumulative volume for the current period.")
    exchange: str = Field(..., min_length=1, max_length=16, description="Exchange where the quote originated.")

class VisualGestureTelemetry(BaseTelemetry):
    """Telemetry for visual gesture detection (e.g., emergency stop)."""
    data_type: Literal["visual_gesture"] = "visual_gesture"
    gesture_type: Literal["PALM_STOP", "WAVE_START", "POINT_TO"] = Field(..., description="Type of detected gesture.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the detection.")
    bounding_box: List[float] = Field(..., min_length=4, max_length=4, description="[x_min, y_min, x_max, y_max] normalized coordinates.")
    camera_id: str = Field(..., description="Identifier of the camera that detected the gesture.")

# Union type for all supported telemetry models
AnyTelemetry = Union[
    RobotVibrationTelemetry,
    RobotMotorTelemetry,
    FinancialQuoteTelemetry,
    VisualGestureTelemetry
]

class TelemetryBatch(BaseModel):
    """A batch of mixed telemetry data."""
    batch_id: str = Field(..., description="Unique identifier for this telemetry batch.")
    telemetry_items: conlist(AnyTelemetry, min_length=1, max_length=10000) = Field(..., description="List of telemetry items in the batch.")