# Generated by Archi (Architect)
```python
from typing import Dict, Any, Optional
from dataclasses import dataclass
from telemetry_client import TelemetryClient # Internal Swarm OS Library

@dataclass
class MonitoringRequest:
    target_resource: str
    metric_scope: str
    time_window: str
    thresholds: Optional[Dict[str, float]] = None
    granularity: str = "AGGREGATED"

class MonitoringSkill:
    def __init__(self, config: Dict[str, Any]):
        self.client = TelemetryClient(config)
        self.analyzer = HeuristicEngine()

    async def execute(self, params: Dict[str, Any]) -> Dict[str, Any]:
        try:
            # 1. Parse and Validate
            request = MonitoringRequest(**params)
            
            # 2. Data Acquisition
            raw_data = await self.client.fetch_metrics(
                resource=request.target_resource,
                scope=request.metric_scope,
                window=request.time_window
            )
            
            # 3. Analysis
            analysis = self.analyzer.process(
                data=raw_data, 
                thresholds=request.thresholds,
                granularity=request.granularity
            )
            
            return {
                "status": "SUCCESS",
                "payload": analysis
            }
            
        except ResourceNotFoundError as e:
            return {"status": "ERROR", "code": "ERR_RES_404", "message": str(e)}
        except Exception as e:
            return {"status": "ERROR", "code": "ERR_INTERNAL", "message": "Critical failure in telemetry pipeline."}

class HeuristicEngine:
    def process(self, data, thresholds, granularity):
        # Implementation of Z-score and threshold logic
        # Returns structured JSON as per specification
        pass
```