# Generated by Devo (Lead Developer)
"""
research_pipeline.py
Swarm OS v12 - Advanced Neural Architecture
Production-grade pipeline for ingesting, analyzing, and reporting on latest AI research papers.

Author: Devo (Lead Developer)
Date: 2026-07-09
Version: 1.0.0

Dependencies:
- aiohttp>=3.9.0
- asyncio>=3.4.3
- pydantic>=2.5.0
- tenacity>=8.2.0
- loguru>=0.7.0
- cachetools>=5.3.0
"""

import asyncio
import hashlib
import json
import os
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field, asdict

import aiohttp
from pydantic import BaseModel, Field, ValidationError
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
from loguru import logger
from cachetools import TTLCache

# -------------------- Configuration --------------------

class ResearchPipelineConfig(BaseModel):
    """Central configuration for the research pipeline."""
    arxiv_api_base: str = Field(default="http://export.arxiv.org/api/query", description="arXiv API endpoint")
    semantic_scholar_api: str = Field(default="https://api.semanticscholar.org/graph/v1/paper", description="Semantic Scholar API")
    max_concurrent_requests: int = Field(default=10, ge=1, le=50, description="Max concurrent API calls")
    cache_ttl_seconds: int = Field(default=3600, ge=60, description="Cache time-to-live")
    retry_attempts: int = Field(default=3, ge=1, le=10, description="Retry attempts for failed requests")
    output_dir: str = Field(default="./reports", description="Directory for generated reports")
    log_level: str = Field(default="INFO", description="Logging level")

    class Config:
        frozen = True  # Immutable configuration

# -------------------- Data Models --------------------

class PaperMetadata(BaseModel):
    """Structured metadata for a research paper."""
    arxiv_id: str = Field(..., description="arXiv identifier")
    title: str = Field(..., description="Paper title")
    authors: List[str] = Field(default_factory=list, description="List of authors")
    abstract: str = Field(default="", description="Paper abstract")
    categories: List[str] = Field(default_factory=list, description="Subject categories")
    published: datetime = Field(default_factory=datetime.utcnow, description="Publication date")
    updated: Optional[datetime] = Field(default=None, description="Last update date")
    pdf_url: Optional[str] = Field(default=None, description="Link to PDF")
    citation_count: int = Field(default=0, ge=0, description="Number of citations")
    source: str = Field(default="arxiv", description="Source of the paper")

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }

class AnalysisResult(BaseModel):
    """Output of the paper analysis engine."""
    paper: PaperMetadata
    summary: str = Field(default="", description="Generated summary")
    key_methods: List[str] = Field(default_factory=list, description="Key methodologies identified")
    key_results: List[str] = Field(default_factory=list, description="Key results/findings")
    limitations: List[str] = Field(default_factory=list, description="Identified limitations")
    novelty_score: float = Field(default=0.0, ge=0.0, le=1.0, description="Novelty assessment")
    relevance_score: float = Field(default=0.0, ge=0.0, le=1.0, description="Relevance to query")
    analyzed_at: datetime = Field(default_factory=datetime.utcnow, description="Analysis timestamp")

# -------------------- Ingestion Layer --------------------

class ArxivIngestionEngine:
    """Handles fetching paper metadata from arXiv API with resilience patterns."""

    def __init__(self, config: ResearchPipelineConfig, session: aiohttp.ClientSession):
        self.config = config
        self.session = session
        self.cache: TTLCache = TTLCache(maxsize=500, ttl=config.cache_ttl_seconds)
        logger.info(f"ArxivIngestionEngine initialized with cache TTL={config.cache_ttl_seconds}s")

    def _generate_cache_key(self, query: str) -> str:
        """Generate deterministic cache key from query."""
        return hashlib.sha256(query.encode('utf-8')).hexdigest()

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
        retry=retry_if_exception_type((aiohttp.ClientError, asyncio.TimeoutError)),
        reraise=True
    )
    async def fetch_papers(self, query: str, max_results: int = 50) -> List[PaperMetadata]:
        """
        Fetch papers from arXiv API with caching and retry logic.
        
        Args:
            query: Search query string (e.g., 'cat:cs.AI+AND+abs:transformer')
            max_results: Maximum number of results to return (max 100)
        
        Returns:
            List of PaperMetadata objects
        """
        cache_key = self._generate_cache_key(f"{query}:{max_results}")
        
        if cache_key in self.cache:
            logger.debug(f"Cache hit for query: {query}")
            return self.cache[cache_key]

        params = {
            'search_query': query,
            'start': 0,
            'max_results': min(max_results, 100),
            'sortBy': 'submittedDate',
            'sortOrder': 'descending'
        }

        try:
            async with self.session.get(
                self.config.arxiv_api_base,
                params=params,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as response:
                response.raise_for_status()
                raw_xml = await response.text()
                papers = self._parse_arxiv_response(raw_xml)
                self.cache[cache_key] = papers
                logger.info(f"Fetched {len(papers)} papers from arXiv for query: {query}")
                return papers
        except aiohttp.ClientError as e:
            logger.error(f"arXiv API request failed: {e}")
            raise
        except Exception as e:
            logger.exception(f"Unexpected error during arXiv fetch: {e}")
            raise

    def _parse_arxiv_response(self, raw_xml: str) -> List[PaperMetadata]:
        """Parse arXiv Atom XML response into PaperMetadata objects."""
        import xml.etree.ElementTree as ET
        
        papers = []
        try:
            root = ET.fromstring(raw_xml)
            ns = {'atom': 'http://www.w3.org/2005/Atom', 'arxiv': 'http://arxiv.org/schemas/atom'}
            
            for entry in root.findall('atom:entry', ns):
                try:
                    paper = PaperMetadata(
                        arxiv_id=entry.find('atom:id', ns).text.split('/')[-1] if entry.find('atom:id', ns) is not None else '',
                        title=entry.find('atom:title', ns).text.strip().replace('\n', ' ') if entry.find('atom:title', ns) is not None else '',
                        authors=[author.find('atom:name', ns).text for author in entry.findall('atom:author', ns)],
                        abstract=entry.find('atom:summary', ns).text.strip().replace('\n', ' ') if entry.find('atom:summary', ns) is not None else '',
                        categories=[cat.get('term') for cat in entry.findall('atom:category', ns)],
                        published=datetime.strptime(entry.find('atom:published', ns).text, '%Y-%m-%dT%H:%M:%SZ') if entry.find('atom:published', ns) is not None else datetime.utcnow(),
                        updated=datetime.strptime(entry.find('atom:updated', ns).text, '%Y-%m-%dT%H:%M:%SZ') if entry.find('atom:updated', ns) is not None else None,
                        pdf_url=entry.find('atom:link[@title="pdf"]', ns).get('href') if entry.find('atom:link[@title="pdf"]', ns) is not None else None,
                        source='arxiv'
                    )
                    papers.append(paper)
                except (AttributeError, ValueError, KeyError) as e:
                    logger.warning(f"Skipping malformed entry: {e}")
                    continue
        except ET.ParseError as e:
            logger.error(f"Failed to parse arXiv XML response: {e}")
            raise
        
        return papers

# -------------------- Analysis Engine --------------------

class PaperAnalyzer:
    """
    Multi-stage analysis engine for research papers.
    Uses NLP heuristics and LLM-based summarization for deep insight extraction.
    """

    def __init__(self, config: ResearchPipelineConfig):
        self.config = config
        self._load_nlp_models()
        logger.info("PaperAnalyzer initialized with NLP models")

    def _load_nlp_models(self):
        """Lazy-load NLP components (spaCy, transformers) for memory efficiency."""
        try:
            import spacy
            self.nlp = spacy.load("en_core_web_sm")
            logger.debug("spaCy model loaded successfully")
        except OSError:
            logger.warning("spaCy model not found. Install with: python -m spacy download en_core_web_sm")
            self.nlp = None
        
        try:
            from transformers import pipeline
            self.summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
            logger.debug("HuggingFace summarizer loaded")
        except ImportError:
            logger.warning("transformers not installed. Summarization will use heuristic fallback.")
            self.summarizer = None

    async def analyze_paper(self, paper: PaperMetadata, query_context: str = "") -> AnalysisResult:
        """
        Perform comprehensive analysis on a single paper.
        
        Args:
            paper: PaperMetadata object to analyze
            query_context: Optional context to guide relevance scoring
        
        Returns:
            AnalysisResult with extracted insights
        """
        # Extract key methods using NLP
        key_methods = self._extract_methods(paper.abstract)
        
        # Generate summary
        summary = await self._generate_summary(paper.abstract)
        
        # Identify limitations
        limitations = self._extract_limitations(paper.abstract)
        
        # Score novelty and relevance
        novelty_score = self._compute_novelty(paper, key_methods)
        relevance_score = self._compute_relevance(paper, query_context)
        
        # Extract key results (heuristic: sentences with quantitative claims)
        key_results = self._extract_key_results(paper.abstract)
        
        return AnalysisResult(
            paper=paper,
            summary=summary,
            key_methods=key_methods,
            key_results=key_results,
            limitations=limitations,
            novelty_score=novelty_score,
            relevance_score=relevance_score
        )

    def _extract_methods(self, text: str) -> List[str]:
        """Extract methodological keywords using NLP and pattern matching."""
        if not text:
            return []
        
        methods = []
        # Pattern-based extraction for common ML methods
        method_patterns = [
            r'\b(transformer|attention|convolutional|recurrent|graph neural|diffusion|GAN|VAE|RL|reinforcement learning|transfer learning|few-shot|zero-shot|self-supervised|contrastive|knowledge distillation|pruning|quantization)\b',
            r'\b(LLaMA|GPT|BERT|T5|ViT|CLIP|DALL-E|Stable Diffusion|ResNet|EfficientNet|YOLO|NeRF)\b'
        ]
        
        import re
        for pattern in method_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            methods.extend([m.lower() for m in matches if m.lower() not in methods])
        
        # NLP-based extraction if spaCy is available
        if self.nlp:
            doc = self.nlp(text)
            for chunk in doc.noun_chunks:
                if any(term in chunk.text.lower() for term in ['method', 'approach', 'architecture', 'framework', 'algorithm']):
                    methods.append(chunk.text.strip())
        
        return list(set(methods))[:10]  # Deduplicate and limit

    async def _generate_summary(self, abstract: str) -> str:
        """Generate concise summary using LLM or heuristic fallback."""
        if not abstract:
            return ""
        
        if self.summarizer:
            try:
                # Truncate to model's max length
                input_text = abstract[:1024]
                summary = self.summarizer(input_text, max_length=150, min_length=30, do_sample=False)
                return summary[0]['summary_text']
            except Exception as e:
                logger.warning(f"LLM summarization failed: {e}. Falling back to extractive.")
        
        # Heuristic fallback: extract first 2-3 sentences
        sentences = abstract.split('. ')
        return '. '.join(sentences[:3]) + '.'

    def _extract_limitations(self, text: str) -> List[str]:
        """Identify limitation statements using pattern matching."""
        if not text:
            return []
        
        import re
        limitation_patterns = [
            r'(limitation|limitation[s]?|drawback|shortcoming|weakness|constraint|trade-off|bottleneck|challenge)',
            r'(limited to|does not|fails to|cannot|struggles with|not suitable for)'
        ]
        
        limitations = []
        sentences = text.split('. ')
        for sentence in sentences:
            for pattern in limitation_patterns:
                if re.search(pattern, sentence, re.IGNORECASE):
                    limitations.append(sentence.strip())
                    break
        
        return limitations[:5]

    def _compute_novelty(self, paper: PaperMetadata, methods: List[str]) -> float:
        """
        Compute novelty score based on:
        - Recency (newer papers score higher)
        - Method diversity (more novel methods = higher score)
        - Citation count (inverse: fewer citations = potentially more novel)
        """
        # Recency factor: papers from last 3 months get boost
        days_old = (datetime.utcnow() - paper.published).days
        recency_score = max(0.0, 1.0 - (days_old / 365.0))
        
        # Method novelty: penalize common methods, reward rare ones
        common_methods = {'transformer', 'attention', 'cnn', 'rnn', 'lstm', 'gru'}
        method_novelty = sum(1.0 for m in methods if m not in common_methods) / max(len(methods), 1)
        
        # Citation novelty: fewer citations for recent papers = potentially novel
        citation_penalty = min(1.0, paper.citation_count / 100.0)
        
        # Weighted combination
        novelty = (0.4 * recency_score) + (0.4 * method_novelty) + (0.2 * (1.0 - citation_penalty))
        return round(min(1.0, max(0.0, novelty)), 4)

    def _compute_relevance(self, paper: PaperMetadata, query_context: str) -> float:
        """Compute relevance score based on keyword overlap with query context."""
        if not query_context:
            return 0.5  # Neutral if no context
        
        query_terms = set(query_context.lower().split())
        paper_text = f"{paper.title} {paper.abstract}".lower()
        
        # TF-style overlap
        overlap = sum(1 for term in query_terms if term in paper_text)
        relevance = overlap / max(len(query_terms), 1)
        
        return round(min(1.0, relevance), 4)

    def _extract_key_results(self, text: str) -> List[str]:
        """Extract sentences containing quantitative results or performance claims."""
        if not text:
            return []
        
        import re
        result_patterns = [
            r'\b(accuracy|precision|recall|F1|BLEU|ROUGE|perplexity|loss|error rate|performance|improvement|state-of-the-art|SOTA)\b',
            r'\b\d+\.?\d*%\b',  # Percentage values
            r'\b(achieve|outperform|improve|reduce|increase|demonstrate|show|report)\b'
        ]
        
        results = []
        sentences = text.split('. ')
        for sentence in sentences:
            for pattern in result_patterns:
                if re.search(pattern, sentence, re.IGNORECASE):
                    results.append(sentence.strip())
                    break
        
        return results[:5]

# -------------------- Orchestrator --------------------

class ResearchPipelineOrchestrator:
    """
    Top-level orchestrator that coordinates ingestion, analysis, and reporting.
    Implements the Saga pattern for distributed transaction management.
    """

    def __init__(self, config: Optional[ResearchPipelineConfig] = None):
        self.config = config or ResearchPipelineConfig()
        self.session: Optional[aiohttp.ClientSession] = None
        self.ingestion_engine: Optional[ArxivIngestionEngine] = None
        self.analyzer: Optional[PaperAnalyzer] = None
        self._setup_logging()
        logger.info("ResearchPipelineOrchestrator initialized")

    def _setup_logging(self):
        """Configure structured logging with Loguru."""
        logger.remove()
        logger.add(
            sink=os.path.join(self.config.output_dir, 'pipeline.log') if os.path.exists(self.config.output_dir) else None,
            level=self.config.log_level,
            format="{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}",
            rotation="10 MB",
            retention="30 days"
        )
        logger.add(
            sink=lambda msg: print(msg, end=''),
            level=self.config.log_level,
            format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{message}</cyan>"
        )

    async def __aenter__(self):
        """Async context manager entry - initializes HTTP session."""
        self.session = aiohttp.ClientSession(
            headers={'User-Agent': 'SwarmOS-ResearchPipeline/1.0'},
            connector=aiohttp.TCPConnector(limit=self.config.max_concurrent_requests)
        )
        self.ingestion_engine = ArxivIngestionEngine(self.config, self.session)
        self.analyzer = PaperAnalyzer(self.config)
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit - cleans up resources."""
        if self.session:
            await self.session.close()
        logger.info("Pipeline resources cleaned up")

    async def execute_pipeline(
        self,
        query: str,
        max_papers: int = 20,
        query_context: str = "",
        output_file: Optional[str] = None
    ) -> List[AnalysisResult]:
        """
        Execute the full research pipeline: fetch -> analyze -> report.
        
        Args:
            query: arXiv search query
            max_papers: Maximum papers to process
            query_context: Context for relevance scoring
            output_file: Optional path to save results as JSON
        
        Returns:
            List of AnalysisResult objects
        """
        logger.info(f"Starting pipeline execution for query: {query}")
        
        # Phase 1: Ingestion
        papers = await self.ingestion_engine.fetch_papers(query, max_results=max_papers)
        if not papers:
            logger.warning("No papers found for query")
            return []
        
        logger.info(f"Ingested {len(papers)} papers")
        
        # Phase 2: Analysis (with concurrency control)
        semaphore = asyncio.Semaphore(self.config.max_concurrent_requests)
        
        async def analyze_with_throttle(paper: PaperMetadata) -> AnalysisResult:
            async with semaphore:
                return await self.analyzer.analyze_paper(paper, query_context)
        
        tasks = [analyze_with_throttle(paper) for paper in papers]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Filter out failed analyses
        valid_results: List[AnalysisResult] = []
        for result in results:
            if isinstance(result, Exception):
                logger.error(f"Analysis failed: {result}")
            else:
                valid_results.append(result)
        
        logger.info(f"Successfully analyzed {len(valid_results)}/{len(papers)} papers")
        
        # Phase 3: Output
        if output_file:
            os.makedirs(os.path.dirname(output_file) or '.', exist_ok=True)
            with open(output_file, 'w') as f:
                json.dump(
                    [result.model_dump() for result in valid_results],
                    f,
                    indent=2,
                    default=str
                )
            logger.info(f"Results saved to {output_file}")
        
        return valid_results

# -------------------- Entry Point --------------------

async def main():
    """Example usage of the research pipeline."""
    config = ResearchPipelineConfig(
        max_concurrent_requests=5,
        cache_ttl_seconds=1800,
        output_dir="./research_output"
    )
    
    os.makedirs(config.output_dir, exist_ok=True)
    
    async with ResearchPipelineOrchestrator(config) as pipeline:
        results = await pipeline.execute_pipeline(
            query="cat:cs.AI+AND+abs:transformer+AND+submittedDate:[202401010000+TO+202412312359]",
            max_papers=10,
            query_context="latest transformer architectures 2024",
            output_file="./research_output/analysis_results.json"
        )
        
        # Print summary
        for result in results:
            logger.info(f"Paper: {result.paper.title[:50]}... | Novelty: {result.novelty_score:.2f} | Relevance: {result.relevance_score:.2f}")

if __name__ == "__main__":
    asyncio.run(main())