# Generated by Verify (QA Engineer)
import pytest
import subprocess
import os
from unittest.mock import MagicMock, patch, call
from git_skill_engine import GitSkillEngine, GitAction

# --- Fixtures ---

@pytest.fixture
def engine():
    """Provides a GitSkillEngine instance with a mocked logger."""
    return GitSkillEngine(logger=MagicMock())

@pytest.fixture
def mock_repo_path(tmp_path):
    """Creates a temporary directory simulating a git repository."""
    repo = tmp_path / "test_repo"
    repo.mkdir()
    (repo / ".git").mkdir()
    return str(repo)

# --- Unit Tests: Internal Methods ---

def test_run_command_success(engine, mock_repo_path):
    """Tests successful execution of a git command."""
    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(
            returncode=0, stdout="success_out", stderr=""
        )
        code, out, err = engine._run_command(mock_repo_path, ["status"])
        
        assert code == 0
        assert out == "success_out"
        assert err == ""
        mock_run.assert_called_once_with(
            ["git", "-C", mock_repo_path, "status"],
            capture_output=True, text=True, timeout=30, check=False
        )

def test_run_command_timeout(engine, mock_repo_path):
    """Tests handling of subprocess timeout."""
    with patch("subprocess.run", side_effect=subprocess.TimeoutExpired("cmd", 30)):
        code, out, err = engine._run_command(mock_repo_path, ["fetch"])
        assert code == 124
        assert "timed out" in err

def test_verify_state_clean(engine, mock_repo_path):
    """Tests state verification for a clean working tree."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        # Mock porcelain status returning empty string (clean)
        mock_run.return_value = (0, "", "")
        assert engine._verify_state(mock_repo_path, "clean") is True
        
        # Mock porcelain status returning changes (dirty)
        mock_run.return_value = (0, "M file.txt", "")
        assert engine._verify_state(mock_repo_path, "clean") is False

def test_resolve_context_invalid_path(engine):
    """Tests context resolution when .git directory is missing."""
    assert engine._resolve_context("/non/existent/path", {}) == (False, "Invalid Git repository path")

def test_resolve_context_dirty_tree(engine, mock_repo_path):
    """Tests context resolution when tree is dirty and force is False."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        mock_run.return_value = (0, "M modified_file.py", "")
        is_valid, msg = engine._resolve_context(mock_repo_path, {"force": False})
        assert is_valid is False
        assert "Dirty working tree" in msg

# --- Unit Tests: Strategy Implementations ---

def test_handle_commit_flow_success(engine, mock_repo_path):
    """Tests the full atomic commit flow."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        # Mock responses for: checkout, add, commit, rev-parse
        mock_run.side_effect = [
            (0, "switched", ""), # checkout
            (0, "", ""),         # add
            (0, "committed", ""),# commit
            (0, "abc123hash", ""),# rev-parse
        ]
        
        params = {"msg": "feat: test", "branch": "test-branch"}
        result = engine._handle_commit_flow(mock_repo_path, params, {})
        
        assert result["commit_hash"] == "abc123hash"
        assert result["branch"] == "test-branch"
        assert mock_run.call_count == 4

def test_handle_commit_flow_failure_rollback(engine, mock_repo_path):
    """Tests that a failed commit triggers a hard reset rollback."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        # Mock: add succeeds, commit fails
        mock_run.side_effect = [
            (0, "", ""),         # add
            (1, "", "commit error"), # commit
            (0, "", ""),         # reset --hard
        ]
        
        with pytest.raises(RuntimeError, match="Commit failed"):
            engine._handle_commit_flow(mock_repo_path, {"msg": "fail"}, {})
        
        # Verify rollback was called
        mock_run.assert_any_call(mock_repo_path, ["reset", "--hard", "HEAD"])

def test_handle_sync_success(engine, mock_repo_path):
    """Tests successful pull-rebase and push."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        mock_run.side_effect = [
            (0, "pull success", ""), # pull
            (0, "push success", ""), # push
        ]
        
        params = {"remote": "origin", "branch": "main"}
        result = engine._handle_sync(mock_repo_path, params, {})
        
        assert result["remote_synced"] is True
        assert result["remote"] == "origin"

def test_handle_sync_conflict(engine, mock_repo_path):
    """Tests sync failure when merge conflicts occur."""
    with patch.object(GitSkillEngine, "_run_command") as mock_run:
        mock_run.return_value = (1, "", "CONFLICT (content): Merge conflict in file.txt")
        
        with pytest.raises(RuntimeError, match="Sync conflict"):
            engine._handle_sync(mock_repo_path, {}, {})

# --- Integration Tests: Public Interface ---

def test_execute_missing_args(engine):
    """Tests execute method with incomplete payload."""
    payload = {"action": "sync"} # Missing repo_path and params
    result = engine.execute(payload)
    assert result["status"] == "failure"
    assert "Missing required arguments" in result["telemetry"]["stderr"]

def test_execute_unsupported_action(engine, mock_repo_path):
    """Tests execute method with an invalid action."""
    payload = {
        "action": "invalid_action",
        "repo_path": mock_repo_path,
        "params": {}
    }
    with patch.object(GitSkillEngine, "_resolve_context", return_value=(True, "OK")):
        result = engine.execute(payload)
        assert result["status"] == "failure"
        assert "Unsupported action" in result["telemetry"]["stderr"]

def test_execute_full_success_cycle(engine, mock_repo_path):
    """End-to-end test of the execute method for a commit flow."""
    payload = {
        "action": GitAction.COMMIT_FLOW.value,
        "repo_path": mock_repo_path,
        "params": {"msg": "Integration test", "branch": "main"},
        "options": {"force": True}
    }
    
    with patch.object(GitSkillEngine, "_resolve_context", return_value=(True, "OK")), \
         patch.object(GitSkillEngine, "_handle_commit_flow", return_value={"commit_hash": "xyz"}), \
         patch.object(GitSkillEngine, "_verify_state", return_value=True):
        
        result = engine.execute(payload)
        
        assert result["status"] == "success"
        assert result["action_performed"] == "commit_flow"
        assert result["data"]["commit_hash"] == "xyz"
        assert "execution_time_ms" in result["telemetry"]

def test_execute_detached_head_failure(engine, mock_repo_path):
    """Tests failure when post-execution state verification fails."""
    payload = {
        "action": GitAction.COMMIT_FLOW.value,
        "repo_path": mock_repo_path,
        "params": {"msg": "test"},
    }
    
    with patch.object(GitSkillEngine, "_resolve_context", return_value=(True, "OK")), \
         patch.object(GitSkillEngine, "_handle_commit_flow", return_value={"hash": "123"}), \
         patch.object(GitSkillEngine, "_verify_state", return_value=False):
        
        result = engine.execute(payload)
        assert result["status"] == "failure"
        assert "Detached HEAD" in result["telemetry"]["stderr"]