# Generated by Verify (QA Engineer)
import pytest
import asyncio
import os
from unittest.mock import MagicMock, AsyncMock, patch
from typing import List

# Assuming the source code is in a file named vuln_scanner.py
from vuln_scanner import (
    VulnScanOrchestrator, BaseEngine, SemgrepEngine, NucleiEngine,
    Vulnerability, Severity, ScanProfile, TargetValidationError,
    RiskEngine, Normalizer, VulnerabilityReport
)

# =============================================================================
# FIXTURES
# =============================================================================

@pytest.fixture
def mock_vulnerability():
    return Vulnerability(
        id="VULN-001",
        severity=Severity.HIGH,
        cvss_score=8.0,
        category="Injection",
        location={"file": "test.py", "line": 10},
        description="Test Vuln",
        remediation="Fix it",
        evidence="payload",
        confidence=1.0
    )

@pytest.fixture
def orchestrator():
    engines = [SemgrepEngine("semgrep"), NucleiEngine("nuclei")]
    return VulnScanOrchestrator(engines)

@pytest.fixture
def valid_config():
    return {
        "target": "https://api.test.com",
        "scan_profile": ScanProfile.STANDARD,
        "engines": ["ALL"],
        "ignore_rules": [],
        "auth_token": "test-token"
    }

# =============================================================================
# UNIT TESTS: RiskEngine & Normalizer
# =============================================================================

class TestRiskEngine:
    def test_calculate_score_empty(self):
        assert RiskEngine.calculate_score([]) == 0.0

    def test_calculate_score_weighted(self):
        vulns = [
            Vulnerability("1", Severity.CRITICAL, 9.0, "C", {}, "D", "R", "E", confidence=1.0), # 10.0
            Vulnerability("2", Severity.LOW, 2.0, "C", {}, "D", "R", "E", confidence=0.5),      # 1.0 * 0.5 = 0.5
        ]
        # (10.0 + 0.5) / 2 = 5.25
        assert RiskEngine.calculate_score(vulns) == 5.25

class TestNormalizer:
    def test_normalize_valid_data(self):
        raw_data = [{
            "id": "RAW-01",
            "severity": "CRITICAL",
            "cvss": 9.5,
            "category": "XSS",
            "location": {"file": "index.html", "line": 5},
            "description": "desc",
            "remediation": "rem",
            "evidence": "evid",
            "confidence": 0.8
        }]
        normalized = Normalizer.normalize(raw_data, "mock_engine")
        assert len(normalized) == 1
        assert normalized[0].severity == Severity.CRITICAL
        assert normalized[0].confidence == 0.8

# =============================================================================
# UNIT TESTS: VulnScanOrchestrator
# =============================================================================

class TestVulnScanOrchestrator:
    
    def test_validate_target_url_success(self, orchestrator):
        # Should not raise exception
        orchestrator._validate_target("https://google.com")

    def test_validate_target_url_fail(self, orchestrator):
        with pytest.raises(TargetValidationError) as exc:
            orchestrator._validate_target("https://")
        assert exc.value.code == "ERR_INVALID_TARGET"

    def test_validate_target_path_success(self, orchestrator, tmp_path):
        test_file = tmp_path / "test_code.py"
        test_file.write_text("print('hello')")
        orchestrator._validate_target(str(test_file))

    def test_validate_target_path_fail(self, orchestrator):
        with pytest.raises(TargetValidationError):
            orchestrator._validate_target("/non/existent/path/to/nothing")

    @pytest.mark.asyncio
    async def test_execute_scan_full_flow(self, orchestrator, valid_config):
        report = await orchestrator.execute_scan(valid_config)
        
        assert isinstance(report, VulnerabilityReport)
        assert report.status == "COMPLETE"
        assert len(report.vulnerabilities) > 0
        assert report.summary.overall_risk_score > 0
        assert "semgrep" in report.scan_metadata.engines_used
        assert "nuclei" in report.scan_metadata.engines_used

    @pytest.mark.asyncio
    async def test_execute_scan_filtering(self, orchestrator, valid_config):
        # Mock engines to return specific IDs
        with patch.object(SemgrepEngine, 'run', new_callable=AsyncMock) as mock_semgrep, \
             patch.object(NucleiEngine, 'run', new_callable=AsyncMock) as mock_nuclei:
            
            mock_semgrep.return_value = [
                Vulnerability("SG-1", Severity.HIGH, 7.0, "C", {}, "D", "R", "E"),
                Vulnerability("SG-IGNORE", Severity.HIGH, 7.0, "C", {}, "D", "R", "E")
            ]
            mock_nuclei.return_value = []
            
            valid_config["ignore_rules"] = ["SG-IGNORE"]
            valid_config["engines"] = ["semgrep"]
            
            report = await orchestrator.execute_scan(valid_config)
            
            assert len(report.vulnerabilities) == 1
            assert report.vulnerabilities[0].id == "SG-1"
            assert "nuclei" not in report.scan_metadata.engines_used

    @pytest.mark.asyncio
    async def test_deduplication_logic(self, orchestrator, valid_config):
        # Create two vulnerabilities that result in the same dedup hash
        # Hash is based on location (file:line), category, and id.
        # To test deduplication, we need same location/category but different severity.
        
        v1 = Vulnerability("V-1", Severity.LOW, 1.0, "Cat1", {"file": "a.py", "line": 1}, "D", "R", "E")
        v2 = Vulnerability("V-1", Severity.CRITICAL, 9.0, "Cat1", {"file": "a.py", "line": 1}, "D", "R", "E")
        
        with patch.object(SemgrepEngine, 'run', new_callable=AsyncMock) as mock_run:
            mock_run.return_value = [v1, v2]
            orchestrator.engines = [SemgrepEngine("semgrep")]
            
            report = await orchestrator.execute_scan(valid_config)
            
            # Should only keep the one with higher severity
            assert len(report.vulnerabilities) == 1
            assert report.vulnerabilities[0].severity == Severity.CRITICAL

    @pytest.mark.asyncio
    async def test_engine_timeout_handling(self, orchestrator, valid_config):
        class SlowEngine(BaseEngine):
            async def run(self, t, p, a=None):
                await asyncio.sleep(10)
                return []

        orchestrator.engines = [SlowEngine("slow")]
        
        # Patch wait_for to trigger timeout immediately
        with patch('asyncio.wait_for', side_effect=asyncio.TimeoutError):
            report = await orchestrator.execute_scan(valid_config)
            assert report.status == "PARTIAL"

    @pytest.mark.asyncio
    async def test_engine_failure_handling(self, orchestrator, valid_config):
        class FailingEngine(BaseEngine):
            async def run(self, t, p, a=None):
                raise RuntimeError("Crash!")

        orchestrator.engines = [FailingEngine("fail")]
        
        report = await orchestrator.execute_scan(valid_config)
        assert report.status == "PARTIAL"
        assert len(report.vulnerabilities) == 0

# =============================================================================
# INTEGRATION TEST: Vulnerability Hash
# =============================================================================

def test_vulnerability_dedup_hash():
    v1 = Vulnerability("ID1", Severity.LOW, 1.0, "Cat1", {"file": "f.py", "line": 10}, "D", "R", "E")
    v2 = Vulnerability("ID1", Severity.LOW, 1.0, "Cat1", {"file": "f.py", "line": 10}, "D", "R", "E")
    v3 = Vulnerability("ID2", Severity.LOW, 1.0, "Cat1", {"file": "f.py", "line": 10}, "D", "R", "E")
    
    assert v1.get_dedup_hash() == v2.get_dedup_hash()
    assert v1.get_dedup_hash() != v3.get_dedup_hash()