# Generated by Verify (QA Engineer)
import pytest
import asyncio
import json
from unittest.mock import MagicMock, patch
from pydantic import ValidationError as PydanticValidationError

# Importing the components from the target file
# Assuming the file is in the same directory for the test runner
from output_validator_skill import (
    OutputValidatorSkill, 
    ValidationResult, 
    Violation, 
    ActionRecommendation, 
    ValidationProfile
)

# --- Fixtures ---

@pytest.fixture
def validator_skill():
    """Provides a clean instance of OutputValidatorSkill for each test."""
    return OutputValidatorSkill()

@pytest.fixture
def valid_json_payload():
    return json.dumps({"status": "success", "data": {"id": 123, "value": "verified"}})

@pytest.fixture
def invalid_json_payload():
    return '{"status": "success", "data": { "id": 123, "value": "unclosed quote }'

@pytest.fixture
def hallucination_payload():
    return "The requested data is unavailable. As an AI language model, I don't have personal opinions on this."

# --- Test Suite ---

class TestOutputValidatorSkill:

    @pytest.mark.asyncio
    async def test_initialization(self, validator_skill):
        """Verify the skill initializes with default or custom config."""
        assert validator_skill.config == {}
        
        custom_config = {"strict_mode": True}
        skill_custom = OutputValidatorSkill(config=custom_config)
        assert skill_custom.config["strict_mode"] is True

    @pytest.mark.asyncio
    async def test_hallucination_detection(self, validator_skill, hallucination_payload):
        """
        Test that AI-typical hallucination markers trigger a HARD_FAIL.
        """
        # Note: Since the provided source was truncated at 'asyn', 
        # I am implementing tests against the intended logic of the class definition.
        
        # Mocking the internal validation method if it's async
        # We simulate the logic: if any marker in HALLUCINATION_MARKERS is found -> HARD_FAIL
        
        # This test assumes the implementation of a method like `validate_output`
        # If the method name differs in the final implementation, this would be updated.
        try:
            result = await validator_skill.validate_output(
                output=hallucination_payload, 
                profile=ValidationProfile.TECHNICAL_DOC
            )
            
            assert result.action_recommendation == ActionRecommendation.HARD_FAIL
            assert any("ai language model" in v.message.lower() for v in result.violations)
            assert result.is_valid is False
        except AttributeError:
            pytest.fail("Method 'validate_output' not implemented or named differently in OutputValidatorSkill")

    @pytest.mark.asyncio
    async def test_json_schema_validation_pass(self, validator_skill, valid_json_payload):
        """Test that valid JSON matching a schema passes validation."""
        schema = {
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "data": {"type": "object"}
            },
            "required": ["status", "data"]
        }
        
        result = await validator_skill.validate_output(
            output=valid_json_payload,
            profile=ValidationProfile.STRICT_JSON,
            schema=schema
        )
        
        assert result.is_valid is True
        assert result.action_recommendation == ActionRecommendation.PASS
        assert result.confidence_score == 1.0
        assert len(result.violations) == 0

    @pytest.mark.asyncio
    async def test_json_schema_validation_fail(self, validator_skill, invalid_json_payload):
        """Test that malformed JSON triggers a RETRY_WITH_PROMPT."""
        schema = {"type": "object"}
        
        result = await validator_skill.validate_output(
            output=invalid_json_payload,
            profile=ValidationProfile.STRICT_JSON,
            schema=schema
        )
        
        assert result.is_valid is False
        assert result.action_recommendation == ActionRecommendation.RETRY_WITH_PROMPT
        assert len(result.violations) > 0

    @pytest.mark.asyncio
    async def test_confidence_score_constraints(self, validator_skill):
        """Ensure the ValidationResult Pydantic model enforces score boundaries [0, 1]."""
        # Test upper bound violation
        with pytest.raises(PydanticValidationError):
            ValidationResult(
                is_valid=True,
                confidence_score=1.1, # Invalid
                violations=[],
                sanitized_output="test",
                action_recommendation=ActionRecommendation.PASS
            )
        
        # Test lower bound violation
        with pytest.raises(PydanticValidationError):
            ValidationResult(
                is_valid=True,
                confidence_score=-0.1, # Invalid
                violations=[],
                sanitized_output="test",
                action_recommendation=ActionRecommendation.PASS
            )

    @pytest.mark.asyncio
    async def test_sanitization_logic(self, validator_skill):
        """Verify that the sanitization stage removes unwanted noise."""
        noisy_input = "Here is the result: { 'key': 'value' }. I hope this helps!"
        
        # Assuming the skill has a sanitization method or it's part of validate_output
        result = await validator_skill.validate_output(
            output=noisy_input,
            profile=ValidationProfile.STRICT_JSON
        )
        
        # The sanitized output should ideally contain only the JSON part
        assert "{ 'key': 'value' }" in str(result.sanitized_output)
        assert "I hope this helps!" not in str(result.sanitized_output)

    @pytest.mark.asyncio
    async def test_empty_input_handling(self, validator_skill):
        """Test system robustness against null or empty strings."""
        result = await validator_skill.validate_output(
            output="",
            profile=ValidationProfile.STRICT_JSON
        )
        
        assert result.is_valid is False
        assert result.action_recommendation == ActionRecommendation.RETRY_WITH_PROMPT

    @pytest.mark.asyncio
    async def test_technical_doc_profile(self, validator_skill):
        """Verify that TECHNICAL_DOC profile allows non-JSON but checks for structure."""
        doc_content = "# Technical Specification\n\nSection 1: Architecture\n- Modular design."
        
        result = await validator_skill.validate_output(
            output=doc_content,
            profile=ValidationProfile.TECHNICAL_DOC
        )
        
        # Technical docs shouldn't fail for not being JSON
        assert result.is_valid is True
        assert result.action_recommendation == ActionRecommendation.PASS

# --- Performance/Stress Simulation ---

@pytest.mark.asyncio
async def test_high_concurrency_validation(validator_skill):
    """Simulate high-throughput validation requests to ensure no race conditions."""
    payloads = [
        {"out": "Valid JSON", "prof": ValidationProfile.STRICT_JSON, "data": '{"a":1}'},
        {"out": "Hallucination", "prof": ValidationProfile.STRICT_JSON, "data": "As an AI model..."},
        {"out": "Invalid", "prof": ValidationProfile.STRICT_JSON, "data": '{bad}'},
    ] * 50 # 150 requests
    
    tasks = [
        validator_skill.validate_output(p["data"], p["prof"]) 
        for p in payloads
    ]
    
    results = await asyncio.gather(*tasks)
    assert len(results) == 150
    assert all(isinstance(r, ValidationResult) for r in results)