# Generated by Verify (QA Engineer)
import pytest
import logging
from unittest.mock import MagicMock, patch
from logic_prover import LogicProver, LogicType, Verdict, VerificationResult, Z3_AVAILABLE

# --- Fixtures ---

@pytest.fixture
def prover():
    """Provides a LogicProver instance with a silenced logger."""
    logger = logging.getLogger("TestLogger")
    logger.setLevel(logging.CRITICAL) 
    return LogicProver(logger=logger)

@pytest.fixture
def valid_payload():
    """Standard valid SMT-LIB payload."""
    return {
        "formula": "(forall ((x Int)) (=> (> x 0) (> (+ x 1) 1)))",
        "logic_type": LogicType.SMT,
        "axioms": [],
        "timeout": 1000
    }

# --- Unit Tests: Schema & Parsing ---

def test_validate_schema_success(prover, valid_payload):
    """Ensure valid payloads do not raise exceptions."""
    prover._validate_schema(valid_payload)

def test_validate_schema_missing_fields(prover):
    """Ensure missing required fields raise ValueError."""
    with pytest.raises(ValueError, match="SYNTAX_ERR: Missing required field 'formula'"):
        prover._validate_schema({"logic_type": LogicType.SMT})
    
    with pytest.raises(ValueError, match="SYNTAX_ERR: Missing required field 'logic_type'"):
        prover._validate_schema({"formula": "(assert true)"})

def test_parse_s_expression_simple(prover):
    """Test parsing of basic atoms and simple lists."""
    assert prover._parse_s_expression("atom") == "atom"
    assert prover._parse_s_expression("(a b c)") == ["a", "b", "c"]

def test_parse_s_expression_nested(prover):
    """Test complex nested S-expressions."""
    expr = "(forall (x Int) (=> (> x 0) (> (+ x 1) 1)))"
    expected = ['forall', ['x', 'Int'], ['=>', ['>', 'x', '0'], ['>', ['+', 'x', '1'], '1']]]
    # Note: The parser treats numbers as strings unless cast, which matches the provided implementation
    result = prover._parse_s_expression(expr)
    assert result[0] == 'forall'
    assert isinstance(result[2], list)
    assert result[2][0] == '=>'

def test_simplify_to_nnf_double_negation(prover):
    """Test that (not (not P)) simplifies to P."""
    formula = ['not', ['not', 'P']]
    assert prover._simplify_to_nnf(formula) == 'P'

def test_simplify_to_nnf_single_negation(prover):
    """Test that single negation is preserved."""
    formula = ['not', 'P']
    assert prover._simplify_to_nnf(formula) == ['not', 'P']

def test_simplify_to_nnf_recursive(prover):
    """Test simplification within nested structures."""
    formula = ['and', ['not', ['not', 'P']], 'Q']
    assert prover._simplify_to_nnf(formula) == ['and', 'P', 'Q']

# --- Unit Tests: Solver Logic ---

def test_prove_invalid_schema(prover):
    """Test that prove() handles schema errors gracefully."""
    result = prover.prove({"wrong_key": "value"})
    assert result.verdict == Verdict.UNKNOWN
    assert "SYNTAX_ERR" in result.proof_trace[0]

@pytest.mark.skipif(not Z3_AVAILABLE, reason="Z3 not installed")
def test_execute_z3_solver_valid(prover):
    """Test Z3 integration for a known tautology."""
    payload = {
        "formula": "(assert (= 1 1))", # Simplified for Z3 parse_smt2_string
        "logic_type": LogicType.SMT,
        "axioms": []
    }
    # We use a simple tautology: (1=1). Negation is (1!=1) which is UNSAT.
    result = prover.prove(payload)
    assert result.verdict == Verdict.VALID

@pytest.mark.skipif(not Z3_AVAILABLE, reason="Z3 not installed")
def test_execute_z3_solver_invalid(prover):
    """Test Z3 integration for a known falsehood."""
    payload = {
        "formula": "(assert (= 1 2))", 
        "logic_type": LogicType.SMT,
        "axioms": []
    }
    # Negation is (1!=2) which is SAT.
    result = prover.prove(payload)
    assert result.verdict == Verdict.INVALID
    assert result.model is not None

@pytest.mark.skipif(not Z3_AVAILABLE, reason="Z3 not installed")
def test_execute_z3_solver_syntax_error(prover):
    """Test Z3 handling of malformed SMT-LIB strings."""
    payload = {
        "formula": "(this is not smt-lib)",
        "logic_type": LogicType.SMT,
        "axioms": []
    }
    result = prover.prove(payload)
    assert result.verdict == Verdict.UNKNOWN
    assert "SYNTAX_ERR" in result.proof_trace[0]

# --- Unit Tests: Simulation Mode ---

def test_simulate_solver_tautology(prover):
    """Test simulation fallback for tautology-like strings."""
    # Simulation triggers VALID if "=>" and "x" are present
    result = prover._simulate_solver("(=> x 1)", [])
    assert result.verdict == Verdict.VALID
    assert "Simulated" in result.proof_trace[0]

def test_simulate_solver_unknown(prover):
    """Test simulation fallback for unknown strings."""
    result = prover._simulate_solver("random string", [])
    assert result.verdict == Verdict.UNKNOWN

# --- Integration & Mocking ---

def test_prove_orchestration_flow(prover, valid_payload):
    """Test the full prove() pipeline using mocks to isolate Z3."""
    with patch.object(LogicProver, '_execute_z3_solver') as mock_z3:
        mock_z3.return_value = VerificationResult(Verdict.VALID, proof_trace=["Mocked Proof"])
        
        # Force Z3_AVAILABLE to True for this test to bypass simulation
        with patch('logic_prover.Z3_AVAILABLE', True):
            result = prover.prove(valid_payload)
            
            assert result.verdict == Verdict.VALID
            assert result.proof_trace == ["Mocked Proof"]
            mock_z3.assert_called_once()

def test_prove_exception_handling(prover, valid_payload):
    """Test that unexpected exceptions in the pipeline return Verdict.UNKNOWN."""
    with patch.object(LogicProver, '_parse_s_expression', side_effect=RuntimeError("Crash")):
        result = prover.prove(valid_payload)
        assert result.verdict == Verdict.UNKNOWN
        assert "Error: Crash" in result.proof_trace[0]

# --- Performance/Stress Edge Cases ---

def test_deeply_nested_s_expression(prover):
    """Test parser resilience against deeply nested parentheses."""
    depth = 100
    expr = "(" * depth + "atom" + ")" * depth
    result = prover._parse_s_expression(expr)
    # Should resolve to 'atom' after stripping all layers
    assert result == "atom"

def test_empty_axioms_list(prover, valid_payload):
    """Ensure empty axioms list is handled without error."""
    valid_payload['axioms'] = []
    # Should not crash regardless of Z3 availability
    result = prover.prove(valid_payload)
    assert isinstance(result, VerificationResult)