# Generated by Verify (QA Engineer)
"""
test_paper_analyzer.py
Swarm OS v12 - Advanced Neural Architecture
Comprehensive pytest test suite for AdvancedPaperAnalyzer.

Author: Verify (QA Engineer)
Date: 2026-07-09
Version: 1.0.0

Test Coverage:
- Unit tests for all public methods
- Edge cases: empty text, special characters, unicode
- Integration tests with mock dependencies
- Property-based tests for statistical invariants
- Performance benchmarks for critical paths
- Error handling and boundary conditions
"""

import pytest
import json
import tempfile
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock, PropertyMock
from typing import List, Dict, Any
from collections import Counter

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

from paper_analyzer import AdvancedPaperAnalyzer
from research_pipeline import PaperMetadata, AnalysisResult


# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def analyzer():
    """Create a fresh analyzer instance for each test."""
    return AdvancedPaperAnalyzer()


@pytest.fixture
def sample_papers() -> List[PaperMetadata]:
    """Generate diverse sample papers for testing."""
    return [
        PaperMetadata(
            title="Attention Is All You Need",
            authors=["Vaswani", "Shazeer", "Parmar"],
            abstract="We propose a new simple network architecture, the Transformer, based solely on attention mechanisms.",
            year=2017,
            doi="10.48550/arXiv.1706.03762",
            citations=50000
        ),
        PaperMetadata(
            title="Deep Reinforcement Learning",
            authors=["Mnih", "Kavukcuoglu", "Silver"],
            abstract="We present the first deep learning model to successfully learn control policies directly from high-dimensional sensory input using reinforcement learning.",
            year=2015,
            doi="10.1038/nature14236",
            citations=30000
        ),
        PaperMetadata(
            title="GANs for Image Generation",
            authors=["Goodfellow", "Pouget-Abadie", "Mirza"],
            abstract="We propose a new framework for estimating generative models via an adversarial process.",
            year=2014,
            doi="10.48550/arXiv.1406.2661",
            citations=45000
        ),
        PaperMetadata(
            title="BERT: Pre-training of Deep Bidirectional Transformers",
            authors=["Devlin", "Chang", "Lee"],
            abstract="We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.",
            year=2019,
            doi="10.48550/arXiv.1810.04805",
            citations=60000
        )
    ]


@pytest.fixture
def empty_paper() -> PaperMetadata:
    """Paper with minimal content for edge case testing."""
    return PaperMetadata(
        title="",
        authors=[],
        abstract="",
        year=2020,
        doi="",
        citations=0
    )


@pytest.fixture
def unicode_paper() -> PaperMetadata:
    """Paper with unicode characters in abstract."""
    return PaperMetadata(
        title="Neural Networks with 日本語 Characters",
        authors=["Taro", "Hanako"],
        abstract="研究論文の解析における深層学習の応用について調査した。",
        year=2023,
        doi="10.1234/test.unicode",
        citations=100
    )


# ============================================================================
# Unit Tests - Initialization
# ============================================================================

class TestInitialization:
    """Test analyzer initialization and configuration."""

    def test_default_initialization(self, analyzer):
        """Verify default parameters are set correctly."""
        assert analyzer.vectorizer is not None
        assert isinstance(analyzer.vectorizer, TfidfVectorizer)
        assert analyzer.vectorizer.max_features == 1000
        assert analyzer.vectorizer.stop_words == 'english'
        assert analyzer.vectorizer.ngram_range == (1, 3)

    def test_taxonomy_loaded(self, analyzer):
        """Verify taxonomy is loaded with expected categories."""
        assert hasattr(analyzer, 'taxonomy')
        assert 'deep_learning' in analyzer.taxonomy
        assert 'reinforcement_learning' in analyzer.taxonomy
        assert 'computer_vision' in analyzer.taxonomy
        assert 'nlp' in analyzer.taxonomy
        assert len(analyzer.taxonomy) >= 4

    def test_taxonomy_keywords_non_empty(self, analyzer):
        """Verify each taxonomy category has keywords."""
        for category, keywords in analyzer.taxonomy.items():
            assert len(keywords) > 0, f"Category '{category}' has no keywords"
            for keyword in keywords:
                assert isinstance(keyword, str)
                assert len(keyword) > 0


# ============================================================================
# Unit Tests - Keyword Extraction
# ============================================================================

class TestKeywordExtraction:
    """Test TF-IDF based keyword extraction."""

    def test_extract_keywords_basic(self, analyzer, sample_papers):
        """Test basic keyword extraction from sample papers."""
        for paper in sample_papers:
            keywords = analyzer.extract_keywords(paper)
            assert isinstance(keywords, list)
            assert len(keywords) > 0
            # Keywords should be relevant to the paper content
            if "transformer" in paper.abstract.lower():
                assert any("transformer" in kw.lower() for kw in keywords)

    def test_extract_keywords_empty_abstract(self, analyzer, empty_paper):
        """Test keyword extraction with empty abstract."""
        keywords = analyzer.extract_keywords(empty_paper)
        assert isinstance(keywords, list)
        assert len(keywords) == 0

    def test_extract_keywords_unicode(self, analyzer, unicode_paper):
        """Test keyword extraction with unicode content."""
        keywords = analyzer.extract_keywords(unicode_paper)
        assert isinstance(keywords, list)
        # Should handle unicode without errors
        for kw in keywords:
            assert isinstance(kw, str)

    def test_extract_keywords_max_keywords(self, analyzer, sample_papers):
        """Test max_keywords parameter."""
        paper = sample_papers[0]
        keywords_5 = analyzer.extract_keywords(paper, max_keywords=5)
        keywords_10 = analyzer.extract_keywords(paper, max_keywords=10)
        assert len(keywords_5) <= 5
        assert len(keywords_10) <= 10
        assert len(keywords_5) <= len(keywords_10)

    def test_extract_keywords_consistency(self, analyzer, sample_papers):
        """Test that same input produces same output."""
        paper = sample_papers[0]
        keywords1 = analyzer.extract_keywords(paper)
        keywords2 = analyzer.extract_keywords(paper)
        assert keywords1 == keywords2

    def test_extract_keywords_special_characters(self, analyzer):
        """Test with special characters in abstract."""
        paper = PaperMetadata(
            title="Test Paper",
            authors=["Test"],
            abstract="Machine learning & AI @ scale! (2024) [research] {important}",
            year=2024,
            doi="10.1234/test",
            citations=50
        )
        keywords = analyzer.extract_keywords(paper)
        assert isinstance(keywords, list)
        # Should handle special characters gracefully


# ============================================================================
# Unit Tests - Methodology Classification
# ============================================================================

class TestMethodologyClassification:
    """Test methodology taxonomy classification."""

    def test_classify_deep_learning(self, analyzer, sample_papers):
        """Test classification of deep learning papers."""
        paper = sample_papers[0]  # Transformer paper
        categories = analyzer.classify_methodology(paper)
        assert 'deep_learning' in categories
        assert categories['deep_learning'] > 0.0

    def test_classify_reinforcement_learning(self, analyzer, sample_papers):
        """Test classification of RL papers."""
        paper = sample_papers[1]  # Deep RL paper
        categories = analyzer.classify_methodology(paper)
        assert 'reinforcement_learning' in categories
        assert categories['reinforcement_learning'] > 0.0

    def test_classify_empty_paper(self, analyzer, empty_paper):
        """Test classification of empty paper returns zero scores."""
        categories = analyzer.classify_methodology(empty_paper)
        for score in categories.values():
            assert score == 0.0

    def test_classify_multiple_categories(self, analyzer):
        """Test paper that spans multiple categories."""
        paper = PaperMetadata(
            title="Multi-modal Learning",
            authors=["Test"],
            abstract="Using transformer attention with CNN features for reinforcement learning in computer vision tasks.",
            year=2024,
            doi="10.1234/multi",
            citations=200
        )
        categories = analyzer.classify_methodology(paper)
        # Should detect multiple methodologies
        positive_categories = [cat for cat, score in categories.items() if score > 0]
        assert len(positive_categories) >= 2

    def test_classify_scores_sum_to_one(self, analyzer, sample_papers):
        """Test that classification scores sum to approximately 1.0."""
        for paper in sample_papers:
            categories = analyzer.classify_methodology(paper)
            total_score = sum(categories.values())
            assert abs(total_score - 1.0) < 0.01, f"Total score {total_score} != 1.0"

    def test_classify_normalization(self, analyzer):
        """Test that scores are properly normalized."""
        paper = PaperMetadata(
            title="Pure Deep Learning",
            authors=["Test"],
            abstract="transformer attention cnn rnn lstm gru gan vae diffusion",
            year=2024,
            doi="10.1234/pure",
            citations=100
        )
        categories = analyzer.classify_methodology(paper)
        assert categories['deep_learning'] > 0.8  # Should be dominant


# ============================================================================
# Unit Tests - Citation Analysis
# ============================================================================

class TestCitationAnalysis:
    """Test citation graph analysis."""

    def test_analyze_citations_basic(self, analyzer, sample_papers):
        """Test basic citation analysis."""
        result = analyzer.analyze_citations(sample_papers)
        assert isinstance(result, dict)
        assert 'total_citations' in result
        assert 'average_citations' in result
        assert 'median_citations' in result
        assert 'max_citations' in result
        assert 'min_citations' in result

    def test_analyze_citations_values(self, analyzer, sample_papers):
        """Test citation statistics values."""
        result = analyzer.analyze_citations(sample_papers)
        citations = [p.citations for p in sample_papers]
        assert result['total_citations'] == sum(citations)
        assert result['average_citations'] == np.mean(citations)
        assert result['median_citations'] == np.median(citations)
        assert result['max_citations'] == max(citations)
        assert result['min_citations'] == min(citations)

    def test_analyze_citations_empty_list(self, analyzer):
        """Test citation analysis with empty list."""
        result = analyzer.analyze_citations([])
        assert result['total_citations'] == 0
        assert result['average_citations'] == 0.0
        assert result['median_citations'] == 0.0
        assert result['max_citations'] == 0
        assert result['min_citations'] == 0

    def test_analyze_citations_single_paper(self, analyzer, sample_papers):
        """Test citation analysis with single paper."""
        result = analyzer.analyze_citations([sample_papers[0]])
        assert result['total_citations'] == sample_papers[0].citations
        assert result['average_citations'] == float(sample_papers[0].citations)
        assert result['median_citations'] == float(sample_papers[0].citations)

    def test_analyze_citations_zero_citations(self, analyzer):
        """Test papers with zero citations."""
        papers = [
            PaperMetadata("A", ["X"], "abstract", 2024, "doi1", 0),
            PaperMetadata("B", ["Y"], "abstract", 2024, "doi2", 0)
        ]
        result = analyzer.analyze_citations(papers)
        assert result['total_citations'] == 0
        assert result['average_citations'] == 0.0


# ============================================================================
# Unit Tests - Trend Detection
# ============================================================================

class TestTrendDetection:
    """Test trend detection across multiple papers."""

    def test_detect_trends_basic(self, analyzer, sample_papers):
        """Test basic trend detection."""
        trends = analyzer.detect_trends(sample_papers)
        assert isinstance(trends, dict)
        assert 'hot_topics' in trends
        assert 'emerging_fields' in trends
        assert 'declining_topics' in trends

    def test_detect_trends_hot_topics(self, analyzer, sample_papers):
        """Test identification of hot topics."""
        trends = analyzer.detect_trends(sample_papers)
        hot_topics = trends['hot_topics']
        assert isinstance(hot_topics, list)
        # Transformer and attention should be hot topics
        topic_text = ' '.join(hot_topics).lower()
        assert any('transformer' in topic_text or 'attention' in topic_text)

    def test_detect_trends_empty_list(self, analyzer):
        """Test trend detection with empty paper list."""
        trends = analyzer.detect_trends([])
        assert trends['hot_topics'] == []
        assert trends['emerging_fields'] == []
        assert trends['declining_topics'] == []

    def test_detect_trends_single_paper(self, analyzer, sample_papers):
        """Test trend detection with single paper."""
        trends = analyzer.detect_trends([sample_papers[0]])
        assert len(trends['hot_topics']) > 0
        assert len(trends['emerging_fields']) >= 0
        assert len(trends['declining_topics']) >= 0

    def test_detect_trends_temporal(self, analyzer):
        """Test temporal trend detection."""
        papers = [
            PaperMetadata("Old", ["X"], "neural network mlp", 2010, "doi1", 100),
            PaperMetadata("Mid", ["Y"], "deep learning cnn", 2015, "doi2", 200),
            PaperMetadata("New", ["Z"], "transformer attention", 2020, "doi3", 300)
        ]
        trends = analyzer.detect_trends(papers)
        # Newer topics should appear in hot topics
        assert any('transformer' in str(trends['hot_topics']).lower())


# ============================================================================
# Unit Tests - Paper Similarity
# ============================================================================

class TestPaperSimilarity:
    """Test paper similarity computation."""

    def test_similarity_same_paper(self, analyzer, sample_papers):
        """Test similarity of a paper with itself."""
        paper = sample_papers[0]
        similarity = analyzer.compute_similarity(paper, paper)
        assert similarity == 1.0

    def test_similarity_different_papers(self, analyzer, sample_papers):
        """Test similarity between different papers."""
        sim = analyzer.compute_similarity(sample_papers[0], sample_papers[1])
        assert 0.0 <= sim <= 1.0

    def test_similarity_related_papers(self, analyzer, sample_papers):
        """Test similarity between related papers."""
        # Both are transformer-based
        sim = analyzer.compute_similarity(sample_papers[0], sample_papers[3])
        assert sim > 0.1  # Should have some similarity

    def test_similarity_unrelated_papers(self, analyzer, sample_papers):
        """Test similarity between unrelated papers."""
        sim = analyzer.compute_similarity(sample_papers[0], sample_papers[2])
        # GANs and Transformers are different topics
        assert sim < 0.8

    def test_similarity_empty_abstract(self, analyzer, empty_paper, sample_papers):
        """Test similarity with empty abstract."""
        sim = analyzer.compute_similarity(empty_paper, sample_papers[0])
        assert sim == 0.0

    def test_similarity_symmetric(self, analyzer, sample_papers):
        """Test that similarity is symmetric."""
        sim_ab = analyzer.compute_similarity(sample_papers[0], sample_papers[1])
        sim_ba = analyzer.compute_similarity(sample_papers[1], sample_papers[0])
        assert abs(sim_ab - sim_ba) < 0.001


# ============================================================================
# Unit Tests - Full Analysis Pipeline
# ============================================================================

class TestFullAnalysis:
    """Test the complete analysis pipeline."""

    def test_analyze_paper_basic(self, analyzer, sample_papers):
        """Test full analysis of a single paper."""
        result = analyzer.analyze_paper(sample_papers[0])
        assert isinstance(result, AnalysisResult)
        assert result.paper == sample_papers[0]
        assert len(result.keywords) > 0
        assert len(result.methodology_scores) > 0
        assert result.citation_impact >= 0

    def test_analyze_paper_empty(self, analyzer, empty_paper):
        """Test analysis of empty paper."""
        result = analyzer.analyze_paper(empty_paper)
        assert result.keywords == []
        assert all(score == 0.0 for score in result.methodology_scores.values())
        assert result.citation_impact == 0.0

    def test_analyze_papers_batch(self, analyzer, sample_papers):
        """Test batch analysis of multiple papers."""
        results = analyzer.analyze_papers(sample_papers)
        assert len(results) == len(sample_papers)
        for result in results:
            assert isinstance(result, AnalysisResult)

    def test_analyze_papers_empty_batch(self, analyzer):
        """Test batch analysis with empty list."""
        results = analyzer.analyze_papers([])
        assert results == []

    def test_analyze_papers_consistency(self, analyzer, sample_papers):
        """Test that batch and individual analysis produce same results."""
        batch_results = analyzer.analyze_papers(sample_papers)
        for i, paper in enumerate(sample_papers):
            individual_result = analyzer.analyze_paper(paper)
            assert batch_results[i].keywords == individual_result.keywords
            assert batch_results[i].methodology_scores == individual_result.methodology_scores


# ============================================================================
# Property-Based Tests
# ============================================================================

class TestProperties:
    """Property-based tests for statistical invariants."""

    def test_keyword_uniqueness(self, analyzer, sample_papers):
        """Test that extracted keywords are unique."""
        for paper in sample_papers:
            keywords = analyzer.extract_keywords(paper)
            assert len(keywords) == len(set(keywords))

    def test_classification_invariance(self, analyzer):
        """Test that classification is invariant to text case."""
        paper_upper = PaperMetadata(
            title="TEST",
            authors=["X"],
            abstract="TRANSFORMER ATTENTION DEEP LEARNING",
            year=2024,
            doi="doi",
            citations=100
        )
        paper_lower = PaperMetadata(
            title="test",
            authors=["x"],
            abstract="transformer attention deep learning",
            year=2024,
            doi="doi",
            citations=100
        )
        cat_upper = analyzer.classify_methodology(paper_upper)
        cat_lower = analyzer.classify_methodology(paper_lower)
        for category in cat_upper:
            assert abs(cat_upper[category] - cat_lower[category]) < 0.01

    def test_similarity_triangle_inequality(self, analyzer, sample_papers):
        """Test triangle inequality for similarity metric."""
        if len(sample_papers) >= 3:
            sim_ab = analyzer.compute_similarity(sample_papers[0], sample_papers[1])
            sim_bc = analyzer.compute_similarity(sample_papers[1], sample_papers[2])
            sim_ac = analyzer.compute_similarity(sample_papers[0], sample_papers[2])
            # Triangle inequality: sim_ac >= sim_ab + sim_bc - 1
            assert sim_ac >= sim_ab + sim_bc - 1.0


# ============================================================================
# Error Handling Tests
# ============================================================================

class TestErrorHandling:
    """Test error handling and edge cases."""

    def test_invalid_paper_type(self, analyzer):
        """Test handling of invalid paper type."""
        with pytest.raises(TypeError):
            analyzer.extract_keywords("not a paper")

    def test_none_paper(self, analyzer):
        """Test handling of None paper."""
        with pytest.raises(TypeError):
            analyzer.extract_keywords(None)

    def test_malformed_paper(self, analyzer):
        """Test handling of malformed paper object."""
        class MalformedPaper:
            pass
        with pytest.raises(AttributeError):
            analyzer.extract_keywords(MalformedPaper())

    def test_very_long_abstract(self, analyzer):
        """Test with extremely long abstract."""
        long_text = "machine learning " * 10000
        paper = PaperMetadata(
            title="Long Paper",
            authors=["X"],
            abstract=long_text,
            year=2024,
            doi="doi",
            citations=100
        )
        # Should not raise MemoryError or timeout
        keywords = analyzer.extract_keywords(paper)
        assert len(keywords) > 0

    def test_special_characters_in_doi(self, analyzer):
        """Test with special characters in DOI."""
        paper = PaperMetadata(
            title="Special DOI",
            authors=["X"],
            abstract="test abstract",
            year=2024,
            doi="10.1234/test@#$%^&*()",
            citations=100
        )
        result = analyzer.analyze_paper(paper)
        assert result is not None


# ============================================================================
# Performance Tests
# ============================================================================

class TestPerformance:
    """Performance benchmarks for critical paths."""

    def test_keyword_extraction_speed(self, analyzer, sample_papers, benchmark):
        """Benchmark keyword extraction speed."""
        def extract():
            for paper in sample_papers:
                analyzer.extract_keywords(paper)
        benchmark(extract)

    def test_classification_speed(self, analyzer, sample_papers, benchmark):
        """Benchmark classification speed."""
        def classify():
            for paper in sample_papers:
                analyzer.classify_methodology(paper)
        benchmark(classify)

    def test_batch_analysis_speed(self, analyzer, sample_papers, benchmark):
        """Benchmark batch analysis speed."""
        benchmark(analyzer.analyze_papers, sample_papers)


# ============================================================================
# Integration Tests
# ============================================================================

class TestIntegration:
    """Integration tests with real dependencies."""

    def test_full_pipeline_integration(self, analyzer, sample_papers):
        """Test complete analysis pipeline end-to-end."""
        # Step 1: Extract keywords
        for paper in sample_papers:
            keywords = analyzer.extract_keywords(paper)
            assert len(keywords) > 0

        # Step 2: Classify methodology
        categories = analyzer.classify_methodology(sample_papers[0])
        assert len(categories) > 0

        # Step 3: Analyze citations
        citation_stats = analyzer.analyze_citations(sample_papers)
        assert citation_stats['total_citations'] > 0

        # Step 4: Detect trends
        trends = analyzer.detect_trends(sample_papers)
        assert len(trends['hot_topics']) > 0

        # Step 5: Compute similarities
        similarity_matrix = []
        for i in range(len(sample_papers)):
            row = []
            for j in range(len(sample_papers)):
                sim = analyzer.compute_similarity(sample_papers[i], sample_papers[j])
                row.append(sim)
            similarity_matrix.append(row)
        assert len(similarity_matrix) == len(sample_papers)

    def test_serialization_roundtrip(self, analyzer, sample_papers):
        """Test that analysis results can be serialized."""
        result = analyzer.analyze_paper(sample_papers[0])
        # Convert to dict for JSON serialization
        result_dict = {
            'keywords': result.keywords,
            'methodology_scores': result.methodology_scores,
            'citation_impact': result.citation_impact
        }
        json_str = json.dumps(result_dict)
        loaded = json.loads(json_str)
        assert loaded['keywords'] == result.keywords
        assert loaded['methodology_scores'] == result.methodology_scores
        assert loaded['citation_impact'] == result.citation_impact


# ============================================================================
# Regression Tests
# ============================================================================

class TestRegression:
    """Regression tests for known issues."""

    def test_regression_empty_string_keywords(self, analyzer):
        """Regression: Empty strings should not appear as keywords."""
        paper = PaperMetadata(
            title="Test",
            authors=["X"],
            abstract="   ",  # Only whitespace
            year=2024,
            doi="doi",
            citations=0
        )
        keywords = analyzer.extract_keywords(paper)
        assert all(kw.strip() for kw in keywords)

    def test_regression_negative_citations(self, analyzer):
        """Regression: Negative citations should be handled."""
        paper = PaperMetadata(
            title="Negative",
            authors=["X"],
            abstract="test",
            year=2024,
            doi="doi",
            citations=-5
        )
        result = analyzer.analyze_paper(paper)
        assert result.citation_impact >= 0

    def test_regression_duplicate_papers(self, analyzer):
        """Regression: Duplicate papers should not cause issues."""
        papers = [sample_papers[0], sample_papers[0]]  # Same paper twice
        results = analyzer.analyze_papers(papers)
        assert len(results) == 2
        assert results[0].keywords == results[1].keywords


# ============================================================================
# Main Execution
# ============================================================================

if __name__ == '__main__':
    pytest.main(['-v', '--tb=short', '--cov=paper_analyzer', __file__])