# Generated by Verify (QA Engineer)
import pytest
from exceptions import (
    ContainerSkillError,
    RuntimeNotFoundError,
    ContainerExecutionError,
    ResourceConstraintError
)

class TestContainerSkillExceptions:
    """
    Comprehensive test suite for ContainerSkill exception hierarchy.
    Ensures structural integrity, inheritance, and metadata preservation.
    """

    def test_base_exception_initialization(self):
        """Verify ContainerSkillError stores message and original exception correctly."""
        msg = "Base system failure"
        original = ValueError("Root cause")
        
        exc = ContainerSkillError(msg, original_exception=original)
        
        assert str(exc) == msg
        assert exc.original_exception == original
        assert isinstance(exc, Exception)

    def test_exception_hierarchy(self):
        """Verify that all specialized exceptions inherit from ContainerSkillError."""
        specialized_exceptions = [
            RuntimeNotFoundError("Runtime missing"),
            ContainerExecutionError("Execution failed"),
            ResourceConstraintError("Insufficient RAM")
        ]
        
        for exc in specialized_exceptions:
            assert isinstance(exc, ContainerSkillError), f"{type(exc).__name__} should inherit from ContainerSkillError"
            assert isinstance(exc, Exception), f"{type(exc).__name__} should inherit from Exception"

    @pytest.mark.parametrize("exception_class, message", [
        (RuntimeNotFoundError, "No Docker/Podman detected"),
        (ContainerExecutionError, "Container exited with code 137"),
        (ResourceConstraintError, "CPU limit exceeded"),
    ])
    def test_specialized_exception_messages(self, exception_class, message):
        """Verify that specialized exceptions correctly propagate the error message."""
        exc = exception_class(message)
        assert str(exc) == message

    def test_exception_wrapping_causality(self):
        """
        Test the 'original_exception' pattern to ensure that the root cause 
        is preserved when wrapping a lower-level system error.
        """
        try:
            # Simulate a low-level OS error
            raise FileNotFoundError("config.json not found")
        except FileNotFoundError as e:
            # Wrap it in a domain-specific exception
            wrapped_exc = RuntimeNotFoundError("Failed to initialize runtime due to missing config", original_exception=e)
        
        assert isinstance(wrapped_exc, RuntimeNotFoundError)
        assert isinstance(wrapped_exc.original_exception, FileNotFoundError)
        assert "config.json not found" in str(wrapped_exc.original_exception)

    def test_catch_all_base_class(self):
        """Verify that catching ContainerSkillError catches all its descendants."""
        with pytest.raises(ContainerSkillError):
            raise ResourceConstraintError("Out of memory")

    def test_optional_original_exception(self):
        """Ensure that original_exception is Optional and defaults to None."""
        exc = ContainerExecutionError("Generic failure")
        assert exc.original_exception is None

    def test_type_isolation(self):
        """Ensure that different specialized exceptions do not cross-trigger."""
        with pytest.raises(RuntimeNotFoundError):
            try:
                raise ResourceConstraintError("Memory limit")
            except ResourceConstraintError:
                # Re-raising as a different type to test isolation
                raise RuntimeNotFoundError("Wrong type")
        
        # Verify that a ResourceConstraintError is NOT a RuntimeNotFoundError
        exc = ResourceConstraintError("Limit")
        assert not isinstance(exc, RuntimeNotFoundError)