# Generated by Verify (QA Engineer)
import pytest
import json
from typing import Dict, Any

# The architectural specification to be validated
ARCH_SPEC_JSON = """
{
  "component": "DiagramSkill",
  "layers": {
    "api_gateway": "REST/gRPC Interface",
    "processing_core": {
      "parser": "NLP-based Entity Extractor",
      "mapper": "Semantic Logic Engine",
      "generator": "DSL Template Engine"
    },
    "validation_layer": "Grammar-based Linter",
    "output_adapter": "Multi-format Formatter"
  },
  "dependencies": {
    "nlp_engine": "Transformer-based NER",
    "dsl_specs": ["Mermaid.js", "PlantUML", "Graphviz"]
  }
}
"""

@pytest.fixture
def arch_data() -> Dict[str, Any]:
    """Provides the parsed architectural specification."""
    return json.loads(ARCH_SPEC_JSON)

class TestDiagramSkillArchitecture:
    """
    Precision Reliability Suite for DiagramSkill Architectural Specification.
    Ensures structural coherence and dependency alignment.
    """

    def test_root_component_identity(self, arch_data):
        """Verify the component is correctly identified as DiagramSkill."""
        assert arch_data.get("component") == "DiagramSkill", "Component identity mismatch."

    def test_layer_completeness(self, arch_data):
        """Ensure all critical architectural layers are defined."""
        required_layers = {"api_gateway", "processing_core", "validation_layer", "output_adapter"}
        actual_layers = set(arch_data.get("layers", {}).keys())
        
        missing = required_layers - actual_layers
        assert not missing, f"Architectural layers missing: {missing}"

    def test_processing_core_internals(self, arch_data):
        """Validate the internal composition of the processing_core."""
        core = arch_data.get("layers", {}).get("processing_core", {})
        required_modules = {"parser", "mapper", "generator"}
        
        for module in required_modules:
            assert module in core, f"Processing core missing critical module: {module}"
            assert isinstance(core[module], str), f"Module {module} must have a descriptive definition."

    def test_dependency_resolution(self, arch_data):
        """Verify that the NLP engine and DSL specifications are correctly mapped."""
        deps = arch_data.get("dependencies", {})
        
        # Validate NLP Engine
        assert "nlp_engine" in deps, "NLP Engine dependency is missing."
        assert "Transformer" in deps["nlp_engine"], "NLP Engine must be Transformer-based for state-of-the-art NER."
        
        # Validate DSL Specifications
        dsl_specs = deps.get("dsl_specs", [])
        expected_dsls = {"Mermaid.js", "PlantUML", "Graphviz"}
        assert set(dsl_specs) == expected_dsls, f"DSL specifications mismatch. Expected {expected_dsls}, got {set(dsl_specs)}"

    @pytest.mark.parametrize("layer_key", ["api_gateway", "validation_layer", "output_adapter"])
    def test_layer_definition_type(self, arch_data, layer_key):
        """Ensure top-level layers are defined as strings (descriptions)."""
        layer_val = arch_data.get("layers", {}).get(layer_key)
        assert isinstance(layer_val, str), f"Layer {layer_key} must be a string description."

    def test_architectural_robustness_constraints(self, arch_data):
        """
        Chaos-style check: Ensure no empty definitions exist in the architecture.
        """
        def recursive_check(obj):
            if isinstance(obj, dict):
                for k, v in obj.items():
                    assert k != "", "Empty keys are not permitted in architectural specs."
                    recursive_check(v)
            elif isinstance(obj, list):
                for item in obj:
                    recursive_check(item)
            elif isinstance(obj, str):
                assert len(obj.strip()) > 0, "Empty string definitions are not permitted."

        recursive_check(arch_data)

if __name__ == "__main__":
    pytest.main([__file__])