# Generated by Verify (QA Engineer)
import pytest
import math
from math_solver import MathSolver, SolverMode, SyntaxErrorMesh, DomainErrorMesh

@pytest.fixture
def solver():
    """Provides a fresh instance of MathSolver for each test."""
    return MathSolver()

class TestMathSolverSymbolic:
    """Validation suite for Symbolic CAS operations."""

    def test_symbolic_simplification(self, solver):
        payload = {
            "expression": "(x**2 + 2*x + 1)",
            "mode": "SYMBOLIC"
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert "result" in response
        # (x+1)**2 is the simplified form
        assert "(x + 1)**2" in response["result"]["exact"]
        assert response["metadata"]["method_used"] == "SymbolicCAS"

    def test_symbolic_integration(self, solver):
        payload = {
            "expression": "integrate(x**2, x)",
            "mode": "SYMBOLIC"
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert "x**3/3" in response["result"]["exact"]
        assert any("Integration" in step for step in response["metadata"]["steps"])

    def test_symbolic_syntax_error(self, solver):
        payload = {
            "expression": "invalid(syntax @ a)",
            "mode": "SYMBOLIC"
        }
        response = solver.execute(payload)
        assert response["status"] == "ERROR"
        assert response["error_code"] == "ERR_001"

class TestMathSolverNumerical:
    """Validation suite for High-Precision Numerical operations."""

    def test_numerical_evaluation_with_vars(self, solver):
        payload = {
            "expression": "x**2 + 10",
            "mode": "NUMERICAL",
            "variables": {"x": 5},
            "precision": 15
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert response["result"]["approximate"] == 35.0
        assert response["metadata"]["method_used"] == "IterativeNumerical"

    def test_numerical_precision(self, solver):
        # Testing pi to high precision
        payload = {
            "expression": "pi",
            "mode": "NUMERICAL",
            "precision": 50
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        # Verify it's close to math.pi but handles high precision internally
        assert math.isclose(response["result"]["approximate"], math.pi, rel_tol=1e-15)

    def test_numerical_domain_error(self, solver):
        payload = {
            "expression": "1/0",
            "mode": "NUMERICAL"
        }
        response = solver.execute(payload)
        assert response["status"] == "ERROR"
        assert response["error_code"] == "ERR_002"

class TestMathSolverAutoMode:
    """Validation suite for Heuristic Dispatching (AUTO mode)."""

    def test_auto_symbolic_success(self, solver):
        payload = {
            "expression": "x + x",
            "mode": "AUTO"
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert "2*x" in response["result"]["exact"]
        assert "Symbolic" in response["metadata"]["method_used"]

    def test_auto_fallback_to_numerical(self, solver):
        # Force a scenario where symbolic might be complex but numerical is straightforward
        # Note: In the provided implementation, DomainErrorMesh triggers fallback
        payload = {
            "expression": "log(-1)", 
            "mode": "AUTO",
            "variables": {}
        }
        # Since log(-1) is complex, SymbolicEngine might raise DomainErrorMesh 
        # depending on sympy's current state, triggering numerical fallback.
        response = solver.execute(payload)
        # If it falls back to numerical and fails there too, it returns ERROR
        # But we check that the logic attempted the transition
        if response["status"] == "SUCCESS":
            assert "Numerical" in response["metadata"]["method_used"]

class TestMathSolverEdgeCases:
    """Stress tests and boundary condition validation."""

    def test_missing_expression(self, solver):
        payload = {"mode": "SYMBOLIC"}
        response = solver.execute(payload)
        assert response["status"] == "ERROR"
        assert response["error_code"] == "ERR_001"

    def test_empty_variables(self, solver):
        payload = {
            "expression": "5 * 5",
            "mode": "NUMERICAL",
            "variables": {}
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert response["result"]["approximate"] == 25.0

    def test_complex_nested_expression(self, solver):
        payload = {
            "expression": "sin(x)**2 + cos(x)**2",
            "mode": "SYMBOLIC"
        }
        response = solver.execute(payload)
        assert response["status"] == "SUCCESS"
        assert response["result"]["exact"] == "1"

    def test_unsupported_mode(self, solver):
        with pytest.raises(ValueError):
            # This tests the Enum conversion in the execute method
            solver.execute({"expression": "1+1", "mode": "INVALID_MODE"})