# Generated by Verify (QA Engineer)
"""
Comprehensive Test Suite for Swarm OS Authentication Module

Tests JWT-based stateless authentication, token generation, verification,
middleware integration, and edge cases for agent identity verification.
"""

import pytest
import jwt
import time
from datetime import datetime, timedelta
from unittest.mock import Mock, patch, MagicMock
from freezegun import freeze_time

from swarm_security.auth import (
    AuthManager,
    AgentIdentity,
    AuthenticationError,
    SECRET_KEY,
    ALGORITHM,
    ACCESS_TOKEN_EXPIRE_MINUTES
)


# =============================================================================
# Fixtures
# =============================================================================

@pytest.fixture
def auth_manager():
    """Create a fresh AuthManager instance for each test."""
    return AuthManager()


@pytest.fixture
def valid_agent_data():
    """Standard agent data for testing."""
    return {
        "agent_id": "agent-001",
        "role": "worker",
        "permissions": ["read", "write", "execute"]
    }


@pytest.fixture
def valid_token(auth_manager, valid_agent_data):
    """Generate a valid token for testing."""
    return auth_manager.generate_token(
        agent_id=valid_agent_data["agent_id"],
        role=valid_agent_data["role"],
        permissions=valid_agent_data["permissions"]
    )


@pytest.fixture
def expired_token(auth_manager, valid_agent_data):
    """Generate an expired token for testing."""
    with freeze_time(datetime.utcnow() - timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES + 1)):
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )
    return token


@pytest.fixture
def tampered_token(valid_token):
    """Create a tampered token by modifying the payload."""
    parts = valid_token.split('.')
    # Corrupt the payload section
    parts[1] = parts[1][:-1] + 'Z' if parts[1][-1] != 'Z' else parts[1][:-1] + 'Y'
    return '.'.join(parts)


# =============================================================================
# AuthManager Initialization Tests
# =============================================================================

class TestAuthManagerInitialization:
    """Verify AuthManager initializes with correct configuration."""

    def test_default_initialization(self, auth_manager):
        """Should initialize with default configuration."""
        assert auth_manager is not None
        assert auth_manager.secret_key == SECRET_KEY
        assert auth_manager.algorithm == ALGORITHM
        assert auth_manager.expire_minutes == ACCESS_TOKEN_EXPIRE_MINUTES

    def test_custom_configuration(self):
        """Should accept custom configuration parameters."""
        custom_key = "custom-secret-key"
        custom_algorithm = "HS512"
        custom_expiry = 60

        manager = AuthManager(
            secret_key=custom_key,
            algorithm=custom_algorithm,
            expire_minutes=custom_expiry
        )

        assert manager.secret_key == custom_key
        assert manager.algorithm == custom_algorithm
        assert manager.expire_minutes == custom_expiry

    def test_empty_secret_key_raises_error(self):
        """Should raise error if secret key is empty."""
        with pytest.raises(ValueError, match="Secret key cannot be empty"):
            AuthManager(secret_key="")

    def test_invalid_expiry_raises_error(self):
        """Should raise error if expiry is not positive."""
        with pytest.raises(ValueError, match="Expire minutes must be positive"):
            AuthManager(expire_minutes=0)

        with pytest.raises(ValueError, match="Expire minutes must be positive"):
            AuthManager(expire_minutes=-5)


# =============================================================================
# Token Generation Tests
# =============================================================================

class TestTokenGeneration:
    """Verify token generation produces valid JWT tokens."""

    def test_generate_token_success(self, auth_manager, valid_agent_data):
        """Should generate a valid JWT token."""
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        assert token is not None
        assert isinstance(token, str)
        assert len(token.split('.')) == 3  # JWT has 3 parts

    def test_generated_token_contains_correct_payload(self, auth_manager, valid_agent_data):
        """Should encode correct agent data in token payload."""
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])

        assert payload["agent_id"] == valid_agent_data["agent_id"]
        assert payload["role"] == valid_agent_data["role"]
        assert payload["permissions"] == valid_agent_data["permissions"]

    def test_token_has_expiry_claim(self, auth_manager, valid_agent_data):
        """Should include expiration claim in token."""
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        assert "exp" in payload

    def test_token_expiry_is_correct_duration(self, auth_manager, valid_agent_data):
        """Should set correct expiration time."""
        with freeze_time("2024-01-01 12:00:00") as frozen_time:
            token = auth_manager.generate_token(
                agent_id=valid_agent_data["agent_id"],
                role=valid_agent_data["role"],
                permissions=valid_agent_data["permissions"]
            )

            payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
            expected_expiry = datetime(2024, 1, 1, 12, 30, 0)  # 30 minutes later
            actual_expiry = datetime.fromtimestamp(payload["exp"])

            assert actual_expiry == expected_expiry

    def test_token_has_issued_at_claim(self, auth_manager, valid_agent_data):
        """Should include issued-at claim."""
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        assert "iat" in payload

    def test_token_has_jti_claim(self, auth_manager, valid_agent_data):
        """Should include unique JWT ID claim."""
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        assert "jti" in payload
        assert isinstance(payload["jti"], str)
        assert len(payload["jti"]) > 0

    def test_generated_tokens_are_unique(self, auth_manager, valid_agent_data):
        """Should generate unique tokens for same data."""
        token1 = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )
        token2 = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        assert token1 != token2

    def test_generate_token_with_empty_permissions(self, auth_manager):
        """Should handle empty permissions list."""
        token = auth_manager.generate_token(
            agent_id="agent-001",
            role="viewer",
            permissions=[]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        assert payload["permissions"] == []

    def test_generate_token_with_special_characters(self, auth_manager):
        """Should handle special characters in agent data."""
        token = auth_manager.generate_token(
            agent_id="agent-@#$%",
            role="admin-role_123",
            permissions=["read:all", "write:system"]
        )

        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        assert payload["agent_id"] == "agent-@#$%"
        assert payload["role"] == "admin-role_123"


# =============================================================================
# Token Verification Tests
# =============================================================================

class TestTokenVerification:
    """Verify token verification correctly validates tokens."""

    def test_verify_valid_token(self, auth_manager, valid_token):
        """Should successfully verify a valid token."""
        identity = auth_manager.verify_token(valid_token)

        assert identity is not None
        assert isinstance(identity, AgentIdentity)

    def test_verify_token_returns_correct_identity(self, auth_manager, valid_token, valid_agent_data):
        """Should return correct agent identity from valid token."""
        identity = auth_manager.verify_token(valid_token)

        assert identity.agent_id == valid_agent_data["agent_id"]
        assert identity.role == valid_agent_data["role"]
        assert identity.permissions == valid_agent_data["permissions"]

    def test_verify_expired_token_raises_error(self, auth_manager, expired_token):
        """Should raise AuthenticationError for expired token."""
        with pytest.raises(AuthenticationError) as exc_info:
            auth_manager.verify_token(expired_token)

        assert "expired" in str(exc_info.value).lower() or "expired" in exc_info.value.code.lower()

    def test_verify_tampered_token_raises_error(self, auth_manager, tampered_token):
        """Should raise AuthenticationError for tampered token."""
        with pytest.raises(AuthenticationError) as exc_info:
            auth_manager.verify_token(tampered_token)

        assert "invalid" in str(exc_info.value).lower() or "invalid" in exc_info.value.code.lower()

    def test_verify_malformed_token_raises_error(self, auth_manager):
        """Should raise AuthenticationError for malformed token."""
        malformed_tokens = [
            "",
            "not-a-token",
            "header.payload",
            "a.b.c.d",  # too many parts
            "a.b"  # too few parts
        ]

        for token in malformed_tokens:
            with pytest.raises(AuthenticationError):
                auth_manager.verify_token(token)

    def test_verify_token_with_wrong_secret(self, auth_manager, valid_token):
        """Should raise error if token signed with different secret."""
        different_manager = AuthManager(secret_key="different-secret-key")

        with pytest.raises(AuthenticationError):
            different_manager.verify_token(valid_token)

    def test_verify_token_with_wrong_algorithm(self, auth_manager, valid_agent_data):
        """Should raise error if token uses different algorithm."""
        # Create token with different algorithm
        token = jwt.encode(
            {
                "agent_id": valid_agent_data["agent_id"],
                "role": valid_agent_data["role"],
                "permissions": valid_agent_data["permissions"],
                "exp": datetime.utcnow() + timedelta(minutes=30)
            },
            SECRET_KEY,
            algorithm="HS512"
        )

        with pytest.raises(AuthenticationError):
            auth_manager.verify_token(token)

    def test_verify_token_sets_authenticated_at(self, auth_manager, valid_token):
        """Should set authenticated_at timestamp on identity."""
        with freeze_time("2024-01-01 12:00:00"):
            identity = auth_manager.verify_token(valid_token)

            assert identity.authenticated_at == datetime(2024, 1, 1, 12, 0, 0)


# =============================================================================
# AgentIdentity Tests
# =============================================================================

class TestAgentIdentity:
    """Verify AgentIdentity class behavior."""

    def test_agent_identity_creation(self):
        """Should create agent identity with correct attributes."""
        identity = AgentIdentity(
            agent_id="agent-001",
            role="worker",
            permissions=["read", "write"]
        )

        assert identity.agent_id == "agent-001"
        assert identity.role == "worker"
        assert identity.permissions == ["read", "write"]
        assert identity.authenticated_at is not None

    def test_agent_identity_to_dict(self):
        """Should convert identity to dictionary correctly."""
        with freeze_time("2024-01-01 12:00:00"):
            identity = AgentIdentity(
                agent_id="agent-001",
                role="worker",
                permissions=["read", "write"]
            )

            result = identity.to_dict()

            assert result["agent_id"] == "agent-001"
            assert result["role"] == "worker"
            assert result["permissions"] == ["read", "write"]
            assert result["authenticated_at"] == "2024-01-01T12:00:00"

    def test_agent_identity_immutable_permissions(self):
        """Should not allow modification of permissions through to_dict."""
        identity = AgentIdentity(
            agent_id="agent-001",
            role="worker",
            permissions=["read", "write"]
        )

        result = identity.to_dict()
        result["permissions"].append("delete")

        assert "delete" not in identity.permissions


# =============================================================================
# Decorator/Middleware Tests
# =============================================================================

class TestAuthDecorator:
    """Verify the authentication decorator works correctly."""

    def test_decorator_authenticates_request(self, auth_manager, valid_token):
        """Should authenticate request with valid token."""
        mock_request = MagicMock()
        mock_request.headers = {"Authorization": f"Bearer {valid_token}"}

        @auth_manager.require_auth
        def protected_endpoint(request):
            return {"status": "success", "agent": request.agent.agent_id}

        result = protected_endpoint(mock_request)
        assert result["status"] == "success"
        assert result["agent"] == "agent-001"

    def test_decorator_rejects_missing_token(self, auth_manager):
        """Should reject request without token."""
        mock_request = MagicMock()
        mock_request.headers = {}

        @auth_manager.require_auth
        def protected_endpoint(request):
            return {"status": "success"}

        with pytest.raises(AuthenticationError):
            protected_endpoint(mock_request)

    def test_decorator_rejects_invalid_token(self, auth_manager):
        """Should reject request with invalid token."""
        mock_request = MagicMock()
        mock_request.headers = {"Authorization": "Bearer invalid-token"}

        @auth_manager.require_auth
        def protected_endpoint(request):
            return {"status": "success"}

        with pytest.raises(AuthenticationError):
            protected_endpoint(mock_request)

    def test_decorator_rejects_expired_token(self, auth_manager, expired_token):
        """Should reject request with expired token."""
        mock_request = MagicMock()
        mock_request.headers = {"Authorization": f"Bearer {expired_token}"}

        @auth_manager.require_auth
        def protected_endpoint(request):
            return {"status": "success"}

        with pytest.raises(AuthenticationError):
            protected_endpoint(mock_request)

    def test_decorator_passes_agent_to_request(self, auth_manager, valid_token):
        """Should attach agent identity to request object."""
        mock_request = MagicMock()
        mock_request.headers = {"Authorization": f"Bearer {valid_token}"}

        @auth_manager.require_auth
        def protected_endpoint(request):
            assert hasattr(request, 'agent')
            assert isinstance(request.agent, AgentIdentity)
            return {"status": "success"}

        result = protected_endpoint(mock_request)
        assert result["status"] == "success"

    def test_decorator_supports_custom_token_extraction(self, auth_manager, valid_token):
        """Should support custom token extraction function."""
        mock_request = MagicMock()
        mock_request.custom_header = valid_token

        def custom_extractor(request):
            return request.custom_header

        @auth_manager.require_auth(token_extractor=custom_extractor)
        def protected_endpoint(request):
            return {"status": "success", "agent": request.agent.agent_id}

        result = protected_endpoint(mock_request)
        assert result["status"] == "success"


# =============================================================================
# Edge Cases and Error Handling Tests
# =============================================================================

class TestEdgeCases:
    """Verify handling of edge cases and error conditions."""

    def test_concurrent_token_verification(self, auth_manager, valid_token):
        """Should handle concurrent token verification."""
        import concurrent.futures

        def verify_token():
            identity = auth_manager.verify_token(valid_token)
            return identity.agent_id

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            futures = [executor.submit(verify_token) for _ in range(20)]
            results = [f.result() for f in concurrent.futures.as_completed(futures)]

        assert all(result == "agent-001" for result in results)

    def test_token_with_additional_claims(self, auth_manager):
        """Should handle tokens with additional custom claims."""
        additional_claims = {
            "department": "engineering",
            "level": 5,
            "features": ["feature_a", "feature_b"]
        }

        token = auth_manager.generate_token(
            agent_id="agent-001",
            role="worker",
            permissions=["read"],
            **additional_claims
        )

        identity = auth_manager.verify_token(token)
        assert identity.agent_id == "agent-001"

    def test_verify_token_with_none(self, auth_manager):
        """Should raise error for None token."""
        with pytest.raises(AuthenticationError):
            auth_manager.verify_token(None)

    def test_generate_token_with_none_values(self, auth_manager):
        """Should handle None values in token generation."""
        with pytest.raises(ValueError):
            auth_manager.generate_token(
                agent_id=None,
                role="worker",
                permissions=["read"]
            )

    def test_token_replay_attack_detection(self, auth_manager, valid_token):
        """Should detect token replay within expiry window."""
        # Verify same token multiple times
        for _ in range(5):
            identity = auth_manager.verify_token(valid_token)
            assert identity.agent_id == "agent-001"

    def test_very_long_permissions_list(self, auth_manager):
        """Should handle very long permissions list."""
        permissions = [f"perm_{i}" for i in range(1000)]
        token = auth_manager.generate_token(
            agent_id="agent-001",
            role="admin",
            permissions=permissions
        )

        identity = auth_manager.verify_token(token)
        assert len(identity.permissions) == 1000


# =============================================================================
# Performance Tests
# =============================================================================

class TestPerformance:
    """Verify authentication performance meets requirements."""

    def test_token_generation_performance(self, auth_manager, valid_agent_data):
        """Should generate token within acceptable time."""
        import time

        start_time = time.time()
        for _ in range(100):
            auth_manager.generate_token(
                agent_id=valid_agent_data["agent_id"],
                role=valid_agent_data["role"],
                permissions=valid_agent_data["permissions"]
            )
        elapsed = time.time() - start_time

        # Should generate 100 tokens in less than 1 second
        assert elapsed < 1.0, f"Token generation too slow: {elapsed:.2f}s"

    def test_token_verification_performance(self, auth_manager, valid_token):
        """Should verify token within acceptable time."""
        import time

        start_time = time.time()
        for _ in range(100):
            auth_manager.verify_token(valid_token)
        elapsed = time.time() - start_time

        # Should verify 100 tokens in less than 1 second
        assert elapsed < 1.0, f"Token verification too slow: {elapsed:.2f}s"


# =============================================================================
# Integration Tests
# =============================================================================

class TestIntegration:
    """Verify end-to-end authentication flow."""

    def test_full_authentication_flow(self, auth_manager, valid_agent_data):
        """Should complete full authentication flow successfully."""
        # Generate token
        token = auth_manager.generate_token(
            agent_id=valid_agent_data["agent_id"],
            role=valid_agent_data["role"],
            permissions=valid_agent_data["permissions"]
        )

        # Verify token
        identity = auth_manager.verify_token(token)

        # Use identity
        assert identity.agent_id == valid_agent_data["agent_id"]
        assert identity.role == valid_agent_data["role"]
        assert identity.permissions == valid_agent_data["permissions"]

        # Convert to dict for serialization
        identity_dict = identity.to_dict()
        assert identity_dict["agent_id"] == valid_agent_data["agent_id"]

    def test_multiple_agents_authentication(self, auth_manager):
        """Should handle multiple agents authenticating simultaneously."""
        agents = [
            {"agent_id": "agent-001", "role": "worker", "permissions": ["read"]},
            {"agent_id": "agent-002", "role": "admin", "permissions": ["read", "write", "delete"]},
            {"agent_id": "agent-003", "role": "viewer", "permissions": ["read"]}
        ]

        tokens = []
        for agent in agents:
            token = auth_manager.generate_token(**agent)
            tokens.append(token)

        # Verify all tokens
        for token, agent in zip(tokens, agents):
            identity = auth_manager.verify_token(token)
            assert identity.agent_id == agent["agent_id"]
            assert identity.role == agent["role"]
            assert identity.permissions == agent["permissions"]


# =============================================================================
# Security Tests
# =============================================================================

class TestSecurity:
    """Verify security properties of authentication system."""

    def test_token_does_not_expose_secret(self, auth_manager, valid_token):
        """Should not expose secret key in token."""
        assert SECRET_KEY not in valid_token

    def test_token_does_not_expose_algorithm(self, auth_manager, valid_token):
        """Should not expose algorithm in token payload."""
        payload_encoded = valid_token.split('.')[1]
        import base64
        # Add padding if necessary
        payload_encoded += '=' * (4 - len(payload_encoded) % 4)
        payload_decoded = base64.urlsafe_b64decode(payload_encoded).decode('utf-8')
        assert ALGORITHM not in payload_decoded

    def test_jwt_not_vulnerable_to_none_algorithm(self, auth_manager, valid_agent_data):
        """Should reject tokens with 'none' algorithm."""
        # Create token with 'none' algorithm
        import json
        import base64

        header = base64.urlsafe_b64encode(json.dumps({"alg": "none", "typ": "JWT"}).encode()).decode().rstrip('=')
        payload = base64.urlsafe_b64encode(json.dumps({
            "agent_id": valid_agent_data["agent_id"],
            "role": valid_agent_data["role"],
            "permissions": valid_agent_data["permissions"],
            "exp": (datetime.utcnow() + timedelta(minutes=30)).timestamp()
        }).encode()).decode().rstrip('=')

        none_token = f"{header}.{payload}."

        with pytest.raises(AuthenticationError):
            auth_manager.verify_token(none_token)


# =============================================================================
# Configuration Tests
# =============================================================================

class TestConfiguration:
    """Verify configuration handling."""

    def test_environment_variable_secret_key(self):
        """Should load secret key from environment variable."""
        import os
        test_key = "env-test-key-12345"
        os.environ["SWARM_SECRET_KEY"] = test_key

        manager = AuthManager()
        assert manager.secret_key == test_key

        # Cleanup
        del os.environ["SWARM_SECRET_KEY"]

    def test_configuration_override_priority(self):
        """Should prioritize explicit configuration over environment."""
        import os
        os.environ["SWARM_SECRET_KEY"] = "env-key"

        manager = AuthManager(secret_key="explicit-key")
        assert manager.secret_key == "explicit-key"

        # Cleanup
        del os.environ["SWARM_SECRET_KEY"]


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])