# Generated by Verify (QA Engineer)
"""
Comprehensive pytest test suite for swarm_security.validator module.

Tests cover:
- ValidationError custom exception behavior
- AgentCommand schema: field constraints, regex patterns, defaults
- AgentData schema: content_type pattern, data union types, encoding, checksum
- ConfigurationSchema: field constraints, nested validation
- Edge cases: empty strings, invalid patterns, boundary values, type coercion
"""

import pytest
from datetime import datetime
from typing import Dict, Any
from pydantic import ValidationError as PydanticValidationError

from swarm_security.validator import (
    ValidationError,
    AgentCommand,
    AgentData,
    ConfigurationSchema,
)


# ---------------------------------------------------------------------------
# ValidationError Tests
# ---------------------------------------------------------------------------

class TestValidationError:
    """Test the custom ValidationError exception."""

    def test_basic_instantiation(self):
        """Test basic exception creation with just a message."""
        err = ValidationError("test error")
        assert err.message == "test error"
        assert err.errors == {}
        assert str(err) == "test error"

    def test_with_errors_dict(self):
        """Test exception with detailed error dictionary."""
        errors = {"field1": "must not be empty", "field2": "invalid type"}
        err = ValidationError("validation failed", errors=errors)
        assert err.message == "validation failed"
        assert err.errors == errors
        assert str(err) == "validation failed"

    def test_empty_errors_default(self):
        """Test that errors defaults to empty dict when not provided."""
        err = ValidationError("msg")
        assert err.errors == {}

    def test_inherits_from_exception(self):
        """Test that ValidationError is a proper Exception subclass."""
        err = ValidationError("msg")
        assert isinstance(err, Exception)
        assert isinstance(err, ValidationError)


# ---------------------------------------------------------------------------
# AgentCommand Tests
# ---------------------------------------------------------------------------

class TestAgentCommand:
    """Test AgentCommand schema validation."""

    # --- Valid Cases ---

    def test_valid_minimal(self):
        """Test creation with only required fields."""
        cmd = AgentCommand(action="deploy", target="node-1")
        assert cmd.action == "deploy"
        assert cmd.target == "node-1"
        assert cmd.payload is None
        assert isinstance(cmd.timestamp, datetime)
        assert cmd.priority == 0

    def test_valid_with_all_fields(self):
        """Test creation with all optional fields provided."""
        ts = datetime(2025, 1, 15, 10, 30, 0)
        cmd = AgentCommand(
            action="scale.up",
            target="cluster-alpha",
            payload={"replicas": 5},
            timestamp=ts,
            priority=50,
        )
        assert cmd.action == "scale.up"
        assert cmd.target == "cluster-alpha"
        assert cmd.payload == {"replicas": 5}
        assert cmd.timestamp == ts
        assert cmd.priority == 50

    def test_valid_action_patterns(self):
        """Test various valid action patterns."""
        valid_actions = [
            "deploy",
            "scale.up",
            "rollback_v2",
            "health-check",
            "config.set",
            "a" * 256,  # max length
        ]
        for action in valid_actions:
            cmd = AgentCommand(action=action, target="t")
            assert cmd.action == action

    def test_valid_target_lengths(self):
        """Test target field at boundary lengths."""
        cmd = AgentCommand(action="test", target="x")
        assert cmd.target == "x"

        long_target = "x" * 128
        cmd = AgentCommand(action="test", target=long_target)
        assert cmd.target == long_target

    def test_valid_priority_boundaries(self):
        """Test priority at min and max values."""
        cmd = AgentCommand(action="test", target="t", priority=0)
        assert cmd.priority == 0

        cmd = AgentCommand(action="test", target="t", priority=100)
        assert cmd.priority == 100

    def test_timestamp_defaults_to_now(self):
        """Test that timestamp defaults to current UTC time."""
        before = datetime.utcnow()
        cmd = AgentCommand(action="test", target="t")
        after = datetime.utcnow()
        assert before <= cmd.timestamp <= after

    def test_payload_none_default(self):
        """Test that payload defaults to None."""
        cmd = AgentCommand(action="test", target="t")
        assert cmd.payload is None

    def test_payload_with_dict(self):
        """Test payload accepts arbitrary dict."""
        cmd = AgentCommand(
            action="test",
            target="t",
            payload={"key": "value", "nested": {"a": 1}},
        )
        assert cmd.payload == {"key": "value", "nested": {"a": 1}}

    # --- Invalid Cases ---

    def test_invalid_action_empty(self):
        """Test that empty action raises validation error."""
        with pytest.raises(PydanticValidationError) as exc_info:
            AgentCommand(action="", target="t")
        errors = exc_info.value.errors()
        assert any(e["loc"] == ("action",) for e in errors)

    def test_invalid_action_too_long(self):
        """Test that action exceeding max length raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="x" * 257, target="t")

    def test_invalid_action_pattern(self):
        """Test that action with invalid characters raises error."""
        invalid_actions = [
            "deploy!",      # exclamation
            "scale up",     # space
            "cmd@host",     # @
            "test#1",       # #
            "a/b",          # slash
            "a\\b",         # backslash
        ]
        for action in invalid_actions:
            with pytest.raises(PydanticValidationError):
                AgentCommand(action=action, target="t")

    def test_invalid_target_empty(self):
        """Test that empty target raises validation error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="")

    def test_invalid_target_too_long(self):
        """Test that target exceeding max length raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="x" * 129)

    def test_invalid_priority_negative(self):
        """Test that negative priority raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="t", priority=-1)

    def test_invalid_priority_too_high(self):
        """Test that priority > 100 raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="t", priority=101)

    def test_invalid_priority_float(self):
        """Test that float priority is rejected (must be int)."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="t", priority=50.5)

    def test_invalid_timestamp_type(self):
        """Test that non-datetime timestamp raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="t", timestamp="2025-01-01")

    def test_invalid_payload_type(self):
        """Test that non-dict payload raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test", target="t", payload="not_a_dict")

    def test_missing_required_fields(self):
        """Test that missing required fields raises error."""
        with pytest.raises(PydanticValidationError):
            AgentCommand()  # missing action and target

        with pytest.raises(PydanticValidationError):
            AgentCommand(action="test")  # missing target

        with pytest.raises(PydanticValidationError):
            AgentCommand(target="test")  # missing action


# ---------------------------------------------------------------------------
# AgentData Tests
# ---------------------------------------------------------------------------

class TestAgentData:
    """Test AgentData schema validation."""

    # --- Valid Cases ---

    def test_valid_string_data(self):
        """Test creation with string data."""
        data = AgentData(content_type="text/plain", data="hello world")
        assert data.content_type == "text/plain"
        assert data.data == "hello world"
        assert data.encoding is None
        assert data.checksum is None

    def test_valid_bytes_data(self):
        """Test creation with bytes data."""
        data = AgentData(content_type="application/octet-stream", data=b"\x00\x01\x02")
        assert data.data == b"\x00\x01\x02"

    def test_valid_dict_data(self):
        """Test creation with dict data."""
        payload = {"key": "value", "num": 42}
        data = AgentData(content_type="application/json", data=payload)
        assert data.data == payload

    def test_valid_with_encoding(self):
        """Test creation with valid encoding."""
        data = AgentData(
            content_type="text/plain",
            data="hello",
            encoding="utf-8",
        )
        assert data.encoding == "utf-8"

    def test_valid_with_checksum(self):
        """Test creation with valid checksum."""
        data = AgentData(
            content_type="text/plain",
            data="hello",
            checksum="a" * 32,
        )
        assert data.checksum == "a" * 32

    def test_valid_content_type_patterns(self):
        """Test various valid content-type patterns."""
        valid_types = [
            "text/plain",
            "application/json",
            "image/png",
            "application/vnd.api+json",
            "text/html; charset=utf-8",  # Note: pattern allows this
        ]
        for ct in valid_types:
            data = AgentData(content_type=ct, data="test")
            assert data.content_type == ct

    def test_valid_encoding_values(self):
        """Test all valid encoding values."""
        for enc in ["utf-8", "base64", "hex"]:
            data = AgentData(
                content_type="text/plain",
                data="test",
                encoding=enc,
            )
            assert data.encoding == enc

    def test_valid_checksum_lengths(self):
        """Test checksum at boundary lengths."""
        data = AgentData(
            content_type="text/plain",
            data="test",
            checksum="x" * 32,
        )
        assert len(data.checksum) == 32

        data = AgentData(
            content_type="text/plain",
            data="test",
            checksum="x" * 128,
        )
        assert len(data.checksum) == 128

    # --- Invalid Cases ---

    def test_invalid_content_type_empty(self):
        """Test that empty content_type raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(content_type="", data="test")

    def test_invalid_content_type_pattern(self):
        """Test that invalid content_type pattern raises error."""
        invalid_types = [
            "text",           # missing slash
            "text/",          # missing subtype
            "/plain",         # missing type
            "TEXT/PLAIN",     # uppercase
            "text / plain",   # space
            "text/html/extra", # too many slashes
        ]
        for ct in invalid_types:
            with pytest.raises(PydanticValidationError):
                AgentData(content_type=ct, data="test")

    def test_invalid_encoding(self):
        """Test that invalid encoding raises error."""
        invalid_encodings = ["utf8", "UTF-8", "base64!", "hex ", ""]
        for enc in invalid_encodings:
            with pytest.raises(PydanticValidationError):
                AgentData(
                    content_type="text/plain",
                    data="test",
                    encoding=enc,
                )

    def test_invalid_checksum_too_short(self):
        """Test that checksum < 32 chars raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(
                content_type="text/plain",
                data="test",
                checksum="x" * 31,
            )

    def test_invalid_checksum_too_long(self):
        """Test that checksum > 128 chars raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(
                content_type="text/plain",
                data="test",
                checksum="x" * 129,
            )

    def test_missing_content_type(self):
        """Test that missing content_type raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(data="test")

    def test_missing_data(self):
        """Test that missing data raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(content_type="text/plain")

    def test_invalid_data_type(self):
        """Test that invalid data type (int) raises error."""
        with pytest.raises(PydanticValidationError):
            AgentData(content_type="text/plain", data=42)

    def test_invalid_data_type_list(self):
        """Test that list data raises error (must be str, bytes, or dict)."""
        with pytest.raises(PydanticValidationError):
            AgentData(content_type="text/plain", data=[1, 2, 3])


# ---------------------------------------------------------------------------
# ConfigurationSchema Tests
# ---------------------------------------------------------------------------

class TestConfigurationSchema:
    """Test ConfigurationSchema validation."""

    def test_valid_minimal(self):
        """Test creation with only required fields."""
        config = ConfigurationSchema(
            agent_name="worker-1",
            log_level="INFO",
            max_retries=3,
        )
        assert config.agent_name == "worker-1"
        assert config.log_level == "INFO"
        assert config.max_retries == 3

    def test_valid_with_all_fields(self):
        """Test creation with all fields."""
        config = ConfigurationSchema(
            agent_name="scanner-42",
            log_level="DEBUG",
            max_retries=10,
            timeout=300,
            features={"tls": True, "rate_limit": 100},
        )
        assert config.agent_name == "scanner-42"
        assert config.log_level == "DEBUG"
        assert config.max_retries == 10
        assert config.timeout == 300
        assert config.features == {"tls": True, "rate_limit": 100}

    def test_default_timeout(self):
        """Test that timeout defaults to 30."""
        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=3,
        )
        assert config.timeout == 30

    def test_default_features(self):
        """Test that features defaults to empty dict."""
        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=3,
        )
        assert config.features == {}

    def test_valid_log_levels(self):
        """Test all valid log levels."""
        for level in ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]:
            config = ConfigurationSchema(
                agent_name="test",
                log_level=level,
                max_retries=3,
            )
            assert config.log_level == level

    def test_valid_max_retries_boundaries(self):
        """Test max_retries at min and max values."""
        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=0,
        )
        assert config.max_retries == 0

        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=10,
        )
        assert config.max_retries == 10

    def test_valid_timeout_boundaries(self):
        """Test timeout at min and max values."""
        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=3,
            timeout=1,
        )
        assert config.timeout == 1

        config = ConfigurationSchema(
            agent_name="test",
            log_level="INFO",
            max_retries=3,
            timeout=3600,
        )
        assert config.timeout == 3600

    def test_valid_agent_name_patterns(self):
        """Test various valid agent name patterns."""
        valid_names = [
            "agent-1",
            "scanner.prod",
            "worker_v2",
            "a" * 64,
        ]
        for name in valid_names:
            config = ConfigurationSchema(
                agent_name=name,
                log_level="INFO",
                max_retries=3,
            )
            assert config.agent_name == name

    # --- Invalid Cases ---

    def test_invalid_agent_name_empty(self):
        """Test that empty agent_name raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="",
                log_level="INFO",
                max_retries=3,
            )

    def test_invalid_agent_name_too_long(self):
        """Test that agent_name > 64 chars raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="x" * 65,
                log_level="INFO",
                max_retries=3,
            )

    def test_invalid_agent_name_pattern(self):
        """Test that agent_name with invalid characters raises error."""
        invalid_names = [
            "agent name",   # space
            "agent!name",   # exclamation
            "agent@host",   # @
            "agent#1",      # #
            "agent/name",   # slash
        ]
        for name in invalid_names:
            with pytest.raises(PydanticValidationError):
                ConfigurationSchema(
                    agent_name=name,
                    log_level="INFO",
                    max_retries=3,
                )

    def test_invalid_log_level(self):
        """Test that invalid log level raises error."""
        invalid_levels = ["info", "debug", "WARN", "FATAL", "", "INFO "]
        for level in invalid_levels:
            with pytest.raises(PydanticValidationError):
                ConfigurationSchema(
                    agent_name="test",
                    log_level=level,
                    max_retries=3,
                )

    def test_invalid_max_retries_negative(self):
        """Test that negative max_retries raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="test",
                log_level="INFO",
                max_retries=-1,
            )

    def test_invalid_max_retries_too_high(self):
        """Test that max_retries > 10 raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="test",
                log_level="INFO",
                max_retries=11,
            )

    def test_invalid_timeout_too_low(self):
        """Test that timeout < 1 raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="test",
                log_level="INFO",
                max_retries=3,
                timeout=0,
            )

    def test_invalid_timeout_too_high(self):
        """Test that timeout > 3600 raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="test",
                log_level="INFO",
                max_retries=3,
                timeout=3601,
            )

    def test_missing_required_fields(self):
        """Test that missing required fields raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema()  # missing all required

        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(agent_name="test")  # missing log_level and max_retries

        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(agent_name="test", log_level="INFO")  # missing max_retries

    def test_invalid_features_type(self):
        """Test that non-dict features raises error."""
        with pytest.raises(PydanticValidationError):
            ConfigurationSchema(
                agent_name="test",
                log_level="INFO",
                max_retries=3,
                features="not_a_dict",
            )


# ---------------------------------------------------------------------------
# Integration / Cross-Schema Tests
# ---------------------------------------------------------------------------

class TestSchemaIntegration:
    """Test interactions between schemas and real-world usage patterns."""

    def test_agent_command_with_data_payload(self):
        """Test AgentCommand with AgentData as payload."""
        inner_data = AgentData(content_type="text/plain", data="scan result")
        cmd = AgentCommand(
            action="process",
            target="analyzer",
            payload={"data": inner_data.dict()},
        )
        assert cmd.payload["data"]["content_type"] == "text/plain"
        assert cmd.payload["data"]["data"] == "scan result"

    def test_configuration_with_nested_validation(self):
        """Test ConfigurationSchema with complex nested features."""
        config = ConfigurationSchema(
            agent_name="coordinator",
            log_level="DEBUG",
            max_retries=5,
            timeout=120,
            features={
                "plugins": ["auth", "logging"],
                "limits": {"cpu": 0.5, "memory": 256},
                "enabled": True,
            },
        )
        assert config.features["plugins"] == ["auth", "logging"]
        assert config.features["limits"]["cpu"] == 0.5

    def test_serialization_roundtrip(self):
        """Test that schemas serialize and deserialize correctly."""
        original = AgentCommand(
            action="deploy",
            target="node-1",
            payload={"version": "2.0"},
            priority=75,
        )
        data = original.dict()
        restored = AgentCommand(**data)
        assert restored.action == original.action
        assert restored.target == original.target
        assert restored.payload == original.payload
        assert restored.priority == original.priority
        # timestamp may differ slightly due to serialization, check type
        assert isinstance(restored.timestamp, datetime)

    def test_json_serialization(self):
        """Test that schemas can be serialized to JSON."""
        cmd = AgentCommand(action="test", target="t")
        json_str = cmd.json()
        assert '"action": "test"' in json_str
        assert '"target": "t"' in json_str

        # Verify it can be parsed back
        import json as json_lib
        parsed = json_lib.loads(json_str)
        assert parsed["action"] == "test"
        assert parsed["target"] == "t"