# Generated by Devo (Lead Developer)
[START]
"""
Task Arbiter - Intelligent Resource Distribution for Swarm V2
Extends the Resource Arbiter to intelligently distribute CPU/GPU compute across all agents.
Monitors system tasks, classifies workload complexity, and offloads to optimal compute resources.

Performance Optimizations:
- O(log n) priority queue via heapq (replaced O(n) deque scan)
- O(1) duplicate detection via set lookup
- Thread-safe async operations with asyncio.Lock
- Consistent __hash__/__eq__ contract for set operations
"""

import asyncio
import heapq
import psutil
import threading
import os
from typing import Dict, List, Optional, Callable, Any
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from collections import deque
import logging

from swarm_v2.core.resource_arbiter import get_resource_arbiter, ResourceArbiter
from swarm_v2.core.attempt_sampler import get_attempt_sampler

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("TaskArbiter")

class TaskComplexity(Enum):
    """Classification of task complexity for resource allocation."""
    LOW = "low"          # CPU-only, lightweight
    MEDIUM = "medium"   # May benefit from GPU
    HIGH = "high"       # Requires GPU/model inference
    CRITICAL = "critical"  # Full system resources


class MaintenanceTaskType(Enum):
    """Types of maintenance tasks for dynamic scheduling."""
    MEMORY_PRUNING = "memory_pruning"
    LOG_ROTATION = "log_rotation"
    CACHE_CLEANUP = "cache_cleanup"
    METRICS_COLLECTION = "metrics_collection"
    HEALTH_CHECK = "health_check"
    GARBAGE_COLLECTION = "garbage_collection"
    INDEX_OPTIMIZATION = "index_optimization"
    TEMP_FILE_CLEANUP = "temp_file_cleanup"
    EVOLUTIONARY_CYCLE = "evolutionary_cycle" # Phase 16: Autonomous self-improvement


class UsageWindow(Enum):
    """System usage windows for task scheduling."""
    LOW_USAGE = "low_usage"       # < 20% CPU, ideal for maintenance
    NORMAL_USAGE = "normal_usage"  # 20-60% CPU
    HIGH_USAGE = "high_usage"     # 60-80% CPU
    CRITICAL_USAGE = "critical_usage"  # > 80% CPU

class ComputeTarget(Enum):
    """Available compute targets for task execution."""
    CPU_CORES = "cpu_cores"
    GPU_MODEL = "gpu_model" 
    HYBRID = "hybrid"  # CPU preprocessing + GPU inference
    REMOTE_SWARM = "remote_swarm" # Phase 15: Offload to another Swarm OS instance


@dataclass(order=False)  # Disable auto-generated comparison; we define custom __lt__
class Task:
    """Represents a task to be distributed. Uses heapq for priority ordering.
    
    Performance note: __lt__ is inverted for heapq min-heap behavior.
    Higher priority value = more urgent, but heapq pops smallest first.
    We compare in reverse: self.priority > other.priority means self is more urgent.
    """
    task_id: str
    task_type: str  # "llm", "file_io", "computation", "analysis"
    complexity: TaskComplexity
    payload: Any
    callback: Optional[Callable] = None
    priority: int = 0  # Higher = more urgent
    created_at: datetime = field(default_factory=datetime.now)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    result: Any = None
    error: Optional[str] = None
    gpu_model: Optional[str] = None

    def __lt__(self, other: 'Task') -> bool:
        """Comparison for heapq: higher priority = more urgent = popped first.
        
        heapq is a min-heap, so we invert: priority 0 (highest urgency)
        should be popped first. We use negative priority internally.
        """
        if not isinstance(other, Task):
            return NotImplemented
        # Higher priority value = more urgent, but heapq pops smallest first
        # So we compare in reverse: self.priority > other.priority means self is more urgent
        return self.priority > other.priority
    
    def __eq__(self, other: object) -> bool:
        """Equality based on task_id for set operations and duplicate detection."""
        if not isinstance(other, Task):
            return NotImplemented
        return self.task_id == other.task_id
    
    def __hash__(self) -> int:
        """Hash based on task_id for O(1) set membership."""
        return hash(self.task_id)


class PriorityTaskQueue:
    """Thread-safe priority queue using heapq for O(log n) operations.
    
    Replaces the previous deque-based implementation which required O(n) scans
    for priority resolution. This implementation provides:
    - O(log n) push/pop operations
    - O(1) peek operation
    - O(1) duplicate detection via set
    - Thread-safe async operations with asyncio.Lock
    """
    
    def __init__(self):
        self._heap: list[Task] = []
        self._lock = asyncio.Lock()
        self._task_ids: set[str] = set()  # For O(1) duplicate detection
    
    async def push(self, task: Task) -> None:
        """Push a task onto the priority queue. O(log n)."""
        async with self._lock:
            if task.task_id in self._task_ids:
                logger.warning(f"Duplicate task ID detected: {task.task_id}")
                return
            heapq.heappush(self._heap, task)
            self._task_ids.add(task.task_id)
            logger.debug(f"Task {task.task_id} pushed. Queue size: {len(self._heap)}")
    
    async def pop(self) -> Optional[Task]:
        """Pop the highest-priority task. O(log n)."""
        async with self._lock:
            if not self._heap:
                return None
            task = heapq.heappop(self._heap)
            self._task_ids.discard(task.task_id)
            logger.debug(f"Task {task.task_id} popped. Queue size: {len(self._heap)}")
            return task
    
    async def peek(self) -> Optional[Task]:
        """View the highest-priority task without removing it. O(1)."""
        async with self._lock:
            return self._heap[0] if self._heap else None
    
    async def remove(self, task_id: str) -> Optional[Task]:
        """Remove a specific task by ID. O(n) worst-case, but rare operation.
        
        Uses swap-with-last pattern to avoid O(n) shift cost.
        """
        async with self._lock:
            for i, task in enumerate(self._heap):
                if task.task_id == task_id:
                    # Swap with last element and pop (O(1) removal)
                    self._heap[i] = self._heap[-1]
                    self._heap.pop()
                    heapq.heapify(self._heap)  # Restore heap invariant O(n)
                    self._task_ids.discard(task_id)
                    logger.info(f"Task {task_id} removed from queue")
                    return task
            logger.warning(f"Task {task_id} not found in queue")
            return None
    
    async def size(self) -> int:
        """Return the number of tasks in the queue. O(1)."""
        async with self._lock:
            return len(self._heap)
    
    async def clear(self) -> None:
        """Clear all tasks. O(1)."""
        async with self._lock:
            self._heap.clear()
            self._task_ids.clear()
            logger.info("Task queue cleared")
    
    async def get_all_tasks(self) -> List[Task]:
        """Return a copy of all tasks in the queue. O(n)."""
        async with self._lock:
            return list(self._heap)


@dataclass 
class AgentWorkload:
    """Tracks an agent's current workload."""
    agent_id: str
    role: str
    current_task: Optional[Task] = None
    cpu_affinity: List[int] = field(default_factory=list)
    gpu_model: Optional[str] = None
    is_busy: bool = False
    task_history: List[str] = field(default_factory=list)


@dataclass
class MaintenanceTask:
    """Represents a maintenance task for dynamic scheduling."""
    task_id: str
    task_type: MaintenanceTaskType
    priority: int = 0  # Lower = less urgent (maintenance is low priority)
    estimated_duration_sec: float = 5.0
    last_run: Optional[datetime] = None
    interval_sec: float = 300.0  # Default: run every 5 minutes
    enabled: bool = True
    callback: Optional[Callable] = None
    
    def is_due(self) -> bool:
        """Check if maintenance task is due to run."""
        if not self.enabled:
            return False
        if self.last_run is None:
            return True
        elapsed = (datetime.now() - self.last_run).total_seconds()
        return elapsed >= self.interval_sec


@dataclass
class UsageMetrics:
    """Tracks system usage for dynamic scheduling decisions."""
    cpu_percent: float = 0.0
    memory_percent: float = 0.0
    gpu_utilization: Optional[float] = None
    gpu_memory_used: Optional[float] = None
    active_tasks: int = 0
    queue_depth: int = 0
    timestamp: datetime = field(default_factory=datetime.now)
    
    def get_usage_window(self) -> UsageWindow:
        """Determine the current usage window based on CPU utilization."""
        if self.cpu_percent < 20:
            return UsageWindow.LOW_USAGE
        elif self.cpu_percent < 60:
            return UsageWindow.NORMAL_USAGE
        elif self.cpu_percent < 80:
            return UsageWindow.HIGH_USAGE
        else:
            return UsageWindow.CRITICAL_USAGE


class TaskArbiter:
    """Intelligent Resource Distribution for Swarm V2.
    
    Distributes CPU/GPU compute across all agents using a priority queue.
    Monitors system tasks, classifies workload complexity, and offloads
    to optimal compute resources.
    
    Performance improvements over previous implementation:
    - O(log n) task submission/retrieval via heapq
    - O(1) duplicate detection via set
    - Thread-safe async operations
    """
    
    def __init__(self, max_concurrent_tasks: int = 10, resource_arbiter: Optional[ResourceArbiter] = None):
        self.task_queue = PriorityTaskQueue()
        self.max_concurrent_tasks = max_concurrent_tasks
        self.active_tasks: Dict[str, Task] = {}
        self.agent_workloads: Dict[str, AgentWorkload] = {}
        self.maintenance_tasks: Dict[str, MaintenanceTask] = {}
        self.resource_arbiter = resource_arbiter or get_resource_arbiter()
        self.attempt_sampler = get_attempt_sampler()
        self._lock = asyncio.Lock()
        self._running = False
        self._maintenance_interval = 60.0  # Check maintenance every 60 seconds
        self._metrics_history: deque[UsageMetrics] = deque(maxlen=100)  # Keep last 100 metrics
        self._usage_window = UsageWindow.NORMAL_USAGE
        
        # Initialize default maintenance tasks
        self._init_maintenance_tasks()
        
        logger.info(f"TaskArbiter initialized with max_concurrent_tasks={max_concurrent_tasks}")
    
    def _init_maintenance_tasks(self) -> None:
        """Initialize default maintenance tasks with appropriate intervals."""
        maintenance_configs = [
            (MaintenanceTaskType.MEMORY_PRUNING, 300.0, 3),
            (MaintenanceTaskType.LOG_ROTATION, 3600.0, 1),
            (MaintenanceTaskType.CACHE_CLEANUP, 600.0, 2),
            (MaintenanceTaskType.METRICS_COLLECTION, 60.0, 5),
            (MaintenanceTaskType.HEALTH_CHECK, 30.0, 4),
            (MaintenanceTaskType.GARBAGE_COLLECTION, 1800.0, 1),
            (MaintenanceTaskType.INDEX_OPTIMIZATION, 7200.0, 1),
            (MaintenanceTaskType.TEMP_FILE_CLEANUP, 900.0, 2),
            (MaintenanceTaskType.EVOLUTIONARY_CYCLE, 86400.0, 0),  # Once per day
        ]
        
        for task_type, interval, priority in maintenance_configs:
            task = MaintenanceTask(
                task_id=f"maint_{task_type.value}",
                task_type=task_type,
                priority=priority,
                interval_sec=interval,
                estimated_duration_sec=5.0 if task_type != MaintenanceTaskType.EVOLUTIONARY_CYCLE else 60.0
            )
            self.maintenance_tasks[task.task_id] = task
    
    async def submit_task(self, task: Task) -> str:
        """Submit a task for distribution. O(log n) instead of O(n).
        
        Args:
            task: The Task to submit
            
        Returns:
            The task_id of the submitted task
        """
        await self.task_queue.push(task)
        logger.info(f"Task {task.task_id} submitted with priority {task.priority}")
        return task.task_id
    
    async def get_next_task(self) -> Optional[Task]:
        """Get the highest-priority task. O(log n) instead of O(n).
        
        Returns:
            The highest-priority Task, or None if queue is empty
        """
        return await self.task_queue.pop()
    
    async def cancel_task(self, task_id: str) -> bool:
        """Cancel a pending task by ID.
        
        Args:
            task_id: The ID of the task to cancel
            
        Returns:
            True if task was found and cancelled, False otherwise
        """
        task = await self.task_queue.remove(task_id)
        if task:
            logger.info(f"Task {task_id} cancelled")
            return True
        logger.warning(f"Task {task_id} not found for cancellation")
        return False
    
    async def peek_next_task(self) -> Optional[Task]:
        """View the highest-priority task without removing it. O(1).
        
        Returns:
            The highest-priority Task, or None if queue is empty
        """
        return await self.task_queue.peek()
    
    async def get_queue_size(self) -> int:
        """Get the current number of tasks in the queue. O(1)."""
        return await self.task_queue.size()
    
    async def register_agent(self, agent_id: str, role: str, cpu_affinity: Optional[List[int]] = None,
                            gpu_model: Optional[str] = None) -> None:
        """Register an agent for task distribution.
        
        Args:
            agent_id: Unique identifier for the agent
            role: The agent's role (e.g., "llm", "file_io", "computation")
            cpu_affinity: List of CPU cores the agent is pinned to
            gpu_model: GPU model if the agent has GPU access
        """
        async with self._lock:
            if agent_id in self.agent_workloads:
                logger.warning(f"Agent {agent_id} already registered, updating configuration")
            
            self.agent_workloads[agent_id] = AgentWorkload(
                agent_id=agent_id,
                role=role,
                cpu_affinity=cpu_affinity or [],
                gpu_model=gpu_model,
                is_busy=False
            )
            logger.info(f"Agent {agent_id} registered with role={role}")
    
    async def unregister_agent(self, agent_id: str) -> bool:
        """Unregister an agent from task distribution.
        
        Args:
            agent_id: The agent to unregister
            
        Returns:
            True if agent was found and unregistered, False otherwise
        """
        async with self._lock:
            if agent_id in self.agent_workloads:
                del self.agent_workloads[agent_id]
                logger.info(f"Agent {agent_id} unregistered")
                return True
            logger.warning(f"Agent {agent_id} not found for unregistration")
            return False
    
    async def assign_task_to_agent(self, agent_id: str, task: Task) -> bool:
        """Assign a task to a specific agent.
        
        Args:
            agent_id: The agent to assign the task to
            task: The task to assign
            
        Returns:
            True if assignment was successful, False if agent is busy or not found
        """
        async with self._lock:
            workload = self.agent_workloads.get(agent_id)
            if not workload:
                logger.error(f"Agent {agent_id} not found")
                return False
            
            if workload.is_busy:
                logger.warning(f"Agent {agent_id} is busy, cannot assign task {task.task_id}")
                return False
            
            workload.current_task = task
            workload.is_busy = True
            workload.task_history.append(task.task_id)
            task.started_at = datetime.now()
            self.active_tasks[task.task_id] = task
            
            logger.info(f"Task {task.task_id} assigned to agent {agent_id}")
            return True
    
    async def complete_task(self, task_id: str, result: Any = None, error: Optional[str] = None) -> bool:
        """Mark a task as completed and free the assigned agent.
        
        Args:
            task_id: The ID of the completed task
            result: The result of the task execution
            error: Error message if the task failed
            
        Returns:
            True if task was found and completed, False otherwise
        """
        async with self._lock:
            task = self.active_tasks.pop(task_id, None)
            if not task:
                logger.warning(f"Task {task_id} not found in active tasks")
                return False
            
            task.completed_at = datetime.now()
            task.result = result
            task.error = error
            
            # Find and free the agent that was working on this task
            for agent_id, workload in self.agent_workloads.items():
                if workload.current_task and workload.current_task.task_id == task_id:
                    workload.current_task = None
                    workload.is_busy = False
                    logger.info(f"Agent {agent_id} freed from task {task_id}")
                    break
            
            # Execute callback if provided
            if task.callback and not error:
                try:
                    if asyncio.iscoroutinefunction(task.callback):
                        await task.callback(result)
                    else:
                        task.callback(result)
                except Exception as e:
                    logger.error(f"Callback execution failed for task {task_id}: {e}")
            
            logger.info(f"Task {task_id} completed{' with error' if error else ''}")
            return True
    
    async def get_available_agents(self, task_type: Optional[str] = None,
                                   requires_gpu: bool = False) -> List[str]:
        """Get list of available agents, optionally filtered by criteria.
        
        Args:
            task_type: Optional filter for agent role
            requires_gpu: If True, only return agents with GPU access
            
        Returns:
            List of agent IDs that are available and match the criteria
        """
        async with self._lock:
            available = []
            for agent_id, workload in self.agent_workloads.items():
                if workload.is_busy:
                    continue
                if task_type and workload.role != task_type:
                    continue
                if requires_gpu and not workload.gpu_model:
                    continue
                available.append(agent_id)
            return available
    
    async def collect_metrics(self) -> UsageMetrics:
        """Collect current system usage metrics.
        
        Returns:
            UsageMetrics with current system state
        """
        metrics = UsageMetrics(
            cpu_percent=psutil.cpu_percent(interval=0.1),
            memory_percent=psutil.virtual_memory().percent,
            active_tasks=len(self.active_tasks),
            queue_depth=await self.task_queue.size()
        )
        
        # Attempt to get GPU metrics if available
        try:
            import pynvml
            pynvml.nvmlInit()
            handle = pynvml.nvmlDeviceGetHandleByIndex(0)
            util = pynvml.nvmlDeviceGetUtilizationRates(handle)
            memory = pynvml.nvmlDeviceGetMemoryInfo(handle)
            metrics.gpu_utilization = util.gpu
            metrics.gpu_memory_used = memory.used / memory.total * 100
        except (ImportError, Exception):
            pass  # GPU metrics not available
        
        self._metrics_history.append(metrics)
        self._usage_window = metrics.get_usage_window()
        
        return metrics
    
    async def run_maintenance_cycle(self) -> None:
        """Execute due maintenance tasks based on current usage window."""
        current_window = self._usage_window
        
        for maint_task in self.maintenance_tasks.values():
            if not maint_task.is_due():
                continue
            
            # Skip non-critical maintenance during high usage
            if current_window in (UsageWindow.HIGH_USAGE, UsageWindow.CRITICAL_USAGE):
                if maint_task.priority < 3:  # Only run high-priority maintenance
                    continue
            
            logger.info(f"Running maintenance task: {maint_task.task_type.value}")
            try:
                if maint_task.callback:
                    if asyncio.iscoroutinefunction(maint_task.callback):
                        await maint_task.callback()
                    else:
                        maint_task.callback()
                else:
                    # Default maintenance behavior based on type
                    await self._execute_default_maintenance(maint_task.task_type)
                
                maint_task.last_run = datetime.now()
                logger.info(f"Maintenance task {maint_task.task_type.value} completed")
            except Exception as e:
                logger.error(f"Maintenance task {maint_task.task_type.value} failed: {e}")
    
    async def _execute_default_maintenance(self, task_type: MaintenanceTaskType) -> None:
        """Execute default maintenance behavior for a given task type."""
        if task_type == MaintenanceTaskType.MEMORY_PRUNING:
            import gc
            gc.collect()
            logger.debug("Memory pruning completed")
        
        elif task_type == MaintenanceTaskType.CACHE_CLEANUP:
            # Clear completed task results from memory
            async with self._lock:
                completed_ids = [
                    tid for tid, task in self.active_tasks.items()
                    if task.completed_at is not None
                ]
                for tid in completed_ids:
                    del self.active_tasks[tid]
            logger.debug(f"Cache cleanup: removed {len(completed_ids)} completed tasks")
        
        elif task_type == MaintenanceTaskType.METRICS_COLLECTION:
            await self.collect_metrics()
        
        elif task_type == MaintenanceTaskType.HEALTH_CHECK:
            # Verify all registered agents are responsive
            async with self._lock:
                for agent_id in list(self.agent_workloads.keys()):
                    # In a real implementation, this would ping the agent
                    logger.debug(f"Health check passed for agent {agent_id}")
    
    async def start(self) -> None:
        """Start the TaskArbiter's background processing loop."""
        if self._running:
            logger.warning("TaskArbiter is already running")
            return
        
        self._running = True
        logger.info("TaskArbiter started")
        
        while self._running:
            try:
                # Collect metrics
                await self.collect_metrics()
                
                # Run maintenance cycle
                await self.run_maintenance_cycle()
                
                # Process pending tasks
                if await self.task_queue.size() > 0:
                    available_agents = await self.get_available_agents()
                    if available_agents:
                        task = await self.get_next_task()
                        if task:
                            # Simple round-robin assignment to first available agent
                            agent_id = available_agents[0]
                            await self.assign_task_to_agent(agent_id, task)
                
                await asyncio.sleep(1.0)  # Main loop interval
                
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Error in main loop: {e}", exc_info=True)
                await asyncio.sleep(5.0)  # Back off on error
    
    async def stop(self) -> None:
        """Gracefully stop the TaskArbiter."""
        self._running = False
        logger.info("TaskArbiter stopped")
    
    def get_status(self) -> Dict[str, Any]:
        """Get current status of the TaskArbiter.
        
        Returns:
            Dictionary with current status information
        """
        return {
            "running": self._running,
            "queue_depth": len(self.task_queue._heap) if hasattr(self.task_queue, '_heap') else 0,
            "active_tasks": len(self.active_tasks),
            "registered_agents": len(self.agent_workloads),
            "usage_window": self._usage_window.value,
            "maintenance_tasks": len(self.maintenance_tasks)
        }


# Singleton instance
_task_arbiter_instance: Optional[TaskArbiter] = None

def get_task_arbiter() -> TaskArbiter:
    """Get or create the global TaskArbiter singleton."""
    global _task_arbiter_instance
    if _task_arbiter_instance is None:
        _task_arbiter_instance = TaskArbiter()
    return _task_arbiter_instance