# Generated by Archi (Architect)
import logging
import sys
from pythonjsonlogger import jsonlogger

def setup_logging(log_level: str = "INFO"):
    """
    Configures structured JSON logging for the application.
    Logs are output to stdout, suitable for containerized environments
    and ingestion by log aggregation systems.
    """
    logger = logging.getLogger()
    logger.setLevel(log_level.upper())

    # Clear existing handlers to prevent duplicate logs in case of re-configuration
    if logger.handlers:
        for handler in logger.handlers:
            logger.removeHandler(handler)

    # Create a JSON formatter
    formatter = jsonlogger.JsonFormatter(
        fmt='%(asctime)s %(levelname)s %(name)s %(message)s',
        datefmt='%Y-%m-%dT%H:%M:%S%z',
        rename_fields={'levelname': 'level', 'asctime': 'timestamp'},
        static_fields={'service': 'SwarmOS Health Monitor', 'environment': 'production'}
    )

    # Create a stream handler that writes to stdout
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    # Suppress verbose loggers from libraries if not in DEBUG mode
    if log_level.upper() != "DEBUG":
        logging.getLogger("uvicorn").setLevel(logging.WARNING)
        logging.getLogger("uvicorn.access").setLevel(logging.WARNING)
        logging.getLogger("fastapi").setLevel(logging.WARNING)
        logging.getLogger("gunicorn.error").setLevel(logging.INFO)
        logging.getLogger("gunicorn.access").setLevel(logging.INFO)

    logger.info(f"Logging configured with level: {log_level.upper()}")

# Example usage (in main.py or other modules):
# import logging
# logger = logging.getLogger(__name__)
# logger.info("This is an info message.")
# logger.error("This is an error message.", extra={"custom_field": "value"})