# Generated by Orchestra (Swarm Manager)
"""
CodebaseIndexer: Advanced static analysis engine for swarm_v2.
Crawls the codebase to extract class, method, and docstring signatures
with full type resolution and dependency mapping.
"""

import ast
import os
import hashlib
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple, Any
from dataclasses import dataclass, field, asdict
from datetime import datetime
import json
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
import re

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Signature:
    """Immutable signature representation for caching and comparison."""
    name: str
    type: str  # 'class', 'function', 'method', 'property'
    module: str
    line_number: int
    docstring: Optional[str]
    parameters: Tuple[Tuple[str, Optional[str]], ...]  # (name, type_annotation)
    return_type: Optional[str]
    decorators: Tuple[str, ...]
    dependencies: Tuple[str, ...]  # imported modules
    complexity: int  # cyclomatic complexity estimate
    hash: str = field(init=False)

    def __post_init__(self):
        object.__setattr__(self, 'hash', self._compute_hash())

    def _compute_hash(self) -> str:
        content = f"{self.name}:{self.type}:{self.module}:{self.line_number}:{self.docstring}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]


@dataclass
class ModuleIndex:
    """Represents indexed content of a single module."""
    path: str
    module_name: str
    signatures: Dict[str, Signature]
    imports: Set[str]
    last_modified: float
    file_hash: str
    errors: List[str] = field(default_factory=list)


class AdvancedDocstringParser:
    """Parses docstrings into structured metadata."""

    @staticmethod
    def parse(docstring: Optional[str]) -> Dict[str, Any]:
        if not docstring:
            return {"summary": "", "params": {}, "returns": "", "raises": []}

        result = {
            "summary": "",
            "params": {},
            "returns": "",
            "raises": []
        }

        lines = docstring.strip().split('\n')
        if not lines:
            return result

        # Extract summary (first paragraph)
        summary_lines = []
        for line in lines:
            stripped = line.strip()
            if not stripped:
                break
            summary_lines.append(stripped)
        result["summary"] = ' '.join(summary_lines)

        # Parse Google-style sections
        current_section = None
        param_pattern = re.compile(r'^\s*(\w+)\s*\((.+?)\):\s*(.+)$')
        for line in lines:
            stripped = line.strip()
            if stripped.lower().startswith('args:'):
                current_section = 'params'
                continue
            elif stripped.lower().startswith('returns:'):
                current_section = 'returns'
                continue
            elif stripped.lower().startswith('raises:'):
                current_section = 'raises'
                continue

            if current_section == 'params':
                match = param_pattern.match(stripped)
                if match:
                    result["params"][match.group(1)] = {
                        "type": match.group(2),
                        "description": match.group(3)
                    }
            elif current_section == 'returns':
                result["returns"] = stripped
            elif current_section == 'raises':
                result["raises"].append(stripped)

        return result


class ComplexityAnalyzer:
    """Estimates cyclomatic complexity of AST nodes."""

    @staticmethod
    def analyze(node: ast.AST) -> int:
        """Count decision points as complexity metric."""
        complexity = 1  # Base complexity

        for child in ast.walk(node):
            if isinstance(child, (ast.If, ast.While, ast.For, ast.ExceptHandler)):
                complexity += 1
            elif isinstance(child, ast.BoolOp):
                complexity += len(child.values) - 1
            elif isinstance(child, ast.Try):
                complexity += len(child.handlers)
            elif isinstance(child, (ast.And, ast.Or)):
                complexity += 1

        return complexity


class CodebaseIndexer:
    """
    Advanced codebase indexer with multi-threaded crawling,
    dependency resolution, and incremental indexing support.
    """

    def __init__(
        self,
        root_path: str,
        exclude_dirs: Optional[Set[str]] = None,
        max_workers: int = 4,
        cache_path: Optional[str] = None
    ):
        self.root_path = Path(root_path).resolve()
        self.exclude_dirs = exclude_dirs or {'__pycache__', '.git', 'venv', '.env', 'node_modules'}
        self.max_workers = max_workers
        self.cache_path = Path(cache_path) if cache_path else self.root_path / '.index_cache'
        self.cache_path.mkdir(parents=True, exist_ok=True)

        self.modules: Dict[str, ModuleIndex] = {}
        self.global_signatures: Dict[str, Signature] = {}
        self.dependency_graph: Dict[str, Set[str]] = {}
        self._lock = None  # Would use threading.Lock in production

    def crawl(self, full_reindex: bool = False) -> Dict[str, Any]:
        """
        Main entry point: crawl the codebase and build index.
        Returns summary statistics.
        """
        logger.info(f"Starting crawl of {self.root_path}")

        python_files = self._discover_python_files()
        logger.info(f"Discovered {len(python_files)} Python files")

        # Parallel processing of files
        with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            future_to_file = {
                executor.submit(self._index_file, f, full_reindex): f
                for f in python_files
            }

            for future in as_completed(future_to_file):
                file_path = future_to_file[future]
                try:
                    module_index = future.result()
                    if module_index:
                        self.modules[module_index.module_name] = module_index
                        for sig_name, sig in module_index.signatures.items():
                            self.global_signatures[sig_name] = sig
                except Exception as e:
                    logger.error(f"Failed to index {file_path}: {e}")

        # Build dependency graph
        self._build_dependency_graph()

        # Cache the index
        self._save_cache()

        return self._generate_summary()

    def _discover_python_files(self) -> List[Path]:
        """Recursively discover all Python files, respecting exclusions."""
        python_files = []
        for root, dirs, files in os.walk(self.root_path):
            # Modify dirs in-place to skip excluded directories
            dirs[:] = [d for d in dirs if d not in self.exclude_dirs]

            for file in files:
                if file.endswith('.py'):
                    full_path = Path(root) / file
                    python_files.append(full_path)

        return python_files

    def _index_file(self, file_path: Path, force_reindex: bool = False) -> Optional[ModuleIndex]:
        """Index a single Python file."""
        try:
            # Check cache first
            file_stat = file_path.stat()
            file_hash = self._compute_file_hash(file_path)

            if not force_reindex:
                cached = self._load_cached_index(file_path)
                if cached and cached.file_hash == file_hash:
                    return cached

            # Parse the file
            with open(file_path, 'r', encoding='utf-8') as f:
                source = f.read()

            try:
                tree = ast.parse(source, filename=str(file_path))
            except SyntaxError as e:
                logger.warning(f"Syntax error in {file_path}: {e}")
                return ModuleIndex(
                    path=str(file_path),
                    module_name=self._path_to_module(file_path),
                    signatures={},
                    imports=set(),
                    last_modified=file_stat.st_mtime,
                    file_hash=file_hash,
                    errors=[str(e)]
                )

            # Extract module name and imports
            module_name = self._path_to_module(file_path)
            imports = self._extract_imports(tree)

            # Extract signatures
            signatures = {}
            self._extract_signatures(tree, module_name, signatures)

            return ModuleIndex(
                path=str(file_path),
                module_name=module_name,
                signatures=signatures,
                imports=imports,
                last_modified=file_stat.st_mtime,
                file_hash=file_hash
            )

        except Exception as e:
            logger.error(f"Error indexing {file_path}: {e}")
            return None

    def _extract_signatures(
        self,
        node: ast.AST,
        module_name: str,
        signatures: Dict[str, Signature],
        parent_class: Optional[str] = None
    ):
        """Recursively extract signatures from AST nodes."""
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.ClassDef):
                class_sig = self._create_class_signature(child, module_name)
                if class_sig:
                    signatures[class_sig.name] = class_sig

                # Recurse into class body for methods
                self._extract_signatures(
                    child, module_name, signatures,
                    parent_class=child.name
                )

            elif isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                sig = self._create_function_signature(
                    child, module_name, parent_class
                )
                if sig:
                    signatures[sig.name] = sig

    def _create_class_signature(
        self,
        node: ast.ClassDef,
        module_name: str
    ) -> Optional[Signature]:
        """Create Signature for a class definition."""
        try:
            docstring = ast.get_docstring(node)
            decorators = tuple(
                self._get_decorator_name(d) for d in node.decorator_list
            )

            # Extract base classes as dependencies
            bases = []
            for base in node.bases:
                if isinstance(base, ast.Name):
                    bases.append(base.id)
                elif isinstance(base, ast.Attribute):
                    bases.append(f"{self._get_attribute_name(base)}")

            return Signature(
                name=node.name,
                type='class',
                module=module_name,
                line_number=node.lineno,
                docstring=docstring,
                parameters=(),
                return_type=None,
                decorators=decorators,
                dependencies=tuple(bases),
                complexity=ComplexityAnalyzer.analyze(node)
            )
        except Exception as e:
            logger.debug(f"Error creating class signature for {node.name}: {e}")
            return None

    def _create_function_signature(
        self,
        node: ast.FunctionDef,
        module_name: str,
        parent_class: Optional[str] = None
    ) -> Optional[Signature]:
        """Create Signature for a function/method definition."""
        try:
            docstring = ast.get_docstring(node)
            decorators = tuple(
                self._get_decorator_name(d) for d in node.decorator_list
            )

            # Extract parameters with type annotations
            params = []
            for arg in node.args.args:
                arg_name = arg.arg
                arg_type = None
                if arg.annotation:
                    arg_type = self._resolve_annotation(arg.annotation)
                params.append((arg_name, arg_type))

            # Handle *args and **kwargs
            if node.args.vararg:
                params.append((f"*{node.args.vararg.arg}", None))
            if node.args.kwarg:
                params.append((f"**{node.args.kwarg.arg}", None))

            # Extract return type
            return_type = None
            if node.returns:
                return_type = self._resolve_annotation(node.returns)

            # Determine type
            sig_type = 'method' if parent_class else 'function'
            if any(d == 'property' for d in decorators):
                sig_type = 'property'

            # Build full name with parent class
            name = f"{parent_class}.{node.name}" if parent_class else node.name

            return Signature(
                name=name,
                type=sig_type,
                module=module_name,
                line_number=node.lineno,
                docstring=docstring,
                parameters=tuple(params),
                return_type=return_type,
                decorators=decorators,
                dependencies=(),
                complexity=ComplexityAnalyzer.analyze(node)
            )
        except Exception as e:
            logger.debug(f"Error creating function signature for {node.name}: {e}")
            return None

    def _resolve_annotation(self, annotation: ast.AST) -> str:
        """Resolve type annotation AST node to string representation."""
        if isinstance(annotation, ast.Name):
            return annotation.id
        elif isinstance(annotation, ast.Attribute):
            return self._get_attribute_name(annotation)
        elif isinstance(annotation, ast.Subscript):
            # Handle generic types like List[str], Dict[str, int]
            value = self._resolve_annotation(annotation.value)
            if isinstance(annotation.slice, ast.Index):
                slice_val = self._resolve_annotation(annotation.slice.value)
            elif isinstance(annotation.slice, ast.Tuple):
                slice_val = ', '.join(
                    self._resolve_annotation(el) for el in annotation.slice.elts
                )
            else:
                slice_val = self._resolve_annotation(annotation.slice)
            return f"{value}[{slice_val}]"
        elif isinstance(annotation, ast.Constant):
            return str(annotation.value)
        elif isinstance(annotation, ast.BinOp):
            # Handle Union types
            left = self._resolve_annotation(annotation.left)
            right = self._resolve_annotation(annotation.right)
            return f"{left} | {right}"
        return "Any"

    def _get_attribute_name(self, node: ast.Attribute) -> str:
        """Get full attribute name like 'module.ClassName'."""
        parts = []
        current = node
        while isinstance(current, ast.Attribute):
            parts.append(current.attr)
            current = current.value
        if isinstance(current, ast.Name):
            parts.append(current.id)
        return '.'.join(reversed(parts))

    def _get_decorator_name(self, decorator: ast.AST) -> str:
        """Extract decorator name."""
        if isinstance(decorator, ast.Name):
            return decorator.id
        elif isinstance(decorator, ast.Attribute):
            return self._get_attribute_name(decorator)
        elif isinstance(decorator, ast.Call):
            if isinstance(decorator.func, ast.Name):
                return decorator.func.id
            elif isinstance(decorator.func, ast.Attribute):
                return self._get_attribute_name(decorator.func)
        return str(decorator)

    def _extract_imports(self, tree: ast.AST) -> Set[str]:
        """Extract all imports from AST."""
        imports = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module)
        return imports

    def _path_to_module(self, file_path: Path) -> str:
        """Convert file path to Python module path."""
        rel_path = file_path.relative_to(self.root_path)
        module_path = rel_path.with_suffix('')
        return str(module_path).replace(os.sep, '.')

    def _compute_file_hash(self, file_path: Path) -> str:
        """Compute SHA256 hash of file contents."""
        hasher = hashlib.sha256()
        with open(file_path, 'rb') as f:
            for chunk in iter(lambda: f.read(4096), b''):
                hasher.update(chunk)
        return hasher.hexdigest()

    def _build_dependency_graph(self):
        """Build module dependency graph from imports."""
        self.dependency_graph = {}
        for module_name, module_index in self.modules.items():
            self.dependency_graph[module_name] = module_index.imports

    def _save_cache(self):
        """Save index to cache file."""
        try:
            cache_file = self.cache_path / 'index_cache.json'
            cache_data = {
                'timestamp': datetime.now().isoformat(),
                'modules': {
                    name: {
                        'path': idx.path,
                        'module_name': idx.module_name,
                        'file_hash': idx.file_hash,
                        'last_modified': idx.last_modified,
                        'signature_count': len(idx.signatures),
                        'imports': list(idx.imports)
                    }
                    for name, idx in self.modules.items()
                }
            }
            with open(cache_file, 'w') as f:
                json.dump(cache_data, f, indent=2)
            logger.info(f"Cache saved to {cache_file}")
        except Exception as e:
            logger.error(f"Failed to save cache: {e}")

    def _load_cached_index(self, file_path: Path) -> Optional[ModuleIndex]:
        """Load cached index for a file if it exists and is valid."""
        try:
            cache_file = self.cache_path / 'index_cache.json'
            if not cache_file.exists():
                return None

            with open(cache_file, 'r') as f:
                cache_data = json.load(f)

            module_name = self._path_to_module(file_path)
            if module_name in cache_data.get('modules', {}):
                cached = cache_data['modules'][module_name]
                # Verify file still exists and hash matches
                if file_path.exists():
                    current_hash = self._compute_file_hash(file_path)
                    if current_hash == cached['file_hash']:
                        # Return minimal cached info
                        return ModuleIndex(
                            path=cached['path'],
                            module_name=cached['module_name'],
                            signatures={},
                            imports=set(cached['imports']),
                            last_modified=cached['last_modified'],
                            file_hash=cached['file_hash']
                        )
            return None
        except Exception:
            return None

    def _generate_summary(self) -> Dict[str, Any]:
        """Generate summary statistics of the index."""
        total_signatures = len(self.global_signatures)
        type_counts = {}
        module_counts = len(self.modules)

        for sig in self.global_signatures.values():
            type_counts[sig.type] = type_counts.get(sig.type, 0) + 1

        # Find circular dependencies
        circular_deps = self._find_circular_dependencies()

        return {
            'timestamp': datetime.now().isoformat(),
            'root_path': str(self.root_path),
            'modules_indexed': module_counts,
            'total_signatures': total_signatures,
            'signatures_by_type': type_counts,
            'circular_dependencies': list(circular_deps),
            'dependency_count': len(self.dependency_graph)
        }

    def _find_circular_dependencies(self) -> Set[Tuple[str, str]]:
        """Detect circular dependencies between modules."""
        circular = set()
        visited = set()
        path = []

        def dfs(module: str):
            if module in path:
                idx = path.index(module)
                cycle = tuple(path[idx:] + [module])
                circular.add(cycle)
                return
            if module in visited:
                return

            visited.add(module)
            path.append(module)

            for dep in self.dependency_graph.get(module, set()):
                if dep in self.modules:
                    dfs(dep)

            path.pop()

        for module in self.modules:
            dfs(module)

        return circular

    def query(self, pattern: str, search_type: Optional[str] = None) -> List[Signature]:
        """Query the index for signatures matching a pattern."""
        results = []
        pattern_lower = pattern.lower()

        for sig in self.global_signatures.values():
            if search_type and sig.type != search_type:
                continue

            if (pattern_lower in sig.name.lower() or
                (sig.docstring and pattern_lower in sig.docstring.lower())):
                results.append(sig)

        return sorted(results, key=lambda x: x.name)

    def get_module_dependencies(self, module_name: str) -> Set[str]:
        """Get direct dependencies of a module."""
        return self.dependency_graph.get(module_name, set())

    def get_affected_modules(self, changed_file: str) -> Set[str]:
        """Find all modules that might be affected by a change."""
        changed_module = self._path_to_module(Path(changed_file))
        affected = {changed_module}

        # Find all modules that depend on the changed module
        for module_name, deps in self.dependency_graph.items():
            if changed_module in deps:
                affected.add(module_name)

        return affected


# Singleton instance for global access
_indexer_instance: Optional[CodebaseIndexer] = None


def get_indexer(
    root_path: Optional[str] = None,
    **kwargs
) -> CodebaseIndexer:
    """Get or create the global indexer instance."""
    global _indexer_instance
    if _indexer_instance is None:
        if root_path is None:
            root_path = os.getcwd()
        _indexer_instance = CodebaseIndexer(root_path, **kwargs)
    return _indexer_instance


def index_codebase(full_reindex: bool = False) -> Dict[str, Any]:
    """Convenience function to index the codebase."""
    indexer = get_indexer()
    return indexer.crawl(full_reindex=full_reindex)


if __name__ == '__main__':
    # Quick test
    indexer = CodebaseIndexer('.')
    summary = indexer.crawl()
    print(json.dumps(summary, indent=2))
    print(f"\nFound {summary['total_signatures']} signatures across {summary['modules_indexed']} modules")