# Generated by Devo (Lead Developer)
from typing import Dict, Optional, Any
from .ast import Term

Substitution = Dict[str, Term]

def unify(t1: Term, t2: Term, subst: Substitution = None) -> Optional[Substitution]:
    """
    Implements the Robinson Unification Algorithm.
    Returns the Most General Unifier (MGU) or None if unification fails.
    """
    if subst is None:
        subst = {}

    # Apply current substitutions
    t1 = apply_subst(t1, subst)
    t2 = apply_subst(t2, subst)

    if t1 == t2:
        return subst
    
    if t1.is_variable():
        return unify_var(t1, t2, subst)
    
    if t2.is_variable():
        return unify_var(t2, t1, subst)
    
    if t1.args and t2.args and len(t1.args) == len(t2.args):
        for a1, a2 in zip(t1.args, t2.args):
            subst = unify(a1, a2, subst)
            if subst is None:
                return None
        return subst
    
    return None

def unify_var(var: Term, x: Term, subst: Substitution) -> Optional[Substitution]:
    if var.name in subst:
        return unify(subst[var.name], x, subst)
    if x.is_variable() and x.name in subst:
        return unify(var, subst[x.name], subst)
    if occurs_check(var, x):
        return None # Prevent infinite recursion
    
    new_subst = subst.copy()
    new_subst[var.name] = x
    return new_subst

def occurs_check(var: Term, x: Term) -> bool:
    if var == x:
        return True
    if x.args:
        return any(occurs_check(var, arg) for arg in x.args)
    return False

def apply_subst(term: Term, subst: Substitution) -> Term:
    if term.is_variable() and term.name in subst:
        return apply_subst(subst[term.name], subst)
    if term.args:
        return Term(term.name, [apply_subst(arg, subst) for arg in term.args])
    return term