# Generated by Devo (Lead Developer)
from setuptools import setup, Extension
import sys

kyber_module = Extension(
    'kyber_ctypes_interface',
    sources=['kyber_ctypes_interface.c'],
    extra_compile_args=[
        '-O3',
        '-march=native',
        '-mtune=native',
        '-fstack-protector-strong',
        '-D_FORTIFY_SOURCE=2',
        '-Wall',
        '-Wextra',
        '-Werror'
    ] if sys.platform != 'win32' else ['/O2', '/GL'],
    libraries=['rt'] if sys.platform != 'win32' else []
)

setup(
    name='qkd_gateway',
    version='1.0.0',
    description='Post-Quantum Key Distribution Gateway with FVE enforcement',
    ext_modules=[kyber_module],
    install_requires=[
        'uvloop>=0.17.0',
        'cffi>=1.15.0'
    ],
    python_requires='>=3.10',
    entry_points={
        'console_scripts': [
            'qkd-gateway=gateway:main'
        ]
    }
)