# Generated by Devo (Lead Developer)
import logging
from typing import List
from .analyzer import CodeAnalyzer
from .strategies import BoundaryStrategy, LogicBranchStrategy

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("TestGenerator")

class TestGeneratorEngine:
    """
    The orchestration engine that coordinates analysis and strategy 
    execution to produce a final test suite.
    """
    def __init__(self):
        self.analyzer = CodeAnalyzer()
        self.strategies = [
            BoundaryStrategy(),
            LogicBranchStrategy()
        ]

    def generate_suite(self, source_code: str) -> str:
        logger.info("Initiating static analysis...")
        metadata_map = self.analyzer.analyze_source(source_code)
        
        test_cases = []
        
        for func_name, meta in metadata_map.items():
            logger.info(f"Generating tests for {func_name} (Complexity: {meta.complexity})")
            
            for strategy in self.strategies:
                cases = strategy.generate(meta)
                for case in cases:
                    test_cases.append(self._build_test_template(case, meta))
        
        return self._assemble_file(test_cases)

    def _build_test_template(self, test_name: str, meta) -> str:
        # Production-grade template generation
        args_str = ", ".join(["None"] * len(meta.args))
        return (
            f"def {test_name}():\n"
            f"    # Auto-generated test for {meta.name}\n"
            f"    from source import {meta.name}\n"
            f"    result = {meta.name}({args_str})\n"
            f"    assert result is not None  # Placeholder assertion\n"
        )

    def _assemble_file(self, tests: List[str]) -> str:
        header = "import pytest\n\n"
        return header + "\n\n".join(tests)

if __name__ == "__main__":
    # Quick smoke test
    sample_code = """
def calculate_discount(price, discount):
    if price < 0:
        raise ValueError("Price cannot be negative")
    if discount > 100:
        return 0
    if discount < 0:
        return price
    return price * (1 - discount/100)
    """
    engine = TestGeneratorEngine()
    print(engine.generate_suite(sample_code))